/*
 * This file was automatically generated by EvoSuite
 * Fri May 08 14:56:38 GMT 2020
 */

package main;

import org.junit.Test;
import static org.junit.Assert.*;
import custom_classes.Email;
import custom_classes.HTMLSnippets;
import custom_classes.HideInMenu;
import custom_classes.Id;
import custom_classes.Name;
import custom_classes.PageLinkStatus;
import custom_classes.RegistrationUserSettings;
import custom_classes.SiteMenus;
import custom_classes.SitePages;
import custom_classes.UserPassword;
import custom_classes.UserRoles;
import custom_classes.UserStatus;
import custom_classes.Username;
import custom_classes.WidgetFeedNumberOfPosts;
import custom_classes.WidgetFeedPostContent;
import custom_classes.WidgetFeedTitle;
import custom_classes.WidgetFeedUrl;
import custom_classes.WidgetLocation;
import custom_classes.WidgetLoginTitles;
import custom_classes.WidgetMenus;
import custom_classes.WidgetNumberOfUsers;
import custom_classes.WidgetTextTitles;
import custom_classes.WidgetTotalUser;
import custom_classes.WidgetUnit;
import custom_classes.WidgetUserDisplay;
import custom_classes.WidgetUserType;
import main.ClassUnderTest;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, resetStaticState = true) 
public class ClassUnderTest_ESTest extends ClassUnderTest_ESTest_scaffolding {

  //Test case number: 0
  /*
   * 13 covered goals:
   * Goal 1. main.ClassUnderTest.addEditLoginDetailsAddEditLoginWidgetContainerPage(Lcustom_classes/WidgetLoginTitles;Lcustom_classes/PageLinkStatus;)V: Line 3126
   * Goal 2. main.ClassUnderTest.addLoginWidgetsContainerPage()V: Line 2758
   * Goal 3. main.ClassUnderTest.goToEditCurrentUserAddEditUserContainerPage()V: Line 1333
   * Goal 4. main.ClassUnderTest.goToEditCurrentUserUserListContainerPage()V: Line 919
   * Goal 5. main.ClassUnderTest.goToRolesAddEditUserContainerPage()V: Line 1359
   * Goal 6. main.ClassUnderTest.goToSiteAddEditUserContainerPage()V: Line 1385
   * Goal 7. main.ClassUnderTest.goToSitePagesContainerPage()V: Line 1958
   * Goal 8. main.ClassUnderTest.goToUserListUserListContainerPage()V: Line 983
   * Goal 9. main.ClassUnderTest.goToUsersAddEditLoginWidgetContainerPage()V: Line 3277
   * Goal 10. main.ClassUnderTest.goToUsersDashboardContainerPage()V: Line 775
   * Goal 11. main.ClassUnderTest.goToUsersUserListContainerPage()V: Line 995
   * Goal 12. main.ClassUnderTest.goToWidgetsPagesContainerPage()V: Line 1982
   * Goal 13. main.ClassUnderTest.goToWidgetsWidgetsContainerPage()V: Line 3024
   */

  @Test(timeout = 1001000)
  public void test00()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      classUnderTest0.goToUsersDashboardContainerPage();
      classUnderTest0.goToUserListUserListContainerPage();
      classUnderTest0.goToEditCurrentUserUserListContainerPage();
      classUnderTest0.goToSiteAddEditUserContainerPage();
      classUnderTest0.goToSitePagesContainerPage();
      classUnderTest0.goToWidgetsPagesContainerPage();
      classUnderTest0.goToWidgetsWidgetsContainerPage();
      classUnderTest0.addLoginWidgetsContainerPage();
      WidgetLoginTitles widgetLoginTitles0 = WidgetLoginTitles.LOGIN;
      PageLinkStatus pageLinkStatus0 = PageLinkStatus.DISABLED;
      classUnderTest0.addEditLoginDetailsAddEditLoginWidgetContainerPage(widgetLoginTitles0, pageLinkStatus0);
      classUnderTest0.goToUsersAddEditLoginWidgetContainerPage();
      classUnderTest0.goToUsersUserListContainerPage();
      classUnderTest0.goToEditCurrentUserUserListContainerPage();
      classUnderTest0.goToEditCurrentUserAddEditUserContainerPage();
      classUnderTest0.goToRolesAddEditUserContainerPage();
  }

  //Test case number: 1
  /*
   * 34 covered goals:
   * Goal 1. main.ClassUnderTest.addEditPageAddEditPageContainerPage(Lcustom_classes/SitePages;Lcustom_classes/HTMLSnippets;Lcustom_classes/PageLinkStatus;Lcustom_classes/HideInMenu;)V: Line 2166
   * Goal 2. main.ClassUnderTest.addFeedWidgetDashboardContainerPage(Lcustom_classes/WidgetFeedTitle;Lcustom_classes/WidgetFeedUrl;Lcustom_classes/WidgetFeedNumberOfPosts;Lcustom_classes/WidgetFeedPostContent;)V: Line 515
   * Goal 3. main.ClassUnderTest.addItemAddEditItemPage()V: Line 396
   * Goal 4. main.ClassUnderTest.addLinkPagesContainerPage()V: Line 1706
   * Goal 5. main.ClassUnderTest.addMenuPagesContainerPage(Lcustom_classes/SiteMenus;)V: Line 1727
   * Goal 6. main.ClassUnderTest.addMenuWidgetsContainerPage()V: Line 2772
   * Goal 7. main.ClassUnderTest.addPagePagesContainerPage()V: Line 1747
   * Goal 8. main.ClassUnderTest.addUserUserListContainerPage()V: Line 812
   * Goal 9. main.ClassUnderTest.addUserWidgetDashboardContainerPage(Lcustom_classes/WidgetUserType;Lcustom_classes/WidgetUserDisplay;Lcustom_classes/WidgetTotalUser;Lcustom_classes/WidgetNumberOfUsers;)V: Line 553
   * Goal 10. main.ClassUnderTest.cancelOperationDeleteItemPage()V: Line 252
   * Goal 11. main.ClassUnderTest.closeEditLinkAddEditLinkContainerPage()V: Line 2629
   * Goal 12. main.ClassUnderTest.deleteUserOrFeedWidgetDashboardContainerPage(Lcustom_classes/Id;)V: Line 603
   * Goal 13. main.ClassUnderTest.editUserWidgetDashboardContainerPage(Lcustom_classes/Id;Lcustom_classes/WidgetUserType;Lcustom_classes/WidgetUserDisplay;Lcustom_classes/WidgetTotalUser;Lcustom_classes/WidgetNumberOfUsers;)V: Line 696
   * Goal 14. main.ClassUnderTest.goToDashboardAddEditLinkContainerPage()V: Line 2642
   * Goal 15. main.ClassUnderTest.goToDashboardDashboardContainerPage()V: Line 713
   * Goal 16. main.ClassUnderTest.goToEditCurrentUserWidgetsContainerPage()V: Line 2955
   * Goal 17. main.ClassUnderTest.goToMetaAddEditPageContainerPage()V: Line 2268
   * Goal 18. main.ClassUnderTest.goToPermissionsAddEditUserContainerPage()V: Line 1346
   * Goal 19. main.ClassUnderTest.goToPermissionsUserListContainerPage()V: Line 932
   * Goal 20. main.ClassUnderTest.goToRolesUserListContainerPage()V: Line 945
   * Goal 21. main.ClassUnderTest.goToSiteAddEditUserContainerPage()V: Line 1385
   * Goal 22. main.ClassUnderTest.goToSitePagesContainerPage()V: Line 1958
   * Goal 23. main.ClassUnderTest.goToSiteUserListContainerPage()V: Line 971
   * Goal 24. main.ClassUnderTest.goToSiteWidgetsContainerPage()V: Line 3000
   * Goal 25. main.ClassUnderTest.goToUserListPermissionsContainerPage()V: Line 1523
   * Goal 26. main.ClassUnderTest.goToUserListUserListContainerPage()V: Line 983
   * Goal 27. main.ClassUnderTest.goToUsersDashboardContainerPage()V: Line 775
   * Goal 28. main.ClassUnderTest.goToUsersPermissionsContainerPage()V: Line 1535
   * Goal 29. main.ClassUnderTest.goToUsersUserListContainerPage()V: Line 995
   * Goal 30. main.ClassUnderTest.goToWidgetsAddEditMenuWidgetContainerPage()V: Line 3579
   * Goal 31. main.ClassUnderTest.goToWidgetsAddEditPageContainerPage()V: Line 2317
   * Goal 32. main.ClassUnderTest.goToWidgetsPagesContainerPage()V: Line 1982
   * Goal 33. main.ClassUnderTest.moveLinkOrPageToMenuPagesContainerPage(Lcustom_classes/SiteLinkOrPage;Lcustom_classes/SiteMenus;)V: Line 2025
   * Goal 34. main.ClassUnderTest.unpublishLinkOrPagePagesContainerPage(Lcustom_classes/SiteLinkOrPage;)V: Line 2113
   */

  @Test(timeout = 1001000)
  public void test01()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      WidgetUserType widgetUserType0 = WidgetUserType.LOGGEDIN;
      WidgetUserDisplay widgetUserDisplay0 = WidgetUserDisplay.THUMBNAIL;
      WidgetTotalUser widgetTotalUser0 = WidgetTotalUser.HIDE;
      WidgetNumberOfUsers widgetNumberOfUsers0 = WidgetNumberOfUsers.TWENTYFOUR;
      classUnderTest0.addUserWidgetDashboardContainerPage(widgetUserType0, widgetUserDisplay0, widgetTotalUser0, widgetNumberOfUsers0);
      classUnderTest0.goToDashboardDashboardContainerPage();
      int int0 = 2490;
      Id id0 = new Id(int0);
      WidgetUserType widgetUserType1 = WidgetUserType.LOGGEDIN;
      classUnderTest0.editUserWidgetDashboardContainerPage(id0, widgetUserType1, widgetUserDisplay0, widgetTotalUser0, widgetNumberOfUsers0);
      WidgetTotalUser widgetTotalUser1 = WidgetTotalUser.HIDE;
      classUnderTest0.editUserWidgetDashboardContainerPage(id0, widgetUserType1, widgetUserDisplay0, widgetTotalUser1, widgetNumberOfUsers0);
      WidgetFeedNumberOfPosts widgetFeedNumberOfPosts0 = new WidgetFeedNumberOfPosts(int0);
      WidgetFeedPostContent widgetFeedPostContent0 = WidgetFeedPostContent.DONTSHOW;
      WidgetUserDisplay widgetUserDisplay1 = WidgetUserDisplay.THUMBNAIL;
      WidgetTotalUser widgetTotalUser2 = WidgetTotalUser.HIDE;
      classUnderTest0.addUserWidgetDashboardContainerPage(widgetUserType0, widgetUserDisplay1, widgetTotalUser2, widgetNumberOfUsers0);
      WidgetFeedTitle widgetFeedTitle0 = WidgetFeedTitle.PAGEKITNEWS;
      WidgetFeedUrl widgetFeedUrl0 = WidgetFeedUrl.SPORT;
      classUnderTest0.addFeedWidgetDashboardContainerPage(widgetFeedTitle0, widgetFeedUrl0, widgetFeedNumberOfPosts0, widgetFeedPostContent0);
      classUnderTest0.goToUsersDashboardContainerPage();
      classUnderTest0.goToPermissionsUserListContainerPage();
      classUnderTest0.goToUsersPermissionsContainerPage();
      classUnderTest0.goToUsersUserListContainerPage();
      classUnderTest0.goToSiteUserListContainerPage();
      classUnderTest0.goToWidgetsPagesContainerPage();
      classUnderTest0.addMenuWidgetsContainerPage();
      classUnderTest0.goToWidgetsAddEditMenuWidgetContainerPage();
      classUnderTest0.goToEditCurrentUserWidgetsContainerPage();
      classUnderTest0.goToPermissionsAddEditUserContainerPage();
      classUnderTest0.goToUserListPermissionsContainerPage();
      classUnderTest0.goToUserListUserListContainerPage();
      classUnderTest0.goToRolesUserListContainerPage();
      classUnderTest0.goToUsersPermissionsContainerPage();
      classUnderTest0.addUserUserListContainerPage();
      classUnderTest0.goToSiteAddEditUserContainerPage();
      classUnderTest0.addPagePagesContainerPage();
      SitePages sitePages0 = SitePages.HOME;
      HTMLSnippets hTMLSnippets0 = HTMLSnippets.IMAGE_TITLE;
      PageLinkStatus pageLinkStatus0 = PageLinkStatus.ENABLED;
      HideInMenu hideInMenu0 = HideInMenu.YES;
      classUnderTest0.addEditPageAddEditPageContainerPage(sitePages0, hTMLSnippets0, pageLinkStatus0, hideInMenu0);
      classUnderTest0.goToMetaAddEditPageContainerPage();
      classUnderTest0.goToWidgetsAddEditPageContainerPage();
      classUnderTest0.goToSiteWidgetsContainerPage();
      classUnderTest0.goToSitePagesContainerPage();
      SiteMenus siteMenus0 = SiteMenus.SIDE_MENU;
      classUnderTest0.addMenuPagesContainerPage(siteMenus0);
      classUnderTest0.addItemAddEditItemPage();
      classUnderTest0.unpublishLinkOrPagePagesContainerPage(sitePages0);
      classUnderTest0.addLinkPagesContainerPage();
      classUnderTest0.closeEditLinkAddEditLinkContainerPage();
      SiteMenus siteMenus1 = SiteMenus.NOT_LINKED;
      classUnderTest0.moveLinkOrPageToMenuPagesContainerPage(sitePages0, siteMenus1);
      classUnderTest0.addLinkPagesContainerPage();
      classUnderTest0.goToDashboardAddEditLinkContainerPage();
      classUnderTest0.deleteUserOrFeedWidgetDashboardContainerPage(id0);
      classUnderTest0.cancelOperationDeleteItemPage();
  }

  //Test case number: 2
  /*
   * 17 covered goals:
   * Goal 1. main.ClassUnderTest.addEditTextWidgetAddEditTextWidgetContainerPage(Lcustom_classes/WidgetTextTitles;Lcustom_classes/HTMLSnippets;Lcustom_classes/PageLinkStatus;)V: Line 2338
   * Goal 2. main.ClassUnderTest.addFeedWidgetDashboardContainerPage(Lcustom_classes/WidgetFeedTitle;Lcustom_classes/WidgetFeedUrl;Lcustom_classes/WidgetFeedNumberOfPosts;Lcustom_classes/WidgetFeedPostContent;)V: Line 515
   * Goal 3. main.ClassUnderTest.addMenuWidgetsContainerPage()V: Line 2772
   * Goal 4. main.ClassUnderTest.addTextWidgetsContainerPage()V: Line 2786
   * Goal 5. main.ClassUnderTest.addUserWidgetDashboardContainerPage(Lcustom_classes/WidgetUserType;Lcustom_classes/WidgetUserDisplay;Lcustom_classes/WidgetTotalUser;Lcustom_classes/WidgetNumberOfUsers;)V: Line 553
   * Goal 6. main.ClassUnderTest.editUserWidgetDashboardContainerPage(Lcustom_classes/Id;Lcustom_classes/WidgetUserType;Lcustom_classes/WidgetUserDisplay;Lcustom_classes/WidgetTotalUser;Lcustom_classes/WidgetNumberOfUsers;)V: Line 696
   * Goal 7. main.ClassUnderTest.goToDashboardDashboardContainerPage()V: Line 713
   * Goal 8. main.ClassUnderTest.goToEditCurrentUserAddEditTextWidgetContainerPage()V: Line 2436
   * Goal 9. main.ClassUnderTest.goToEditCurrentUserAddEditUserContainerPage()V: Line 1333
   * Goal 10. main.ClassUnderTest.goToPermissionsUserListContainerPage()V: Line 932
   * Goal 11. main.ClassUnderTest.goToRolesAddEditUserContainerPage()V: Line 1359
   * Goal 12. main.ClassUnderTest.goToSiteUserListContainerPage()V: Line 971
   * Goal 13. main.ClassUnderTest.goToUsersDashboardContainerPage()V: Line 775
   * Goal 14. main.ClassUnderTest.goToUsersPermissionsContainerPage()V: Line 1535
   * Goal 15. main.ClassUnderTest.goToUsersUserListContainerPage()V: Line 995
   * Goal 16. main.ClassUnderTest.goToWidgetsAddEditMenuWidgetContainerPage()V: Line 3579
   * Goal 17. main.ClassUnderTest.goToWidgetsPagesContainerPage()V: Line 1982
   */

  @Test(timeout = 1001000)
  public void test02()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      WidgetUserType widgetUserType0 = WidgetUserType.LOGGEDIN;
      WidgetUserDisplay widgetUserDisplay0 = WidgetUserDisplay.THUMBNAIL;
      WidgetTotalUser widgetTotalUser0 = WidgetTotalUser.HIDE;
      WidgetNumberOfUsers widgetNumberOfUsers0 = WidgetNumberOfUsers.TWENTYFOUR;
      classUnderTest0.addUserWidgetDashboardContainerPage(widgetUserType0, widgetUserDisplay0, widgetTotalUser0, widgetNumberOfUsers0);
      classUnderTest0.goToDashboardDashboardContainerPage();
      int int0 = 2490;
      Id id0 = new Id(int0);
      WidgetUserType widgetUserType1 = WidgetUserType.LOGGEDIN;
      classUnderTest0.editUserWidgetDashboardContainerPage(id0, widgetUserType1, widgetUserDisplay0, widgetTotalUser0, widgetNumberOfUsers0);
      WidgetTotalUser widgetTotalUser1 = WidgetTotalUser.HIDE;
      classUnderTest0.editUserWidgetDashboardContainerPage(id0, widgetUserType1, widgetUserDisplay0, widgetTotalUser1, widgetNumberOfUsers0);
      WidgetFeedNumberOfPosts widgetFeedNumberOfPosts0 = new WidgetFeedNumberOfPosts(int0);
      WidgetFeedPostContent widgetFeedPostContent0 = WidgetFeedPostContent.SHOWALLPOSTS;
      WidgetUserDisplay widgetUserDisplay1 = WidgetUserDisplay.THUMBNAIL;
      WidgetTotalUser widgetTotalUser2 = WidgetTotalUser.HIDE;
      classUnderTest0.addUserWidgetDashboardContainerPage(widgetUserType0, widgetUserDisplay1, widgetTotalUser2, widgetNumberOfUsers0);
      WidgetFeedTitle widgetFeedTitle0 = WidgetFeedTitle.PAGEKITNEWS;
      WidgetFeedUrl widgetFeedUrl0 = WidgetFeedUrl.SPORT;
      classUnderTest0.addFeedWidgetDashboardContainerPage(widgetFeedTitle0, widgetFeedUrl0, widgetFeedNumberOfPosts0, widgetFeedPostContent0);
      classUnderTest0.goToUsersDashboardContainerPage();
      classUnderTest0.goToPermissionsUserListContainerPage();
      classUnderTest0.goToUsersPermissionsContainerPage();
      classUnderTest0.goToUsersUserListContainerPage();
      classUnderTest0.goToSiteUserListContainerPage();
      classUnderTest0.goToWidgetsPagesContainerPage();
      classUnderTest0.addMenuWidgetsContainerPage();
      classUnderTest0.goToWidgetsAddEditMenuWidgetContainerPage();
      classUnderTest0.addTextWidgetsContainerPage();
      WidgetTextTitles widgetTextTitles0 = WidgetTextTitles.POWERED_COPY;
      HTMLSnippets hTMLSnippets0 = HTMLSnippets.IMAGE_TITLE_PRICE;
      PageLinkStatus pageLinkStatus0 = PageLinkStatus.DISABLED;
      classUnderTest0.addEditTextWidgetAddEditTextWidgetContainerPage(widgetTextTitles0, hTMLSnippets0, pageLinkStatus0);
      WidgetTextTitles widgetTextTitles1 = WidgetTextTitles.POWERED;
      HTMLSnippets hTMLSnippets1 = HTMLSnippets.HOME;
      PageLinkStatus pageLinkStatus1 = PageLinkStatus.ENABLED;
      classUnderTest0.addEditTextWidgetAddEditTextWidgetContainerPage(widgetTextTitles1, hTMLSnippets1, pageLinkStatus1);
      classUnderTest0.goToEditCurrentUserAddEditTextWidgetContainerPage();
      classUnderTest0.goToEditCurrentUserAddEditUserContainerPage();
      classUnderTest0.goToRolesAddEditUserContainerPage();
  }

  //Test case number: 3
  /*
   * 16 covered goals:
   * Goal 1. main.ClassUnderTest.addEditTextWidgetRestrictAccessAddEditTextWidgetContainerPage(Lcustom_classes/WidgetTextTitles;Lcustom_classes/HTMLSnippets;Lcustom_classes/PageLinkStatus;Lcustom_classes/UserRoles;)V: Line 2368
   * Goal 2. main.ClassUnderTest.addFeedWidgetDashboardContainerPage(Lcustom_classes/WidgetFeedTitle;Lcustom_classes/WidgetFeedUrl;Lcustom_classes/WidgetFeedNumberOfPosts;Lcustom_classes/WidgetFeedPostContent;)V: Line 515
   * Goal 3. main.ClassUnderTest.addTextWidgetsContainerPage()V: Line 2786
   * Goal 4. main.ClassUnderTest.goToDashboardDashboardContainerPage()V: Line 713
   * Goal 5. main.ClassUnderTest.goToDashboardPagesContainerPage()V: Line 1901
   * Goal 6. main.ClassUnderTest.goToEditCurrentUserDashboardContainerPage()V: Line 726
   * Goal 7. main.ClassUnderTest.goToMenuPagesContainerPage(Lcustom_classes/SiteMenus;)V: Line 1929
   * Goal 8. main.ClassUnderTest.goToPagesPagesContainerPage()V: Line 1946
   * Goal 9. main.ClassUnderTest.goToSettingsUserListContainerPage()V: Line 958
   * Goal 10. main.ClassUnderTest.goToSiteAddEditUserContainerPage()V: Line 1385
   * Goal 11. main.ClassUnderTest.goToSiteDashboardContainerPage()V: Line 763
   * Goal 12. main.ClassUnderTest.goToSitePagesContainerPage()V: Line 1958
   * Goal 13. main.ClassUnderTest.goToSiteUserListContainerPage()V: Line 971
   * Goal 14. main.ClassUnderTest.goToUserListUserSettingsContainerPage()V: Line 1640
   * Goal 15. main.ClassUnderTest.goToUsersWidgetsContainerPage()V: Line 3012
   * Goal 16. main.ClassUnderTest.goToWidgetsPagesContainerPage()V: Line 1982
   */

  @Test(timeout = 1001000)
  public void test03()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      classUnderTest0.goToDashboardDashboardContainerPage();
      classUnderTest0.goToEditCurrentUserDashboardContainerPage();
      classUnderTest0.goToSiteAddEditUserContainerPage();
      classUnderTest0.goToPagesPagesContainerPage();
      SiteMenus siteMenus0 = SiteMenus.NOT_LINKED;
      classUnderTest0.goToWidgetsPagesContainerPage();
      classUnderTest0.goToUsersWidgetsContainerPage();
      classUnderTest0.goToSettingsUserListContainerPage();
      classUnderTest0.goToUserListUserSettingsContainerPage();
      classUnderTest0.goToSiteUserListContainerPage();
      classUnderTest0.goToMenuPagesContainerPage(siteMenus0);
      classUnderTest0.goToSitePagesContainerPage();
      classUnderTest0.goToDashboardPagesContainerPage();
      classUnderTest0.goToDashboardDashboardContainerPage();
      WidgetFeedTitle widgetFeedTitle0 = WidgetFeedTitle.SPORTNEWS;
      WidgetFeedUrl widgetFeedUrl0 = WidgetFeedUrl.SPORT;
      int int0 = 1;
      WidgetFeedNumberOfPosts widgetFeedNumberOfPosts0 = new WidgetFeedNumberOfPosts(int0);
      WidgetFeedPostContent widgetFeedPostContent0 = WidgetFeedPostContent.SHOWFIRSTPOST;
      classUnderTest0.addFeedWidgetDashboardContainerPage(widgetFeedTitle0, widgetFeedUrl0, widgetFeedNumberOfPosts0, widgetFeedPostContent0);
      classUnderTest0.goToSiteDashboardContainerPage();
      classUnderTest0.goToWidgetsPagesContainerPage();
      classUnderTest0.addTextWidgetsContainerPage();
      WidgetTextTitles widgetTextTitles0 = WidgetTextTitles.POWERED;
      HTMLSnippets hTMLSnippets0 = HTMLSnippets.IMAGE_TITLE;
      PageLinkStatus pageLinkStatus0 = PageLinkStatus.ENABLED;
      UserRoles userRoles0 = UserRoles.AUTHENTICATED;
      classUnderTest0.addEditTextWidgetRestrictAccessAddEditTextWidgetContainerPage(widgetTextTitles0, hTMLSnippets0, pageLinkStatus0, userRoles0);
  }

  //Test case number: 4
  /*
   * 14 covered goals:
   * Goal 1. main.ClassUnderTest.addExistingMenuPagesContainerPage(Lcustom_classes/SiteMenus;)V: Line 1686
   * Goal 2. main.ClassUnderTest.addItemAddEditItemPage()V: Line 380
   * Goal 3. main.ClassUnderTest.addLinkPagesContainerPage()V: Line 1706
   * Goal 4. main.ClassUnderTest.addLocationWidgetDashboardContainerPage(Lcustom_classes/WidgetLocation;Lcustom_classes/WidgetUnit;)V: Line 533
   * Goal 5. main.ClassUnderTest.addMenuWidgetsContainerPage()V: Line 2772
   * Goal 6. main.ClassUnderTest.addUserWidgetDashboardContainerPage(Lcustom_classes/WidgetUserType;Lcustom_classes/WidgetUserDisplay;Lcustom_classes/WidgetTotalUser;Lcustom_classes/WidgetNumberOfUsers;)V: Line 553
   * Goal 7. main.ClassUnderTest.deleteLocationWidgetDashboardContainerPage(Lcustom_classes/Id;)V: Line 575
   * Goal 8. main.ClassUnderTest.editLocationWidgetDashboardContainerPage(Lcustom_classes/Id;Lcustom_classes/WidgetLocation;Lcustom_classes/WidgetUnit;)V: Line 664
   * Goal 9. main.ClassUnderTest.goToMetaAddEditLinkContainerPage()V: Line 2668
   * Goal 10. main.ClassUnderTest.goToPagesAddEditMenuWidgetContainerPage()V: Line 3517
   * Goal 11. main.ClassUnderTest.goToSettingsAddEditLinkContainerPage()V: Line 2693
   * Goal 12. main.ClassUnderTest.goToSiteAddEditLinkContainerPage()V: Line 2706
   * Goal 13. main.ClassUnderTest.goToSiteDashboardContainerPage()V: Line 763
   * Goal 14. main.ClassUnderTest.goToWidgetsPagesContainerPage()V: Line 1982
   */

  @Test(timeout = 1001000)
  public void test04()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      int int0 = 1832;
      Id id0 = new Id(int0);
      WidgetLocation widgetLocation0 = WidgetLocation.GENOA;
      WidgetUnit widgetUnit0 = WidgetUnit.IMPERIAL;
      WidgetUserType widgetUserType0 = WidgetUserType.LASTREGISTERED;
      WidgetUserDisplay widgetUserDisplay0 = WidgetUserDisplay.THUMBNAIL;
      WidgetTotalUser widgetTotalUser0 = WidgetTotalUser.HIDE;
      WidgetNumberOfUsers widgetNumberOfUsers0 = WidgetNumberOfUsers.EIGHTEEN;
      classUnderTest0.addUserWidgetDashboardContainerPage(widgetUserType0, widgetUserDisplay0, widgetTotalUser0, widgetNumberOfUsers0);
      classUnderTest0.editLocationWidgetDashboardContainerPage(id0, widgetLocation0, widgetUnit0);
      WidgetLocation widgetLocation1 = WidgetLocation.GENOA;
      classUnderTest0.addLocationWidgetDashboardContainerPage(widgetLocation1, widgetUnit0);
      classUnderTest0.deleteLocationWidgetDashboardContainerPage(id0);
      classUnderTest0.goToSiteDashboardContainerPage();
      SiteMenus siteMenus0 = SiteMenus.MAIN;
      classUnderTest0.addExistingMenuPagesContainerPage(siteMenus0);
      classUnderTest0.addItemAddEditItemPage();
      classUnderTest0.addLinkPagesContainerPage();
      classUnderTest0.goToSettingsAddEditLinkContainerPage();
      classUnderTest0.goToMetaAddEditLinkContainerPage();
      classUnderTest0.goToSiteAddEditLinkContainerPage();
      classUnderTest0.goToWidgetsPagesContainerPage();
      classUnderTest0.addMenuWidgetsContainerPage();
      classUnderTest0.goToPagesAddEditMenuWidgetContainerPage();
  }

  //Test case number: 5
  /*
   * 12 covered goals:
   * Goal 1. main.ClassUnderTest.addMenuWidgetsContainerPage()V: Line 2772
   * Goal 2. main.ClassUnderTest.addPagePagesContainerPage()V: Line 1747
   * Goal 3. main.ClassUnderTest.addUserAddEditUserContainerPage(Lcustom_classes/Username;Lcustom_classes/Name;Lcustom_classes/Email;Lcustom_classes/UserPassword;Lcustom_classes/UserStatus;)V: Line 1263
   * Goal 4. main.ClassUnderTest.addUserUserListContainerPage()V: Line 812
   * Goal 5. main.ClassUnderTest.deleteLocationWidgetDashboardContainerPage(Lcustom_classes/Id;)V: Line 575
   * Goal 6. main.ClassUnderTest.goToDashboardAddEditUserContainerPage()V: Line 1320
   * Goal 7. main.ClassUnderTest.goToDashboardDashboardContainerPage()V: Line 713
   * Goal 8. main.ClassUnderTest.goToDashboardPagesContainerPage()V: Line 1901
   * Goal 9. main.ClassUnderTest.goToEditCurrentUserAddEditMenuWidgetContainerPage()V: Line 3504
   * Goal 10. main.ClassUnderTest.goToSiteDashboardContainerPage()V: Line 763
   * Goal 11. main.ClassUnderTest.goToUsersDashboardContainerPage()V: Line 775
   * Goal 12. main.ClassUnderTest.goToWidgetsAddEditPageContainerPage()V: Line 2317
   */

  @Test(timeout = 1001000)
  public void test05()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      int int0 = 1768;
      Id id0 = new Id(int0);
      classUnderTest0.deleteLocationWidgetDashboardContainerPage(id0);
      classUnderTest0.goToSiteDashboardContainerPage();
      classUnderTest0.goToDashboardPagesContainerPage();
      classUnderTest0.goToDashboardDashboardContainerPage();
      classUnderTest0.goToDashboardDashboardContainerPage();
      classUnderTest0.goToUsersDashboardContainerPage();
      classUnderTest0.addUserUserListContainerPage();
      Username username0 = Username.ADMIN;
      Name name0 = Name.JOHN;
      Email email0 = Email.ASD;
      UserPassword userPassword0 = UserPassword.FOO;
      UserStatus userStatus0 = UserStatus.BLOCKED;
      classUnderTest0.addUserAddEditUserContainerPage(username0, name0, email0, userPassword0, userStatus0);
      classUnderTest0.goToDashboardAddEditUserContainerPage();
      classUnderTest0.goToSiteDashboardContainerPage();
      classUnderTest0.addPagePagesContainerPage();
      classUnderTest0.goToWidgetsAddEditPageContainerPage();
      classUnderTest0.addMenuWidgetsContainerPage();
      classUnderTest0.goToEditCurrentUserAddEditMenuWidgetContainerPage();
  }

  //Test case number: 6
  /*
   * 21 covered goals:
   * Goal 1. main.ClassUnderTest.addLinkPagesContainerPage()V: Line 1706
   * Goal 2. main.ClassUnderTest.addUserUserListContainerPage()V: Line 812
   * Goal 3. main.ClassUnderTest.addUserWidgetDashboardContainerPage(Lcustom_classes/WidgetUserType;Lcustom_classes/WidgetUserDisplay;Lcustom_classes/WidgetTotalUser;Lcustom_classes/WidgetNumberOfUsers;)V: Line 553
   * Goal 4. main.ClassUnderTest.blockUserUserListContainerPage(Lcustom_classes/Id;)V: Line 834
   * Goal 5. main.ClassUnderTest.cancelOperationDeleteItemPage()V: Line 257
   * Goal 6. main.ClassUnderTest.confirmOperationDeleteItemPage()V: Line 289
   * Goal 7. main.ClassUnderTest.deleteUserOrFeedWidgetDashboardContainerPage(Lcustom_classes/Id;)V: Line 603
   * Goal 8. main.ClassUnderTest.deleteUserUserListContainerPage(Lcustom_classes/Id;)V: Line 889
   * Goal 9. main.ClassUnderTest.editUserWidgetDashboardContainerPage(Lcustom_classes/Id;Lcustom_classes/WidgetUserType;Lcustom_classes/WidgetUserDisplay;Lcustom_classes/WidgetTotalUser;Lcustom_classes/WidgetNumberOfUsers;)V: Line 696
   * Goal 10. main.ClassUnderTest.goToDashboardAddEditLinkContainerPage()V: Line 2642
   * Goal 11. main.ClassUnderTest.goToDashboardDashboardContainerPage()V: Line 713
   * Goal 12. main.ClassUnderTest.goToDashboardUserListContainerPage()V: Line 906
   * Goal 13. main.ClassUnderTest.goToEditCurrentUserDashboardContainerPage()V: Line 726
   * Goal 14. main.ClassUnderTest.goToPermissionsAddEditUserContainerPage()V: Line 1346
   * Goal 15. main.ClassUnderTest.goToRolesPermissionsContainerPage()V: Line 1485
   * Goal 16. main.ClassUnderTest.goToRolesUserListContainerPage()V: Line 945
   * Goal 17. main.ClassUnderTest.goToSiteUserListContainerPage()V: Line 971
   * Goal 18. main.ClassUnderTest.goToUserListAddEditUserContainerPage()V: Line 1397
   * Goal 19. main.ClassUnderTest.goToUserListPermissionsContainerPage()V: Line 1523
   * Goal 20. main.ClassUnderTest.goToUsersDashboardContainerPage()V: Line 775
   * Goal 21. main.ClassUnderTest.goToUsersUserListContainerPage()V: Line 995
   */

  @Test(timeout = 1001000)
  public void test06()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      WidgetUserType widgetUserType0 = WidgetUserType.LOGGEDIN;
      WidgetUserDisplay widgetUserDisplay0 = WidgetUserDisplay.LIST;
      WidgetTotalUser widgetTotalUser0 = WidgetTotalUser.HIDE;
      WidgetNumberOfUsers widgetNumberOfUsers0 = WidgetNumberOfUsers.TWELVE;
      classUnderTest0.addUserWidgetDashboardContainerPage(widgetUserType0, widgetUserDisplay0, widgetTotalUser0, widgetNumberOfUsers0);
      classUnderTest0.goToDashboardDashboardContainerPage();
      int int0 = (-631);
      Id id0 = new Id(int0);
      Id id1 = new Id(id0.value);
      WidgetTotalUser widgetTotalUser1 = WidgetTotalUser.HIDE;
      classUnderTest0.editUserWidgetDashboardContainerPage(id1, widgetUserType0, widgetUserDisplay0, widgetTotalUser1, widgetNumberOfUsers0);
      classUnderTest0.deleteUserOrFeedWidgetDashboardContainerPage(id1);
      classUnderTest0.confirmOperationDeleteItemPage();
      classUnderTest0.goToUsersDashboardContainerPage();
      classUnderTest0.addUserUserListContainerPage();
      classUnderTest0.goToUserListAddEditUserContainerPage();
      classUnderTest0.goToDashboardUserListContainerPage();
      classUnderTest0.goToEditCurrentUserDashboardContainerPage();
      classUnderTest0.goToPermissionsAddEditUserContainerPage();
      classUnderTest0.goToUserListPermissionsContainerPage();
      classUnderTest0.deleteUserUserListContainerPage(id1);
      classUnderTest0.cancelOperationDeleteItemPage();
      classUnderTest0.goToUsersUserListContainerPage();
      classUnderTest0.blockUserUserListContainerPage(id1);
      classUnderTest0.goToSiteUserListContainerPage();
      classUnderTest0.addLinkPagesContainerPage();
      classUnderTest0.goToDashboardAddEditLinkContainerPage();
      classUnderTest0.goToDashboardDashboardContainerPage();
      classUnderTest0.goToDashboardDashboardContainerPage();
      WidgetUserType widgetUserType1 = WidgetUserType.LOGGEDIN;
      WidgetUserDisplay widgetUserDisplay1 = WidgetUserDisplay.THUMBNAIL;
      WidgetNumberOfUsers widgetNumberOfUsers1 = WidgetNumberOfUsers.EIGHTEEN;
      classUnderTest0.editUserWidgetDashboardContainerPage(id1, widgetUserType1, widgetUserDisplay1, widgetTotalUser1, widgetNumberOfUsers1);
      classUnderTest0.goToUsersDashboardContainerPage();
      classUnderTest0.goToRolesUserListContainerPage();
      classUnderTest0.goToRolesPermissionsContainerPage();
  }

  //Test case number: 7
  /*
   * 7 covered goals:
   * Goal 1. main.ClassUnderTest.cancelOperationAddEditItemPage()V: Line 426
   * Goal 2. main.ClassUnderTest.editMenuPagesContainerPage(Lcustom_classes/SiteMenus;Lcustom_classes/SiteMenus;)V: Line 1833
   * Goal 3. main.ClassUnderTest.goToDashboardPagesContainerPage()V: Line 1901
   * Goal 4. main.ClassUnderTest.goToEditCurrentUserDashboardContainerPage()V: Line 726
   * Goal 5. main.ClassUnderTest.goToSiteAddEditUserContainerPage()V: Line 1385
   * Goal 6. main.ClassUnderTest.goToSiteDashboardContainerPage()V: Line 763
   * Goal 7. main.ClassUnderTest.moveAllPagesAndLinksToMenuPagesContainerPage(Lcustom_classes/SiteMenus;)V: Line 2000
   */

  @Test(timeout = 1001000)
  public void test07()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      classUnderTest0.goToSiteDashboardContainerPage();
      SiteMenus siteMenus0 = SiteMenus.NOT_LINKED;
      classUnderTest0.goToDashboardPagesContainerPage();
      classUnderTest0.goToEditCurrentUserDashboardContainerPage();
      classUnderTest0.goToSiteAddEditUserContainerPage();
      classUnderTest0.moveAllPagesAndLinksToMenuPagesContainerPage(siteMenus0);
      SiteMenus siteMenus1 = SiteMenus.MAIN;
      SiteMenus siteMenus2 = SiteMenus.SIDE_MENU;
      classUnderTest0.editMenuPagesContainerPage(siteMenus1, siteMenus2);
      classUnderTest0.cancelOperationAddEditItemPage();
  }

  //Test case number: 8
  /*
   * 4 covered goals:
   * Goal 1. main.ClassUnderTest.cancelOperationSelectLinkPage()V: Line 30
   * Goal 2. main.ClassUnderTest.changeSettingsUserSettingsContainerPage(Lcustom_classes/RegistrationUserSettings;)V: Line 1550
   * Goal 3. main.ClassUnderTest.goToSettingsUserListContainerPage()V: Line 958
   * Goal 4. main.ClassUnderTest.goToUsersDashboardContainerPage()V: Line 775
   */

  @Test(timeout = 1001000)
  public void test08()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      classUnderTest0.goToUsersDashboardContainerPage();
      classUnderTest0.goToSettingsUserListContainerPage();
      RegistrationUserSettings registrationUserSettings0 = RegistrationUserSettings.ENABLED_BUT_APPROVAL;
      classUnderTest0.changeSettingsUserSettingsContainerPage(registrationUserSettings0);
      classUnderTest0.cancelOperationSelectLinkPage();
  }

  //Test case number: 9
  /*
   * 15 covered goals:
   * Goal 1. main.ClassUnderTest.addLinkPagesContainerPage()V: Line 1706
   * Goal 2. main.ClassUnderTest.addLoginWidgetsContainerPage()V: Line 2758
   * Goal 3. main.ClassUnderTest.closeEditLoginAddEditLoginWidgetContainerPage()V: Line 3201
   * Goal 4. main.ClassUnderTest.deleteAllPagesAndLinksPagesContainerPage()V: Line 1767
   * Goal 5. main.ClassUnderTest.editLocationWidgetDashboardContainerPage(Lcustom_classes/Id;Lcustom_classes/WidgetLocation;Lcustom_classes/WidgetUnit;)V: Line 664
   * Goal 6. main.ClassUnderTest.goToDashboardDashboardContainerPage()V: Line 713
   * Goal 7. main.ClassUnderTest.goToDashboardWidgetsContainerPage()V: Line 2942
   * Goal 8. main.ClassUnderTest.goToMenuWidgetsContainerPage(Lcustom_classes/WidgetMenus;)V: Line 2971
   * Goal 9. main.ClassUnderTest.goToRolesUserListContainerPage()V: Line 945
   * Goal 10. main.ClassUnderTest.goToSiteDashboardContainerPage()V: Line 763
   * Goal 11. main.ClassUnderTest.goToSiteWidgetsContainerPage()V: Line 3000
   * Goal 12. main.ClassUnderTest.goToUserListUserListContainerPage()V: Line 983
   * Goal 13. main.ClassUnderTest.goToUsersPagesContainerPage()V: Line 1970
   * Goal 14. main.ClassUnderTest.goToWidgetsAddEditLinkContainerPage()V: Line 2730
   * Goal 15. main.ClassUnderTest.goToWidgetsPagesContainerPage()V: Line 1982
   */

  @Test(timeout = 1001000)
  public void test09()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      int int0 = 166;
      Id id0 = new Id(int0);
      WidgetLocation widgetLocation0 = WidgetLocation.GENOA;
      WidgetUnit widgetUnit0 = WidgetUnit.METRIC;
      classUnderTest0.editLocationWidgetDashboardContainerPage(id0, widgetLocation0, widgetUnit0);
      classUnderTest0.goToDashboardDashboardContainerPage();
      classUnderTest0.goToSiteDashboardContainerPage();
      classUnderTest0.deleteAllPagesAndLinksPagesContainerPage();
      classUnderTest0.goToWidgetsPagesContainerPage();
      classUnderTest0.addLoginWidgetsContainerPage();
      classUnderTest0.closeEditLoginAddEditLoginWidgetContainerPage();
      WidgetMenus widgetMenus0 = WidgetMenus.ALL;
      classUnderTest0.goToMenuWidgetsContainerPage(widgetMenus0);
      classUnderTest0.goToDashboardWidgetsContainerPage();
      classUnderTest0.goToSiteDashboardContainerPage();
      classUnderTest0.addLinkPagesContainerPage();
      classUnderTest0.goToWidgetsAddEditLinkContainerPage();
      classUnderTest0.goToSiteWidgetsContainerPage();
      classUnderTest0.goToUsersPagesContainerPage();
      classUnderTest0.goToUserListUserListContainerPage();
      classUnderTest0.goToRolesUserListContainerPage();
  }

  //Test case number: 10
  /*
   * 8 covered goals:
   * Goal 1. main.ClassUnderTest.addPagePagesContainerPage()V: Line 1747
   * Goal 2. main.ClassUnderTest.closeEditPageAddEditPageContainerPage()V: Line 2216
   * Goal 3. main.ClassUnderTest.goToDashboardDashboardContainerPage()V: Line 713
   * Goal 4. main.ClassUnderTest.goToDashboardUserSettingsContainerPage()V: Line 1563
   * Goal 5. main.ClassUnderTest.goToEditUserDashboardContainerPage(Lcustom_classes/Id;)V: Line 746
   * Goal 6. main.ClassUnderTest.goToRolesAddEditUserContainerPage()V: Line 1359
   * Goal 7. main.ClassUnderTest.goToSettingsPermissionsContainerPage()V: Line 1498
   * Goal 8. main.ClassUnderTest.goToSiteDashboardContainerPage()V: Line 763
   */

  @Test(timeout = 1001000)
  public void test10()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      int int0 = (-141);
      Id id0 = new Id(int0);
      classUnderTest0.goToEditUserDashboardContainerPage(id0);
      classUnderTest0.goToRolesAddEditUserContainerPage();
      classUnderTest0.goToSettingsPermissionsContainerPage();
      classUnderTest0.goToDashboardUserSettingsContainerPage();
      classUnderTest0.goToDashboardDashboardContainerPage();
      classUnderTest0.goToSiteDashboardContainerPage();
      classUnderTest0.addPagePagesContainerPage();
      classUnderTest0.closeEditPageAddEditPageContainerPage();
  }

  //Test case number: 11
  /*
   * 10 covered goals:
   * Goal 1. main.ClassUnderTest.addFeedWidgetDashboardContainerPage(Lcustom_classes/WidgetFeedTitle;Lcustom_classes/WidgetFeedUrl;Lcustom_classes/WidgetFeedNumberOfPosts;Lcustom_classes/WidgetFeedPostContent;)V: Line 515
   * Goal 2. main.ClassUnderTest.addLinkPagesContainerPage()V: Line 1706
   * Goal 3. main.ClassUnderTest.closeOperationAddEditUserContainerPage()V: Line 1285
   * Goal 4. main.ClassUnderTest.goToEditCurrentUserAddEditLinkContainerPage()V: Line 2655
   * Goal 5. main.ClassUnderTest.goToEditCurrentUserDashboardContainerPage()V: Line 726
   * Goal 6. main.ClassUnderTest.goToPermissionsPermissionsContainerPage()V: Line 1472
   * Goal 7. main.ClassUnderTest.goToRolesUserListContainerPage()V: Line 945
   * Goal 8. main.ClassUnderTest.goToSitePagesContainerPage()V: Line 1958
   * Goal 9. main.ClassUnderTest.goToSitePermissionsContainerPage()V: Line 1511
   * Goal 10. main.ClassUnderTest.publishAllPagesAndLinksPagesContainerPage()V: Line 2047
   */

  @Test(timeout = 1001000)
  public void test11()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      WidgetFeedTitle widgetFeedTitle0 = WidgetFeedTitle.WEATHER;
      WidgetFeedUrl widgetFeedUrl0 = WidgetFeedUrl.WEATHER;
      int int0 = (-1232);
      WidgetFeedNumberOfPosts widgetFeedNumberOfPosts0 = new WidgetFeedNumberOfPosts(int0);
      WidgetFeedPostContent widgetFeedPostContent0 = WidgetFeedPostContent.SHOWALLPOSTS;
      classUnderTest0.addFeedWidgetDashboardContainerPage(widgetFeedTitle0, widgetFeedUrl0, widgetFeedNumberOfPosts0, widgetFeedPostContent0);
      classUnderTest0.goToEditCurrentUserDashboardContainerPage();
      classUnderTest0.closeOperationAddEditUserContainerPage();
      classUnderTest0.goToRolesUserListContainerPage();
      classUnderTest0.goToPermissionsPermissionsContainerPage();
      classUnderTest0.goToSitePermissionsContainerPage();
      classUnderTest0.goToSitePagesContainerPage();
      classUnderTest0.publishAllPagesAndLinksPagesContainerPage();
      classUnderTest0.addLinkPagesContainerPage();
      classUnderTest0.goToEditCurrentUserAddEditLinkContainerPage();
  }

  //Test case number: 12
  /*
   * 21 covered goals:
   * Goal 1. main.ClassUnderTest.addUserUserListContainerPage()V: Line 812
   * Goal 2. main.ClassUnderTest.addUserWidgetDashboardContainerPage(Lcustom_classes/WidgetUserType;Lcustom_classes/WidgetUserDisplay;Lcustom_classes/WidgetTotalUser;Lcustom_classes/WidgetNumberOfUsers;)V: Line 553
   * Goal 3. main.ClassUnderTest.deleteLinkOrPagePagesContainerPage(Lcustom_classes/SiteLinkOrPage;)V: Line 1788
   * Goal 4. main.ClassUnderTest.deleteLocationWidgetDashboardContainerPage(Lcustom_classes/Id;)V: Line 575
   * Goal 5. main.ClassUnderTest.giveOrRemoveAllPermissionsToUserRolePermissionsContainerPage(Lcustom_classes/UserRoles;)V: Line 1428
   * Goal 6. main.ClassUnderTest.goToDashboardDashboardContainerPage()V: Line 713
   * Goal 7. main.ClassUnderTest.goToDashboardUserListContainerPage()V: Line 906
   * Goal 8. main.ClassUnderTest.goToEditCurrentUserDashboardContainerPage()V: Line 726
   * Goal 9. main.ClassUnderTest.goToEditCurrentUserUserListContainerPage()V: Line 919
   * Goal 10. main.ClassUnderTest.goToEditCurrentUserWidgetsContainerPage()V: Line 2955
   * Goal 11. main.ClassUnderTest.goToPagesPagesContainerPage()V: Line 1946
   * Goal 12. main.ClassUnderTest.goToPermissionsAddEditUserContainerPage()V: Line 1346
   * Goal 13. main.ClassUnderTest.goToSiteAddEditUserContainerPage()V: Line 1385
   * Goal 14. main.ClassUnderTest.goToSiteDashboardContainerPage()V: Line 763
   * Goal 15. main.ClassUnderTest.goToSitePermissionsContainerPage()V: Line 1511
   * Goal 16. main.ClassUnderTest.goToUserListAddEditUserContainerPage()V: Line 1397
   * Goal 17. main.ClassUnderTest.goToUsersAddEditUserContainerPage()V: Line 1409
   * Goal 18. main.ClassUnderTest.goToUsersPagesContainerPage()V: Line 1970
   * Goal 19. main.ClassUnderTest.goToWidgetsPagesContainerPage()V: Line 1982
   * Goal 20. main.ClassUnderTest.publishAllPagesAndLinksPagesContainerPage()V: Line 2047
   * Goal 21. main.ClassUnderTest.unpublishAllPagesAndLinksPagesContainerPage()V: Line 2091
   */

  @Test(timeout = 1001000)
  public void test12()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      WidgetUserType widgetUserType0 = WidgetUserType.LOGGEDIN;
      WidgetUserDisplay widgetUserDisplay0 = WidgetUserDisplay.LIST;
      WidgetTotalUser widgetTotalUser0 = WidgetTotalUser.HIDE;
      WidgetNumberOfUsers widgetNumberOfUsers0 = WidgetNumberOfUsers.TWELVE;
      classUnderTest0.addUserWidgetDashboardContainerPage(widgetUserType0, widgetUserDisplay0, widgetTotalUser0, widgetNumberOfUsers0);
      classUnderTest0.goToDashboardDashboardContainerPage();
      int int0 = (-631);
      Id id0 = new Id(int0);
      classUnderTest0.deleteLocationWidgetDashboardContainerPage(id0);
      classUnderTest0.goToEditCurrentUserDashboardContainerPage();
      classUnderTest0.goToUsersAddEditUserContainerPage();
      classUnderTest0.goToEditCurrentUserUserListContainerPage();
      classUnderTest0.goToUserListAddEditUserContainerPage();
      classUnderTest0.addUserUserListContainerPage();
      classUnderTest0.goToSiteAddEditUserContainerPage();
      SitePages sitePages0 = SitePages.HOME;
      classUnderTest0.deleteLinkOrPagePagesContainerPage(sitePages0);
      classUnderTest0.publishAllPagesAndLinksPagesContainerPage();
      classUnderTest0.unpublishAllPagesAndLinksPagesContainerPage();
      classUnderTest0.goToWidgetsPagesContainerPage();
      classUnderTest0.goToEditCurrentUserWidgetsContainerPage();
      classUnderTest0.goToPermissionsAddEditUserContainerPage();
      UserRoles userRoles0 = UserRoles.AUTHENTICATED;
      classUnderTest0.giveOrRemoveAllPermissionsToUserRolePermissionsContainerPage(userRoles0);
      classUnderTest0.goToSitePermissionsContainerPage();
      classUnderTest0.publishAllPagesAndLinksPagesContainerPage();
      classUnderTest0.publishAllPagesAndLinksPagesContainerPage();
      classUnderTest0.goToUsersPagesContainerPage();
      classUnderTest0.goToDashboardUserListContainerPage();
      WidgetUserType widgetUserType1 = WidgetUserType.LASTREGISTERED;
      WidgetUserDisplay widgetUserDisplay1 = WidgetUserDisplay.LIST;
      WidgetNumberOfUsers widgetNumberOfUsers1 = WidgetNumberOfUsers.SIX;
      classUnderTest0.addUserWidgetDashboardContainerPage(widgetUserType1, widgetUserDisplay1, widgetTotalUser0, widgetNumberOfUsers1);
      classUnderTest0.goToSiteDashboardContainerPage();
      classUnderTest0.goToPagesPagesContainerPage();
  }

  //Test case number: 13
  /*
   * 10 covered goals:
   * Goal 1. main.ClassUnderTest.confirmOperationDeleteItemPage()V: Line 289
   * Goal 2. main.ClassUnderTest.deleteUserOrFeedWidgetDashboardContainerPage(Lcustom_classes/Id;)V: Line 603
   * Goal 3. main.ClassUnderTest.editFeedWidgetDashboardContainerPage(Lcustom_classes/Id;Lcustom_classes/WidgetFeedTitle;Lcustom_classes/WidgetFeedUrl;Lcustom_classes/WidgetFeedNumberOfPosts;Lcustom_classes/WidgetFeedPostContent;)V: Line 635
   * Goal 4. main.ClassUnderTest.goToDashboardDashboardContainerPage()V: Line 713
   * Goal 5. main.ClassUnderTest.goToDashboardUserSettingsContainerPage()V: Line 1563
   * Goal 6. main.ClassUnderTest.goToEditCurrentUserDashboardContainerPage()V: Line 726
   * Goal 7. main.ClassUnderTest.goToSettingsAddEditUserContainerPage()V: Line 1372
   * Goal 8. main.ClassUnderTest.goToSettingsUserListContainerPage()V: Line 958
   * Goal 9. main.ClassUnderTest.goToSiteUserSettingsContainerPage()V: Line 1628
   * Goal 10. main.ClassUnderTest.goToUsersDashboardContainerPage()V: Line 775
   */

  @Test(timeout = 1001000)
  public void test13()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      classUnderTest0.goToDashboardDashboardContainerPage();
      int int0 = 1490;
      Id id0 = new Id(int0);
      WidgetFeedTitle widgetFeedTitle0 = WidgetFeedTitle.PAGEKITNEWS;
      WidgetFeedUrl widgetFeedUrl0 = WidgetFeedUrl.WEATHER;
      int int1 = (-2896);
      WidgetFeedNumberOfPosts widgetFeedNumberOfPosts0 = new WidgetFeedNumberOfPosts(int1);
      WidgetFeedPostContent widgetFeedPostContent0 = WidgetFeedPostContent.DONTSHOW;
      classUnderTest0.editFeedWidgetDashboardContainerPage(id0, widgetFeedTitle0, widgetFeedUrl0, widgetFeedNumberOfPosts0, widgetFeedPostContent0);
      classUnderTest0.goToEditCurrentUserDashboardContainerPage();
      classUnderTest0.goToSettingsAddEditUserContainerPage();
      classUnderTest0.goToDashboardUserSettingsContainerPage();
      Id id1 = new Id(int0);
      classUnderTest0.deleteUserOrFeedWidgetDashboardContainerPage(id1);
      classUnderTest0.confirmOperationDeleteItemPage();
      classUnderTest0.goToUsersDashboardContainerPage();
      classUnderTest0.goToSettingsUserListContainerPage();
      classUnderTest0.goToSiteUserSettingsContainerPage();
  }

  //Test case number: 14
  /*
   * 14 covered goals:
   * Goal 1. main.ClassUnderTest.addPagePagesContainerPage()V: Line 1747
   * Goal 2. main.ClassUnderTest.editFeedWidgetDashboardContainerPage(Lcustom_classes/Id;Lcustom_classes/WidgetFeedTitle;Lcustom_classes/WidgetFeedUrl;Lcustom_classes/WidgetFeedNumberOfPosts;Lcustom_classes/WidgetFeedPostContent;)V: Line 635
   * Goal 3. main.ClassUnderTest.editPagePagesContainerPage(Lcustom_classes/SitePages;)V: Line 1884
   * Goal 4. main.ClassUnderTest.goToContentAddEditPageContainerPage()V: Line 2229
   * Goal 5. main.ClassUnderTest.goToDashboardDashboardContainerPage()V: Line 713
   * Goal 6. main.ClassUnderTest.goToEditCurrentUserAddEditPageContainerPage()V: Line 2255
   * Goal 7. main.ClassUnderTest.goToEditCurrentUserDashboardContainerPage()V: Line 726
   * Goal 8. main.ClassUnderTest.goToMetaAddEditPageContainerPage()V: Line 2268
   * Goal 9. main.ClassUnderTest.goToPermissionsAddEditUserContainerPage()V: Line 1346
   * Goal 10. main.ClassUnderTest.goToSiteAddEditUserContainerPage()V: Line 1385
   * Goal 11. main.ClassUnderTest.goToSiteUserListContainerPage()V: Line 971
   * Goal 12. main.ClassUnderTest.goToUserListUserListContainerPage()V: Line 983
   * Goal 13. main.ClassUnderTest.goToUsersPermissionsContainerPage()V: Line 1535
   * Goal 14. main.ClassUnderTest.goToUsersUserListContainerPage()V: Line 995
   */

  @Test(timeout = 1001000)
  public void test14()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      classUnderTest0.goToDashboardDashboardContainerPage();
      int int0 = 1490;
      Id id0 = new Id(int0);
      WidgetFeedTitle widgetFeedTitle0 = WidgetFeedTitle.PAGEKITNEWS;
      WidgetFeedUrl widgetFeedUrl0 = WidgetFeedUrl.WEATHER;
      int int1 = (-2896);
      WidgetFeedNumberOfPosts widgetFeedNumberOfPosts0 = new WidgetFeedNumberOfPosts(int1);
      WidgetFeedPostContent widgetFeedPostContent0 = WidgetFeedPostContent.DONTSHOW;
      classUnderTest0.editFeedWidgetDashboardContainerPage(id0, widgetFeedTitle0, widgetFeedUrl0, widgetFeedNumberOfPosts0, widgetFeedPostContent0);
      classUnderTest0.goToEditCurrentUserDashboardContainerPage();
      classUnderTest0.goToSiteAddEditUserContainerPage();
      SitePages sitePages0 = SitePages.HOME;
      classUnderTest0.editPagePagesContainerPage(sitePages0);
      classUnderTest0.goToMetaAddEditPageContainerPage();
      classUnderTest0.goToEditCurrentUserAddEditPageContainerPage();
      classUnderTest0.goToPermissionsAddEditUserContainerPage();
      classUnderTest0.goToUsersPermissionsContainerPage();
      classUnderTest0.goToUserListUserListContainerPage();
      classUnderTest0.goToUsersUserListContainerPage();
      classUnderTest0.goToSiteUserListContainerPage();
      classUnderTest0.addPagePagesContainerPage();
      classUnderTest0.goToContentAddEditPageContainerPage();
  }

  //Test case number: 15
  /*
   * 9 covered goals:
   * Goal 1. main.ClassUnderTest.addFeedWidgetDashboardContainerPage(Lcustom_classes/WidgetFeedTitle;Lcustom_classes/WidgetFeedUrl;Lcustom_classes/WidgetFeedNumberOfPosts;Lcustom_classes/WidgetFeedPostContent;)V: Line 515
   * Goal 2. main.ClassUnderTest.editLocationWidgetDashboardContainerPage(Lcustom_classes/Id;Lcustom_classes/WidgetLocation;Lcustom_classes/WidgetUnit;)V: Line 664
   * Goal 3. main.ClassUnderTest.editUserAddEditUserContainerPage(Lcustom_classes/Username;Lcustom_classes/Name;Lcustom_classes/Email;Lcustom_classes/UserPassword;)V: Line 1303
   * Goal 4. main.ClassUnderTest.goToEditCurrentUserPagesContainerPage()V: Line 1914
   * Goal 5. main.ClassUnderTest.goToMenuPagesContainerPage(Lcustom_classes/SiteMenus;)V: Line 1929
   * Goal 6. main.ClassUnderTest.goToSettingsUserListContainerPage()V: Line 958
   * Goal 7. main.ClassUnderTest.goToSiteDashboardContainerPage()V: Line 763
   * Goal 8. main.ClassUnderTest.goToUserListAddEditUserContainerPage()V: Line 1397
   * Goal 9. main.ClassUnderTest.goToUsersUserSettingsContainerPage()V: Line 1652
   */

  @Test(timeout = 1001000)
  public void test15()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      int int0 = (-1226);
      Id id0 = new Id(int0);
      WidgetLocation widgetLocation0 = WidgetLocation.GENOA;
      WidgetUnit widgetUnit0 = WidgetUnit.IMPERIAL;
      classUnderTest0.editLocationWidgetDashboardContainerPage(id0, widgetLocation0, widgetUnit0);
      WidgetFeedTitle widgetFeedTitle0 = WidgetFeedTitle.PAGEKITNEWS;
      WidgetFeedUrl widgetFeedUrl0 = WidgetFeedUrl.WEATHER;
      int int1 = 2231;
      WidgetFeedNumberOfPosts widgetFeedNumberOfPosts0 = new WidgetFeedNumberOfPosts(int1);
      WidgetFeedPostContent widgetFeedPostContent0 = WidgetFeedPostContent.DONTSHOW;
      classUnderTest0.addFeedWidgetDashboardContainerPage(widgetFeedTitle0, widgetFeedUrl0, widgetFeedNumberOfPosts0, widgetFeedPostContent0);
      classUnderTest0.goToSiteDashboardContainerPage();
      SiteMenus siteMenus0 = SiteMenus.NOT_LINKED;
      classUnderTest0.goToMenuPagesContainerPage(siteMenus0);
      classUnderTest0.goToEditCurrentUserPagesContainerPage();
      Username username0 = Username.FOO;
      Name name0 = Name.MARK;
      Email email0 = Email.FOO;
      UserPassword userPassword0 = UserPassword.FOO;
      classUnderTest0.editUserAddEditUserContainerPage(username0, name0, email0, userPassword0);
      classUnderTest0.goToUserListAddEditUserContainerPage();
      classUnderTest0.goToSettingsUserListContainerPage();
      classUnderTest0.goToUsersUserSettingsContainerPage();
  }

  //Test case number: 16
  /*
   * 14 covered goals:
   * Goal 1. main.ClassUnderTest.addFeedWidgetDashboardContainerPage(Lcustom_classes/WidgetFeedTitle;Lcustom_classes/WidgetFeedUrl;Lcustom_classes/WidgetFeedNumberOfPosts;Lcustom_classes/WidgetFeedPostContent;)V: Line 515
   * Goal 2. main.ClassUnderTest.addLocationWidgetDashboardContainerPage(Lcustom_classes/WidgetLocation;Lcustom_classes/WidgetUnit;)V: Line 533
   * Goal 3. main.ClassUnderTest.addLoginWidgetsContainerPage()V: Line 2758
   * Goal 4. main.ClassUnderTest.addUserWidgetDashboardContainerPage(Lcustom_classes/WidgetUserType;Lcustom_classes/WidgetUserDisplay;Lcustom_classes/WidgetTotalUser;Lcustom_classes/WidgetNumberOfUsers;)V: Line 553
   * Goal 5. main.ClassUnderTest.editFeedWidgetDashboardContainerPage(Lcustom_classes/Id;Lcustom_classes/WidgetFeedTitle;Lcustom_classes/WidgetFeedUrl;Lcustom_classes/WidgetFeedNumberOfPosts;Lcustom_classes/WidgetFeedPostContent;)V: Line 635
   * Goal 6. main.ClassUnderTest.goToDashboardAddEditLoginWidgetContainerPage()V: Line 3214
   * Goal 7. main.ClassUnderTest.goToDashboardDashboardContainerPage()V: Line 713
   * Goal 8. main.ClassUnderTest.goToEditCurrentUserDashboardContainerPage()V: Line 726
   * Goal 9. main.ClassUnderTest.goToSettingsUserListContainerPage()V: Line 958
   * Goal 10. main.ClassUnderTest.goToSiteDashboardContainerPage()V: Line 763
   * Goal 11. main.ClassUnderTest.goToSiteUserSettingsContainerPage()V: Line 1628
   * Goal 12. main.ClassUnderTest.goToUsersAddEditUserContainerPage()V: Line 1409
   * Goal 13. main.ClassUnderTest.goToWidgetsPagesContainerPage()V: Line 1982
   * Goal 14. main.ClassUnderTest.saveSettingsUserSettingsContainerPage()V: Line 1667
   */

  @Test(timeout = 1001000)
  public void test16()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      WidgetFeedTitle widgetFeedTitle0 = WidgetFeedTitle.WEATHER;
      WidgetFeedUrl widgetFeedUrl0 = WidgetFeedUrl.SPORT;
      int int0 = (-3308);
      WidgetFeedNumberOfPosts widgetFeedNumberOfPosts0 = new WidgetFeedNumberOfPosts(int0);
      WidgetFeedPostContent widgetFeedPostContent0 = WidgetFeedPostContent.SHOWALLPOSTS;
      classUnderTest0.addFeedWidgetDashboardContainerPage(widgetFeedTitle0, widgetFeedUrl0, widgetFeedNumberOfPosts0, widgetFeedPostContent0);
      WidgetFeedPostContent widgetFeedPostContent1 = WidgetFeedPostContent.SHOWFIRSTPOST;
      classUnderTest0.addFeedWidgetDashboardContainerPage(widgetFeedTitle0, widgetFeedUrl0, widgetFeedNumberOfPosts0, widgetFeedPostContent1);
      WidgetLocation widgetLocation0 = WidgetLocation.GENOA;
      WidgetUnit widgetUnit0 = WidgetUnit.IMPERIAL;
      classUnderTest0.addLocationWidgetDashboardContainerPage(widgetLocation0, widgetUnit0);
      classUnderTest0.goToSiteDashboardContainerPage();
      classUnderTest0.goToWidgetsPagesContainerPage();
      classUnderTest0.addLoginWidgetsContainerPage();
      classUnderTest0.goToDashboardAddEditLoginWidgetContainerPage();
      int int1 = 283;
      Id id0 = new Id(int1);
      WidgetFeedTitle widgetFeedTitle1 = WidgetFeedTitle.SPORTNEWS;
      WidgetFeedUrl widgetFeedUrl1 = WidgetFeedUrl.SPORT;
      WidgetFeedNumberOfPosts widgetFeedNumberOfPosts1 = new WidgetFeedNumberOfPosts(widgetFeedNumberOfPosts0.value);
      classUnderTest0.editFeedWidgetDashboardContainerPage(id0, widgetFeedTitle1, widgetFeedUrl1, widgetFeedNumberOfPosts1, widgetFeedPostContent1);
      classUnderTest0.goToDashboardDashboardContainerPage();
      WidgetUserType widgetUserType0 = WidgetUserType.LASTREGISTERED;
      WidgetUserDisplay widgetUserDisplay0 = WidgetUserDisplay.THUMBNAIL;
      WidgetTotalUser widgetTotalUser0 = WidgetTotalUser.HIDE;
      WidgetNumberOfUsers widgetNumberOfUsers0 = WidgetNumberOfUsers.TWENTYFOUR;
      classUnderTest0.addUserWidgetDashboardContainerPage(widgetUserType0, widgetUserDisplay0, widgetTotalUser0, widgetNumberOfUsers0);
      classUnderTest0.addLocationWidgetDashboardContainerPage(widgetLocation0, widgetUnit0);
      classUnderTest0.goToEditCurrentUserDashboardContainerPage();
      classUnderTest0.goToUsersAddEditUserContainerPage();
      classUnderTest0.goToSettingsUserListContainerPage();
      classUnderTest0.saveSettingsUserSettingsContainerPage();
      classUnderTest0.goToSiteUserSettingsContainerPage();
  }

  //Test case number: 17
  /*
   * 14 covered goals:
   * Goal 1. main.ClassUnderTest.addFeedWidgetDashboardContainerPage(Lcustom_classes/WidgetFeedTitle;Lcustom_classes/WidgetFeedUrl;Lcustom_classes/WidgetFeedNumberOfPosts;Lcustom_classes/WidgetFeedPostContent;)V: Line 515
   * Goal 2. main.ClassUnderTest.addLoginWidgetsContainerPage()V: Line 2758
   * Goal 3. main.ClassUnderTest.addPagePagesContainerPage()V: Line 1747
   * Goal 4. main.ClassUnderTest.closeEditLoginAddEditLoginWidgetContainerPage()V: Line 3201
   * Goal 5. main.ClassUnderTest.deleteAllPagesAndLinksPagesContainerPage()V: Line 1767
   * Goal 6. main.ClassUnderTest.editLocationWidgetDashboardContainerPage(Lcustom_classes/Id;Lcustom_classes/WidgetLocation;Lcustom_classes/WidgetUnit;)V: Line 664
   * Goal 7. main.ClassUnderTest.goToDashboardAddEditPageContainerPage()V: Line 2242
   * Goal 8. main.ClassUnderTest.goToDashboardDashboardContainerPage()V: Line 713
   * Goal 9. main.ClassUnderTest.goToDashboardWidgetsContainerPage()V: Line 2942
   * Goal 10. main.ClassUnderTest.goToMenuWidgetsContainerPage(Lcustom_classes/WidgetMenus;)V: Line 2971
   * Goal 11. main.ClassUnderTest.goToPermissionsUserListContainerPage()V: Line 932
   * Goal 12. main.ClassUnderTest.goToSiteDashboardContainerPage()V: Line 763
   * Goal 13. main.ClassUnderTest.goToUsersDashboardContainerPage()V: Line 775
   * Goal 14. main.ClassUnderTest.goToWidgetsPagesContainerPage()V: Line 1982
   */

  @Test(timeout = 1001000)
  public void test17()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      int int0 = 166;
      Id id0 = new Id(int0);
      WidgetLocation widgetLocation0 = WidgetLocation.GENOA;
      WidgetUnit widgetUnit0 = WidgetUnit.METRIC;
      classUnderTest0.editLocationWidgetDashboardContainerPage(id0, widgetLocation0, widgetUnit0);
      classUnderTest0.goToDashboardDashboardContainerPage();
      classUnderTest0.goToSiteDashboardContainerPage();
      classUnderTest0.deleteAllPagesAndLinksPagesContainerPage();
      classUnderTest0.goToWidgetsPagesContainerPage();
      classUnderTest0.addLoginWidgetsContainerPage();
      classUnderTest0.closeEditLoginAddEditLoginWidgetContainerPage();
      WidgetMenus widgetMenus0 = WidgetMenus.ALL;
      classUnderTest0.goToMenuWidgetsContainerPage(widgetMenus0);
      classUnderTest0.goToDashboardWidgetsContainerPage();
      classUnderTest0.goToSiteDashboardContainerPage();
      classUnderTest0.addPagePagesContainerPage();
      classUnderTest0.goToDashboardAddEditPageContainerPage();
      WidgetFeedTitle widgetFeedTitle0 = WidgetFeedTitle.SPORTNEWS;
      WidgetFeedUrl widgetFeedUrl0 = WidgetFeedUrl.SPORT;
      int int1 = (-1895);
      WidgetFeedNumberOfPosts widgetFeedNumberOfPosts0 = new WidgetFeedNumberOfPosts(int1);
      WidgetFeedPostContent widgetFeedPostContent0 = WidgetFeedPostContent.SHOWALLPOSTS;
      classUnderTest0.addFeedWidgetDashboardContainerPage(widgetFeedTitle0, widgetFeedUrl0, widgetFeedNumberOfPosts0, widgetFeedPostContent0);
      classUnderTest0.goToUsersDashboardContainerPage();
      classUnderTest0.goToPermissionsUserListContainerPage();
  }

  //Test case number: 18
  /*
   * 21 covered goals:
   * Goal 1. main.ClassUnderTest.addLocationWidgetDashboardContainerPage(Lcustom_classes/WidgetLocation;Lcustom_classes/WidgetUnit;)V: Line 533
   * Goal 2. main.ClassUnderTest.addUserWidgetDashboardContainerPage(Lcustom_classes/WidgetUserType;Lcustom_classes/WidgetUserDisplay;Lcustom_classes/WidgetTotalUser;Lcustom_classes/WidgetNumberOfUsers;)V: Line 553
   * Goal 3. main.ClassUnderTest.closeOperationAddEditUserContainerPage()V: Line 1285
   * Goal 4. main.ClassUnderTest.deleteLocationWidgetDashboardContainerPage(Lcustom_classes/Id;)V: Line 575
   * Goal 5. main.ClassUnderTest.editUserAddEditUserContainerPage(Lcustom_classes/Username;Lcustom_classes/Name;Lcustom_classes/Email;Lcustom_classes/UserPassword;)V: Line 1303
   * Goal 6. main.ClassUnderTest.goToDashboardAddEditUserContainerPage()V: Line 1320
   * Goal 7. main.ClassUnderTest.goToDashboardPermissionsContainerPage()V: Line 1446
   * Goal 8. main.ClassUnderTest.goToDashboardUserListContainerPage()V: Line 906
   * Goal 9. main.ClassUnderTest.goToEditCurrentUserDashboardContainerPage()V: Line 726
   * Goal 10. main.ClassUnderTest.goToEditCurrentUserPermissionsContainerPage()V: Line 1459
   * Goal 11. main.ClassUnderTest.goToEditCurrentUserUserListContainerPage()V: Line 919
   * Goal 12. main.ClassUnderTest.goToEditCurrentUserUserSettingsContainerPage()V: Line 1576
   * Goal 13. main.ClassUnderTest.goToPermissionsAddEditUserContainerPage()V: Line 1346
   * Goal 14. main.ClassUnderTest.goToRolesAddEditUserContainerPage()V: Line 1359
   * Goal 15. main.ClassUnderTest.goToRolesUserListContainerPage()V: Line 945
   * Goal 16. main.ClassUnderTest.goToRolesUserSettingsContainerPage()V: Line 1602
   * Goal 17. main.ClassUnderTest.goToSettingsAddEditUserContainerPage()V: Line 1372
   * Goal 18. main.ClassUnderTest.goToSettingsPermissionsContainerPage()V: Line 1498
   * Goal 19. main.ClassUnderTest.goToSettingsUserSettingsContainerPage()V: Line 1615
   * Goal 20. main.ClassUnderTest.goToUserListAddEditUserContainerPage()V: Line 1397
   * Goal 21. main.ClassUnderTest.goToUsersDashboardContainerPage()V: Line 775
   */

  @Test(timeout = 1001000)
  public void test18()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      int int0 = 4414;
      Id id0 = new Id(int0);
      classUnderTest0.goToUsersDashboardContainerPage();
      classUnderTest0.goToDashboardUserListContainerPage();
      classUnderTest0.goToUsersDashboardContainerPage();
      classUnderTest0.goToRolesUserListContainerPage();
      classUnderTest0.goToDashboardPermissionsContainerPage();
      WidgetLocation widgetLocation0 = WidgetLocation.TRENTO;
      WidgetUnit widgetUnit0 = WidgetUnit.IMPERIAL;
      classUnderTest0.addLocationWidgetDashboardContainerPage(widgetLocation0, widgetUnit0);
      classUnderTest0.goToEditCurrentUserDashboardContainerPage();
      classUnderTest0.goToUserListAddEditUserContainerPage();
      classUnderTest0.goToEditCurrentUserUserListContainerPage();
      classUnderTest0.goToDashboardAddEditUserContainerPage();
      classUnderTest0.deleteLocationWidgetDashboardContainerPage(id0);
      classUnderTest0.goToEditCurrentUserDashboardContainerPage();
      classUnderTest0.goToSettingsAddEditUserContainerPage();
      classUnderTest0.goToEditCurrentUserUserSettingsContainerPage();
      Username username0 = Username.FOO;
      Name name0 = Name.MARK;
      Email email0 = Email.ASD;
      UserPassword userPassword0 = UserPassword.ADMIN;
      classUnderTest0.editUserAddEditUserContainerPage(username0, name0, email0, userPassword0);
      Username username1 = Username.ADMIN;
      classUnderTest0.editUserAddEditUserContainerPage(username1, name0, email0, userPassword0);
      classUnderTest0.goToPermissionsAddEditUserContainerPage();
      classUnderTest0.goToDashboardPermissionsContainerPage();
      WidgetUserType widgetUserType0 = WidgetUserType.LASTREGISTERED;
      WidgetUserDisplay widgetUserDisplay0 = WidgetUserDisplay.LIST;
      WidgetTotalUser widgetTotalUser0 = WidgetTotalUser.HIDE;
      WidgetNumberOfUsers widgetNumberOfUsers0 = WidgetNumberOfUsers.EIGHTEEN;
      classUnderTest0.addUserWidgetDashboardContainerPage(widgetUserType0, widgetUserDisplay0, widgetTotalUser0, widgetNumberOfUsers0);
      classUnderTest0.goToEditCurrentUserDashboardContainerPage();
      classUnderTest0.closeOperationAddEditUserContainerPage();
      classUnderTest0.goToEditCurrentUserUserListContainerPage();
      classUnderTest0.goToPermissionsAddEditUserContainerPage();
      classUnderTest0.goToSettingsPermissionsContainerPage();
      classUnderTest0.goToSettingsUserSettingsContainerPage();
      classUnderTest0.goToSettingsUserSettingsContainerPage();
      classUnderTest0.goToRolesUserSettingsContainerPage();
      classUnderTest0.goToEditCurrentUserPermissionsContainerPage();
      classUnderTest0.closeOperationAddEditUserContainerPage();
      classUnderTest0.goToDashboardUserListContainerPage();
      classUnderTest0.goToEditCurrentUserDashboardContainerPage();
      classUnderTest0.goToSettingsAddEditUserContainerPage();
      classUnderTest0.goToEditCurrentUserUserSettingsContainerPage();
      classUnderTest0.goToRolesAddEditUserContainerPage();
  }

  //Test case number: 19
  /*
   * 10 covered goals:
   * Goal 1. main.ClassUnderTest.addLoginWidgetsContainerPage()V: Line 2758
   * Goal 2. main.ClassUnderTest.addUserWidgetDashboardContainerPage(Lcustom_classes/WidgetUserType;Lcustom_classes/WidgetUserDisplay;Lcustom_classes/WidgetTotalUser;Lcustom_classes/WidgetNumberOfUsers;)V: Line 553
   * Goal 3. main.ClassUnderTest.closeOperationAddEditUserContainerPage()V: Line 1285
   * Goal 4. main.ClassUnderTest.editFeedWidgetDashboardContainerPage(Lcustom_classes/Id;Lcustom_classes/WidgetFeedTitle;Lcustom_classes/WidgetFeedUrl;Lcustom_classes/WidgetFeedNumberOfPosts;Lcustom_classes/WidgetFeedPostContent;)V: Line 635
   * Goal 5. main.ClassUnderTest.goToDashboardPagesContainerPage()V: Line 1901
   * Goal 6. main.ClassUnderTest.goToDashboardUserListContainerPage()V: Line 906
   * Goal 7. main.ClassUnderTest.goToEditCurrentUserDashboardContainerPage()V: Line 726
   * Goal 8. main.ClassUnderTest.goToPagesAddEditLoginWidgetContainerPage()V: Line 3240
   * Goal 9. main.ClassUnderTest.goToSiteDashboardContainerPage()V: Line 763
   * Goal 10. main.ClassUnderTest.goToWidgetsPagesContainerPage()V: Line 1982
   */

  @Test(timeout = 1001000)
  public void test19()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      int int0 = 2096;
      Id id0 = new Id(int0);
      classUnderTest0.goToEditCurrentUserDashboardContainerPage();
      classUnderTest0.closeOperationAddEditUserContainerPage();
      classUnderTest0.goToDashboardUserListContainerPage();
      WidgetFeedTitle widgetFeedTitle0 = WidgetFeedTitle.SPORTNEWS;
      WidgetFeedUrl widgetFeedUrl0 = WidgetFeedUrl.PAGEKIT;
      WidgetFeedNumberOfPosts widgetFeedNumberOfPosts0 = new WidgetFeedNumberOfPosts(int0);
      WidgetFeedPostContent widgetFeedPostContent0 = WidgetFeedPostContent.DONTSHOW;
      classUnderTest0.editFeedWidgetDashboardContainerPage(id0, widgetFeedTitle0, widgetFeedUrl0, widgetFeedNumberOfPosts0, widgetFeedPostContent0);
      WidgetUserType widgetUserType0 = WidgetUserType.LOGGEDIN;
      WidgetUserDisplay widgetUserDisplay0 = WidgetUserDisplay.THUMBNAIL;
      WidgetTotalUser widgetTotalUser0 = WidgetTotalUser.SHOW;
      WidgetNumberOfUsers widgetNumberOfUsers0 = WidgetNumberOfUsers.TWELVE;
      classUnderTest0.addUserWidgetDashboardContainerPage(widgetUserType0, widgetUserDisplay0, widgetTotalUser0, widgetNumberOfUsers0);
      classUnderTest0.goToSiteDashboardContainerPage();
      classUnderTest0.goToDashboardPagesContainerPage();
      classUnderTest0.goToSiteDashboardContainerPage();
      classUnderTest0.goToWidgetsPagesContainerPage();
      classUnderTest0.addLoginWidgetsContainerPage();
      classUnderTest0.goToPagesAddEditLoginWidgetContainerPage();
  }

  //Test case number: 20
  /*
   * 7 covered goals:
   * Goal 1. main.ClassUnderTest.addLocationWidgetDashboardContainerPage(Lcustom_classes/WidgetLocation;Lcustom_classes/WidgetUnit;)V: Line 533
   * Goal 2. main.ClassUnderTest.addPagePagesContainerPage()V: Line 1747
   * Goal 3. main.ClassUnderTest.goToDashboardDashboardContainerPage()V: Line 713
   * Goal 4. main.ClassUnderTest.goToMetaAddEditPageContainerPage()V: Line 2268
   * Goal 5. main.ClassUnderTest.goToPagesAddEditPageContainerPage()V: Line 2281
   * Goal 6. main.ClassUnderTest.goToSiteDashboardContainerPage()V: Line 763
   * Goal 7. main.ClassUnderTest.goToSitePagesContainerPage()V: Line 1958
   */

  @Test(timeout = 1001000)
  public void test20()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      classUnderTest0.goToDashboardDashboardContainerPage();
      classUnderTest0.goToDashboardDashboardContainerPage();
      WidgetLocation widgetLocation0 = WidgetLocation.MILANO;
      WidgetUnit widgetUnit0 = WidgetUnit.METRIC;
      classUnderTest0.addLocationWidgetDashboardContainerPage(widgetLocation0, widgetUnit0);
      classUnderTest0.goToSiteDashboardContainerPage();
      classUnderTest0.goToSitePagesContainerPage();
      classUnderTest0.addPagePagesContainerPage();
      classUnderTest0.goToMetaAddEditPageContainerPage();
      classUnderTest0.goToMetaAddEditPageContainerPage();
      classUnderTest0.goToPagesAddEditPageContainerPage();
  }

  //Test case number: 21
  /*
   * 18 covered goals:
   * Goal 1. main.ClassUnderTest.addLocationWidgetDashboardContainerPage(Lcustom_classes/WidgetLocation;Lcustom_classes/WidgetUnit;)V: Line 533
   * Goal 2. main.ClassUnderTest.addTextWidgetsContainerPage()V: Line 2786
   * Goal 3. main.ClassUnderTest.addUserAddEditUserContainerPage(Lcustom_classes/Username;Lcustom_classes/Name;Lcustom_classes/Email;Lcustom_classes/UserPassword;Lcustom_classes/UserStatus;)V: Line 1263
   * Goal 4. main.ClassUnderTest.addUserUserListContainerPage()V: Line 812
   * Goal 5. main.ClassUnderTest.deleteLocationWidgetDashboardContainerPage(Lcustom_classes/Id;)V: Line 575
   * Goal 6. main.ClassUnderTest.goToDashboardUserListContainerPage()V: Line 906
   * Goal 7. main.ClassUnderTest.goToEditCurrentUserDashboardContainerPage()V: Line 726
   * Goal 8. main.ClassUnderTest.goToPagesAddEditTextWidgetContainerPage()V: Line 2449
   * Goal 9. main.ClassUnderTest.goToPermissionsAddEditUserContainerPage()V: Line 1346
   * Goal 10. main.ClassUnderTest.goToSiteDashboardContainerPage()V: Line 763
   * Goal 11. main.ClassUnderTest.goToSiteUserListContainerPage()V: Line 971
   * Goal 12. main.ClassUnderTest.goToUserListAddEditUserContainerPage()V: Line 1397
   * Goal 13. main.ClassUnderTest.goToUserListPermissionsContainerPage()V: Line 1523
   * Goal 14. main.ClassUnderTest.goToUserListUserListContainerPage()V: Line 983
   * Goal 15. main.ClassUnderTest.goToUsersAddEditUserContainerPage()V: Line 1409
   * Goal 16. main.ClassUnderTest.goToUsersDashboardContainerPage()V: Line 775
   * Goal 17. main.ClassUnderTest.goToUsersPagesContainerPage()V: Line 1970
   * Goal 18. main.ClassUnderTest.goToWidgetsPagesContainerPage()V: Line 1982
   */

  @Test(timeout = 1001000)
  public void test21()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      WidgetLocation widgetLocation0 = WidgetLocation.GENOA;
      WidgetUnit widgetUnit0 = WidgetUnit.IMPERIAL;
      classUnderTest0.addLocationWidgetDashboardContainerPage(widgetLocation0, widgetUnit0);
      int int0 = 250;
      Id id0 = new Id(int0);
      classUnderTest0.goToUsersDashboardContainerPage();
      classUnderTest0.addUserUserListContainerPage();
      classUnderTest0.goToUserListAddEditUserContainerPage();
      classUnderTest0.goToDashboardUserListContainerPage();
      classUnderTest0.deleteLocationWidgetDashboardContainerPage(id0);
      classUnderTest0.goToEditCurrentUserDashboardContainerPage();
      classUnderTest0.goToPermissionsAddEditUserContainerPage();
      classUnderTest0.goToUserListPermissionsContainerPage();
      classUnderTest0.goToDashboardUserListContainerPage();
      classUnderTest0.goToSiteDashboardContainerPage();
      classUnderTest0.goToUsersPagesContainerPage();
      classUnderTest0.addUserUserListContainerPage();
      Username username0 = Username.ADMIN;
      Name name0 = Name.JOHN;
      Email email0 = Email.ASD;
      UserPassword userPassword0 = UserPassword.ADMIN;
      UserStatus userStatus0 = UserStatus.BLOCKED;
      classUnderTest0.addUserAddEditUserContainerPage(username0, name0, email0, userPassword0, userStatus0);
      UserPassword userPassword1 = UserPassword.ADMIN;
      classUnderTest0.addUserAddEditUserContainerPage(username0, name0, email0, userPassword1, userStatus0);
      Username username1 = Username.FOO;
      Email email1 = Email.ASD;
      UserPassword userPassword2 = UserPassword.FOO;
      UserStatus userStatus1 = UserStatus.ACTIVE;
      classUnderTest0.addUserAddEditUserContainerPage(username1, name0, email1, userPassword2, userStatus1);
      classUnderTest0.goToUsersAddEditUserContainerPage();
      classUnderTest0.goToUserListUserListContainerPage();
      classUnderTest0.goToSiteUserListContainerPage();
      classUnderTest0.goToWidgetsPagesContainerPage();
      classUnderTest0.addTextWidgetsContainerPage();
      classUnderTest0.goToPagesAddEditTextWidgetContainerPage();
  }

  //Test case number: 22
  /*
   * 12 covered goals:
   * Goal 1. main.ClassUnderTest.addFeedWidgetDashboardContainerPage(Lcustom_classes/WidgetFeedTitle;Lcustom_classes/WidgetFeedUrl;Lcustom_classes/WidgetFeedNumberOfPosts;Lcustom_classes/WidgetFeedPostContent;)V: Line 515
   * Goal 2. main.ClassUnderTest.confirmOperationDeleteItemPage()V: Line 289
   * Goal 3. main.ClassUnderTest.deleteUserOrFeedWidgetDashboardContainerPage(Lcustom_classes/Id;)V: Line 603
   * Goal 4. main.ClassUnderTest.giveOrRemoveAllPermissionsToUserRolePermissionsContainerPage(Lcustom_classes/UserRoles;)V: Line 1428
   * Goal 5. main.ClassUnderTest.goToDashboardAddEditUserContainerPage()V: Line 1320
   * Goal 6. main.ClassUnderTest.goToDashboardDashboardContainerPage()V: Line 713
   * Goal 7. main.ClassUnderTest.goToEditCurrentUserDashboardContainerPage()V: Line 726
   * Goal 8. main.ClassUnderTest.goToPermissionsUserListContainerPage()V: Line 932
   * Goal 9. main.ClassUnderTest.goToPermissionsUserSettingsContainerPage()V: Line 1589
   * Goal 10. main.ClassUnderTest.goToRolesUserSettingsContainerPage()V: Line 1602
   * Goal 11. main.ClassUnderTest.goToSettingsPermissionsContainerPage()V: Line 1498
   * Goal 12. main.ClassUnderTest.goToUsersDashboardContainerPage()V: Line 775
   */

  @Test(timeout = 1001000)
  public void test22()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      int int0 = (-2209);
      Id id0 = new Id(int0);
      classUnderTest0.deleteUserOrFeedWidgetDashboardContainerPage(id0);
      classUnderTest0.confirmOperationDeleteItemPage();
      classUnderTest0.goToDashboardDashboardContainerPage();
      classUnderTest0.goToEditCurrentUserDashboardContainerPage();
      classUnderTest0.goToDashboardAddEditUserContainerPage();
      WidgetFeedTitle widgetFeedTitle0 = WidgetFeedTitle.PAGEKITNEWS;
      WidgetFeedUrl widgetFeedUrl0 = WidgetFeedUrl.SPORT;
      int int1 = (-4354);
      WidgetFeedNumberOfPosts widgetFeedNumberOfPosts0 = new WidgetFeedNumberOfPosts(int1);
      WidgetFeedPostContent widgetFeedPostContent0 = WidgetFeedPostContent.SHOWFIRSTPOST;
      classUnderTest0.addFeedWidgetDashboardContainerPage(widgetFeedTitle0, widgetFeedUrl0, widgetFeedNumberOfPosts0, widgetFeedPostContent0);
      classUnderTest0.goToUsersDashboardContainerPage();
      classUnderTest0.goToPermissionsUserListContainerPage();
      UserRoles userRoles0 = UserRoles.ANONYMOUS;
      classUnderTest0.giveOrRemoveAllPermissionsToUserRolePermissionsContainerPage(userRoles0);
      classUnderTest0.giveOrRemoveAllPermissionsToUserRolePermissionsContainerPage(userRoles0);
      classUnderTest0.goToSettingsPermissionsContainerPage();
      classUnderTest0.goToPermissionsUserSettingsContainerPage();
      classUnderTest0.goToSettingsPermissionsContainerPage();
      classUnderTest0.goToRolesUserSettingsContainerPage();
  }

  //Test case number: 23
  /*
   * 12 covered goals:
   * Goal 1. main.ClassUnderTest.addTextWidgetsContainerPage()V: Line 2786
   * Goal 2. main.ClassUnderTest.goToEditUserDashboardContainerPage(Lcustom_classes/Id;)V: Line 746
   * Goal 3. main.ClassUnderTest.goToPermissionsPermissionsContainerPage()V: Line 1472
   * Goal 4. main.ClassUnderTest.goToPermissionsUserListContainerPage()V: Line 932
   * Goal 5. main.ClassUnderTest.goToSiteAddEditTextWidgetContainerPage()V: Line 2474
   * Goal 6. main.ClassUnderTest.goToSiteAddEditUserContainerPage()V: Line 1385
   * Goal 7. main.ClassUnderTest.goToSitePermissionsContainerPage()V: Line 1511
   * Goal 8. main.ClassUnderTest.goToUserListPermissionsContainerPage()V: Line 1523
   * Goal 9. main.ClassUnderTest.goToUsersPagesContainerPage()V: Line 1970
   * Goal 10. main.ClassUnderTest.goToWidgetsPagesContainerPage()V: Line 1982
   * Goal 11. main.ClassUnderTest.moveAllPagesAndLinksToMenuPagesContainerPage(Lcustom_classes/SiteMenus;)V: Line 2000
   * Goal 12. main.ClassUnderTest.publishAllPagesAndLinksPagesContainerPage()V: Line 2047
   */

  @Test(timeout = 1001000)
  public void test23()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      int int0 = 3150;
      Id id0 = new Id(int0);
      classUnderTest0.goToEditUserDashboardContainerPage(id0);
      classUnderTest0.goToSiteAddEditUserContainerPage();
      classUnderTest0.publishAllPagesAndLinksPagesContainerPage();
      SiteMenus siteMenus0 = SiteMenus.NOT_LINKED;
      classUnderTest0.moveAllPagesAndLinksToMenuPagesContainerPage(siteMenus0);
      classUnderTest0.goToUsersPagesContainerPage();
      classUnderTest0.goToPermissionsUserListContainerPage();
      classUnderTest0.goToUserListPermissionsContainerPage();
      classUnderTest0.goToPermissionsUserListContainerPage();
      classUnderTest0.goToPermissionsPermissionsContainerPage();
      classUnderTest0.goToSitePermissionsContainerPage();
      classUnderTest0.goToWidgetsPagesContainerPage();
      classUnderTest0.addTextWidgetsContainerPage();
      classUnderTest0.goToSiteAddEditTextWidgetContainerPage();
  }

  //Test case number: 24
  /*
   * 14 covered goals:
   * Goal 1. main.ClassUnderTest.addPagePagesContainerPage()V: Line 1747
   * Goal 2. main.ClassUnderTest.addUserUserListContainerPage()V: Line 812
   * Goal 3. main.ClassUnderTest.goToEditCurrentUserAddEditUserContainerPage()V: Line 1333
   * Goal 4. main.ClassUnderTest.goToEditCurrentUserPagesContainerPage()V: Line 1914
   * Goal 5. main.ClassUnderTest.goToEditCurrentUserUserSettingsContainerPage()V: Line 1576
   * Goal 6. main.ClassUnderTest.goToMetaAddEditPageContainerPage()V: Line 2268
   * Goal 7. main.ClassUnderTest.goToRolesAddEditUserContainerPage()V: Line 1359
   * Goal 8. main.ClassUnderTest.goToSettingsPermissionsContainerPage()V: Line 1498
   * Goal 9. main.ClassUnderTest.goToSiteAddEditUserContainerPage()V: Line 1385
   * Goal 10. main.ClassUnderTest.goToSiteUserListContainerPage()V: Line 971
   * Goal 11. main.ClassUnderTest.goToUserListUserListContainerPage()V: Line 983
   * Goal 12. main.ClassUnderTest.goToUsersAddEditPageContainerPage()V: Line 2305
   * Goal 13. main.ClassUnderTest.goToUsersDashboardContainerPage()V: Line 775
   * Goal 14. main.ClassUnderTest.goToUsersUserListContainerPage()V: Line 995
   */

  @Test(timeout = 1001000)
  public void test24()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      classUnderTest0.goToUsersDashboardContainerPage();
      classUnderTest0.goToUsersUserListContainerPage();
      classUnderTest0.goToUserListUserListContainerPage();
      classUnderTest0.goToSiteUserListContainerPage();
      classUnderTest0.goToEditCurrentUserPagesContainerPage();
      classUnderTest0.goToEditCurrentUserAddEditUserContainerPage();
      classUnderTest0.goToSiteAddEditUserContainerPage();
      classUnderTest0.addPagePagesContainerPage();
      classUnderTest0.goToMetaAddEditPageContainerPage();
      classUnderTest0.goToUsersAddEditPageContainerPage();
      classUnderTest0.addUserUserListContainerPage();
      classUnderTest0.goToRolesAddEditUserContainerPage();
      classUnderTest0.goToSettingsPermissionsContainerPage();
      classUnderTest0.goToEditCurrentUserUserSettingsContainerPage();
  }

  //Test case number: 25
  /*
   * 11 covered goals:
   * Goal 1. main.ClassUnderTest.addLoginWidgetsContainerPage()V: Line 2758
   * Goal 2. main.ClassUnderTest.addUserWidgetDashboardContainerPage(Lcustom_classes/WidgetUserType;Lcustom_classes/WidgetUserDisplay;Lcustom_classes/WidgetTotalUser;Lcustom_classes/WidgetNumberOfUsers;)V: Line 553
   * Goal 3. main.ClassUnderTest.closeEditLoginAddEditLoginWidgetContainerPage()V: Line 3201
   * Goal 4. main.ClassUnderTest.deleteAllPagesAndLinksPagesContainerPage()V: Line 1767
   * Goal 5. main.ClassUnderTest.editLocationWidgetDashboardContainerPage(Lcustom_classes/Id;Lcustom_classes/WidgetLocation;Lcustom_classes/WidgetUnit;)V: Line 664
   * Goal 6. main.ClassUnderTest.goToDashboardDashboardContainerPage()V: Line 713
   * Goal 7. main.ClassUnderTest.goToDashboardWidgetsContainerPage()V: Line 2942
   * Goal 8. main.ClassUnderTest.goToMenuWidgetsContainerPage(Lcustom_classes/WidgetMenus;)V: Line 2971
   * Goal 9. main.ClassUnderTest.goToSiteDashboardContainerPage()V: Line 763
   * Goal 10. main.ClassUnderTest.goToWidgetsPagesContainerPage()V: Line 1982
   * Goal 11. main.ClassUnderTest.selectLogoutRedirectLinkAddEditLoginWidgetContainerPage()V: Line 3364
   */

  @Test(timeout = 1001000)
  public void test25()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      int int0 = 166;
      Id id0 = new Id(int0);
      WidgetLocation widgetLocation0 = WidgetLocation.GENOA;
      WidgetUnit widgetUnit0 = WidgetUnit.METRIC;
      classUnderTest0.editLocationWidgetDashboardContainerPage(id0, widgetLocation0, widgetUnit0);
      classUnderTest0.goToDashboardDashboardContainerPage();
      classUnderTest0.goToSiteDashboardContainerPage();
      classUnderTest0.deleteAllPagesAndLinksPagesContainerPage();
      classUnderTest0.goToWidgetsPagesContainerPage();
      classUnderTest0.addLoginWidgetsContainerPage();
      classUnderTest0.closeEditLoginAddEditLoginWidgetContainerPage();
      WidgetMenus widgetMenus0 = WidgetMenus.ALL;
      classUnderTest0.goToMenuWidgetsContainerPage(widgetMenus0);
      classUnderTest0.goToDashboardWidgetsContainerPage();
      WidgetUserType widgetUserType0 = WidgetUserType.LOGGEDIN;
      WidgetTotalUser widgetTotalUser0 = WidgetTotalUser.SHOW;
      classUnderTest0.goToDashboardDashboardContainerPage();
      WidgetUserDisplay widgetUserDisplay0 = WidgetUserDisplay.THUMBNAIL;
      WidgetNumberOfUsers widgetNumberOfUsers0 = WidgetNumberOfUsers.EIGHTEEN;
      classUnderTest0.addUserWidgetDashboardContainerPage(widgetUserType0, widgetUserDisplay0, widgetTotalUser0, widgetNumberOfUsers0);
      classUnderTest0.goToSiteDashboardContainerPage();
      classUnderTest0.goToWidgetsPagesContainerPage();
      classUnderTest0.addLoginWidgetsContainerPage();
      classUnderTest0.selectLogoutRedirectLinkAddEditLoginWidgetContainerPage();
  }
}
