/*
 * This file was automatically generated by EvoSuite
 * Fri May 08 09:43:14 GMT 2020
 */

package main;

import org.junit.Test;
import static org.junit.Assert.*;
import custom_classes.Email;
import custom_classes.Extension;
import custom_classes.HTMLSnippets;
import custom_classes.HideInMenu;
import custom_classes.Id;
import custom_classes.Name;
import custom_classes.PageLinkStatus;
import custom_classes.RegistrationUserSettings;
import custom_classes.SiteMenus;
import custom_classes.SitePages;
import custom_classes.UserPassword;
import custom_classes.UserRoles;
import custom_classes.UserStatus;
import custom_classes.Username;
import custom_classes.WidgetFeedNumberOfPosts;
import custom_classes.WidgetFeedPostContent;
import custom_classes.WidgetFeedTitle;
import custom_classes.WidgetFeedUrl;
import custom_classes.WidgetLocation;
import custom_classes.WidgetMenus;
import custom_classes.WidgetNumberOfUsers;
import custom_classes.WidgetTotalUser;
import custom_classes.WidgetUnit;
import custom_classes.WidgetUserDisplay;
import custom_classes.WidgetUserType;
import main.ClassUnderTest;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, resetStaticState = true) 
public class ClassUnderTest_ESTest extends ClassUnderTest_ESTest_scaffolding {

  //Test case number: 0
  /*
   * 18 covered goals:
   * Goal 1. main.ClassUnderTest.activateUserUserListContainerPage(Lcustom_classes/Id;)V: Line 793
   * Goal 2. main.ClassUnderTest.addLocationWidgetDashboardContainerPage(Lcustom_classes/WidgetLocation;Lcustom_classes/WidgetUnit;)V: Line 533
   * Goal 3. main.ClassUnderTest.addMenuWidgetsContainerPage()V: Line 2772
   * Goal 4. main.ClassUnderTest.cancelOperationDeleteItemPage()V: Line 257
   * Goal 5. main.ClassUnderTest.deleteUserUserListContainerPage(Lcustom_classes/Id;)V: Line 889
   * Goal 6. main.ClassUnderTest.goToEditCurrentUserAddEditMenuWidgetContainerPage()V: Line 3504
   * Goal 7. main.ClassUnderTest.goToEditCurrentUserPagesContainerPage()V: Line 1914
   * Goal 8. main.ClassUnderTest.goToPermissionsUserListContainerPage()V: Line 932
   * Goal 9. main.ClassUnderTest.goToRolesUserListContainerPage()V: Line 945
   * Goal 10. main.ClassUnderTest.goToSettingsAddEditUserContainerPage()V: Line 1372
   * Goal 11. main.ClassUnderTest.goToSiteDashboardContainerPage()V: Line 763
   * Goal 12. main.ClassUnderTest.goToSitePagesContainerPage()V: Line 1958
   * Goal 13. main.ClassUnderTest.goToSitePermissionsContainerPage()V: Line 1511
   * Goal 14. main.ClassUnderTest.goToSiteUserSettingsContainerPage()V: Line 1628
   * Goal 15. main.ClassUnderTest.goToUserListAddEditUserContainerPage()V: Line 1397
   * Goal 16. main.ClassUnderTest.goToUsersPagesContainerPage()V: Line 1970
   * Goal 17. main.ClassUnderTest.goToWidgetsPagesContainerPage()V: Line 1982
   * Goal 18. main.ClassUnderTest.moveAllPagesAndLinksToMenuPagesContainerPage(Lcustom_classes/SiteMenus;)V: Line 2000
   */

  @Test(timeout = 1001000)
  public void test00()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      WidgetLocation widgetLocation0 = WidgetLocation.GENOA;
      WidgetUnit widgetUnit0 = WidgetUnit.IMPERIAL;
      classUnderTest0.addLocationWidgetDashboardContainerPage(widgetLocation0, widgetUnit0);
      int int0 = 3620;
      Id id0 = new Id(int0);
      classUnderTest0.goToSiteDashboardContainerPage();
      classUnderTest0.goToWidgetsPagesContainerPage();
      classUnderTest0.addMenuWidgetsContainerPage();
      classUnderTest0.goToEditCurrentUserAddEditMenuWidgetContainerPage();
      classUnderTest0.goToSettingsAddEditUserContainerPage();
      classUnderTest0.goToSiteUserSettingsContainerPage();
      classUnderTest0.goToSitePagesContainerPage();
      SiteMenus siteMenus0 = SiteMenus.MAIN;
      classUnderTest0.moveAllPagesAndLinksToMenuPagesContainerPage(siteMenus0);
      classUnderTest0.goToEditCurrentUserPagesContainerPage();
      classUnderTest0.goToUserListAddEditUserContainerPage();
      Id id1 = new Id(id0.value);
      classUnderTest0.activateUserUserListContainerPage(id1);
      classUnderTest0.goToPermissionsUserListContainerPage();
      classUnderTest0.goToSitePermissionsContainerPage();
      classUnderTest0.goToUsersPagesContainerPage();
      classUnderTest0.deleteUserUserListContainerPage(id1);
      classUnderTest0.cancelOperationDeleteItemPage();
      classUnderTest0.goToRolesUserListContainerPage();
  }

  //Test case number: 1
  /*
   * 13 covered goals:
   * Goal 1. main.ClassUnderTest.addEditPageAddEditPageContainerPage(Lcustom_classes/SitePages;Lcustom_classes/HTMLSnippets;Lcustom_classes/PageLinkStatus;Lcustom_classes/HideInMenu;)V: Line 2166
   * Goal 2. main.ClassUnderTest.addLinkPagesContainerPage()V: Line 1706
   * Goal 3. main.ClassUnderTest.addPagePagesContainerPage()V: Line 1747
   * Goal 4. main.ClassUnderTest.goToEditCurrentUserAddEditPageContainerPage()V: Line 2255
   * Goal 5. main.ClassUnderTest.goToPagesAddEditLinkContainerPage()V: Line 2681
   * Goal 6. main.ClassUnderTest.goToRolesUserSettingsContainerPage()V: Line 1602
   * Goal 7. main.ClassUnderTest.goToSettingsAddEditLinkContainerPage()V: Line 2693
   * Goal 8. main.ClassUnderTest.goToSettingsUserListContainerPage()V: Line 958
   * Goal 9. main.ClassUnderTest.goToSiteDashboardContainerPage()V: Line 763
   * Goal 10. main.ClassUnderTest.goToUserListAddEditUserContainerPage()V: Line 1397
   * Goal 11. main.ClassUnderTest.goToUsersPermissionsContainerPage()V: Line 1535
   * Goal 12. main.ClassUnderTest.selectUrlAddEditLinkContainerPage()V: Line 2744
   * Goal 13. main.ClassUnderTest.updateSelectLinkPage()V: Line 214
   */

  @Test(timeout = 1001000)
  public void test01()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      SitePages sitePages0 = SitePages.SPECIAL_POSTS;
      classUnderTest0.goToSiteDashboardContainerPage();
      classUnderTest0.addLinkPagesContainerPage();
      classUnderTest0.selectUrlAddEditLinkContainerPage();
      classUnderTest0.updateSelectLinkPage();
      classUnderTest0.goToSettingsAddEditLinkContainerPage();
      classUnderTest0.goToPagesAddEditLinkContainerPage();
      classUnderTest0.addPagePagesContainerPage();
      HTMLSnippets hTMLSnippets0 = HTMLSnippets.IMAGE_TITLE;
      PageLinkStatus pageLinkStatus0 = PageLinkStatus.DISABLED;
      HideInMenu hideInMenu0 = HideInMenu.YES;
      classUnderTest0.addEditPageAddEditPageContainerPage(sitePages0, hTMLSnippets0, pageLinkStatus0, hideInMenu0);
      classUnderTest0.goToEditCurrentUserAddEditPageContainerPage();
      classUnderTest0.goToUserListAddEditUserContainerPage();
      classUnderTest0.goToSettingsUserListContainerPage();
      classUnderTest0.goToRolesUserSettingsContainerPage();
      classUnderTest0.goToUsersPermissionsContainerPage();
  }

  //Test case number: 2
  /*
   * 26 covered goals:
   * Goal 1. main.ClassUnderTest.addEditPageRestrictAccessAddEditPageContainerPage(Lcustom_classes/SitePages;Lcustom_classes/HTMLSnippets;Lcustom_classes/PageLinkStatus;Lcustom_classes/UserRoles;Lcustom_classes/HideInMenu;)V: Line 2198
   * Goal 2. main.ClassUnderTest.addFeedWidgetDashboardContainerPage(Lcustom_classes/WidgetFeedTitle;Lcustom_classes/WidgetFeedUrl;Lcustom_classes/WidgetFeedNumberOfPosts;Lcustom_classes/WidgetFeedPostContent;)V: Line 515
   * Goal 3. main.ClassUnderTest.addItemAddEditItemPage()V: Line 396
   * Goal 4. main.ClassUnderTest.addLinkPagesContainerPage()V: Line 1706
   * Goal 5. main.ClassUnderTest.addMenuPagesContainerPage(Lcustom_classes/SiteMenus;)V: Line 1727
   * Goal 6. main.ClassUnderTest.addPagePagesContainerPage()V: Line 1747
   * Goal 7. main.ClassUnderTest.cancelOperationAddEditItemPage()V: Line 426
   * Goal 8. main.ClassUnderTest.cancelOperationDeleteItemPage()V: Line 252
   * Goal 9. main.ClassUnderTest.deleteUserOrFeedWidgetDashboardContainerPage(Lcustom_classes/Id;)V: Line 603
   * Goal 10. main.ClassUnderTest.editPagePagesContainerPage(Lcustom_classes/SitePages;)V: Line 1884
   * Goal 11. main.ClassUnderTest.goToDashboardPermissionsContainerPage()V: Line 1446
   * Goal 12. main.ClassUnderTest.goToDashboardUserListContainerPage()V: Line 906
   * Goal 13. main.ClassUnderTest.goToEditCurrentUserUserListContainerPage()V: Line 919
   * Goal 14. main.ClassUnderTest.goToEditCurrentUserWidgetsContainerPage()V: Line 2955
   * Goal 15. main.ClassUnderTest.goToMetaAddEditLinkContainerPage()V: Line 2668
   * Goal 16. main.ClassUnderTest.goToPermissionsPermissionsContainerPage()V: Line 1472
   * Goal 17. main.ClassUnderTest.goToRolesAddEditUserContainerPage()V: Line 1359
   * Goal 18. main.ClassUnderTest.goToSiteDashboardContainerPage()V: Line 763
   * Goal 19. main.ClassUnderTest.goToSiteUserListContainerPage()V: Line 971
   * Goal 20. main.ClassUnderTest.goToUserListUserListContainerPage()V: Line 983
   * Goal 21. main.ClassUnderTest.goToUsersAddEditLinkContainerPage()V: Line 2718
   * Goal 22. main.ClassUnderTest.goToUsersAddEditPageContainerPage()V: Line 2305
   * Goal 23. main.ClassUnderTest.goToUsersAddEditUserContainerPage()V: Line 1409
   * Goal 24. main.ClassUnderTest.goToUsersDashboardContainerPage()V: Line 775
   * Goal 25. main.ClassUnderTest.goToUsersUserListContainerPage()V: Line 995
   * Goal 26. main.ClassUnderTest.goToWidgetsAddEditPageContainerPage()V: Line 2317
   */

  @Test(timeout = 1001000)
  public void test02()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      WidgetFeedTitle widgetFeedTitle0 = WidgetFeedTitle.WEATHER;
      WidgetFeedUrl widgetFeedUrl0 = WidgetFeedUrl.SPORT;
      int int0 = 1294;
      WidgetFeedNumberOfPosts widgetFeedNumberOfPosts0 = new WidgetFeedNumberOfPosts(int0);
      WidgetFeedPostContent widgetFeedPostContent0 = WidgetFeedPostContent.SHOWFIRSTPOST;
      classUnderTest0.addFeedWidgetDashboardContainerPage(widgetFeedTitle0, widgetFeedUrl0, widgetFeedNumberOfPosts0, widgetFeedPostContent0);
      int int1 = 1881;
      Id id0 = new Id(int1);
      classUnderTest0.goToSiteDashboardContainerPage();
      classUnderTest0.addPagePagesContainerPage();
      classUnderTest0.goToWidgetsAddEditPageContainerPage();
      classUnderTest0.goToEditCurrentUserWidgetsContainerPage();
      classUnderTest0.goToRolesAddEditUserContainerPage();
      classUnderTest0.goToPermissionsPermissionsContainerPage();
      classUnderTest0.goToDashboardPermissionsContainerPage();
      classUnderTest0.goToUsersDashboardContainerPage();
      classUnderTest0.goToUsersUserListContainerPage();
      classUnderTest0.goToEditCurrentUserUserListContainerPage();
      classUnderTest0.goToUsersAddEditUserContainerPage();
      classUnderTest0.goToSiteUserListContainerPage();
      SiteMenus siteMenus0 = SiteMenus.OTHER_MENU;
      classUnderTest0.addMenuPagesContainerPage(siteMenus0);
      classUnderTest0.cancelOperationAddEditItemPage();
      classUnderTest0.addMenuPagesContainerPage(siteMenus0);
      classUnderTest0.addItemAddEditItemPage();
      classUnderTest0.addLinkPagesContainerPage();
      classUnderTest0.goToMetaAddEditLinkContainerPage();
      classUnderTest0.goToUsersAddEditLinkContainerPage();
      classUnderTest0.goToUserListUserListContainerPage();
      classUnderTest0.goToSiteUserListContainerPage();
      SitePages sitePages0 = SitePages.HOME;
      classUnderTest0.editPagePagesContainerPage(sitePages0);
      HTMLSnippets hTMLSnippets0 = HTMLSnippets.IMAGE_TITLE;
      PageLinkStatus pageLinkStatus0 = PageLinkStatus.ENABLED;
      UserRoles userRoles0 = UserRoles.AUTHENTICATED;
      HideInMenu hideInMenu0 = HideInMenu.NO;
      classUnderTest0.addEditPageRestrictAccessAddEditPageContainerPage(sitePages0, hTMLSnippets0, pageLinkStatus0, userRoles0, hideInMenu0);
      classUnderTest0.goToUsersAddEditPageContainerPage();
      classUnderTest0.goToDashboardUserListContainerPage();
      classUnderTest0.deleteUserOrFeedWidgetDashboardContainerPage(id0);
      classUnderTest0.cancelOperationDeleteItemPage();
  }

  //Test case number: 3
  /*
   * 15 covered goals:
   * Goal 1. main.ClassUnderTest.addExistingMenuPagesContainerPage(Lcustom_classes/SiteMenus;)V: Line 1686
   * Goal 2. main.ClassUnderTest.addItemAddEditItemPage()V: Line 380
   * Goal 3. main.ClassUnderTest.addLinkPagesContainerPage()V: Line 1706
   * Goal 4. main.ClassUnderTest.deleteAllPagesAndLinksPagesContainerPage()V: Line 1767
   * Goal 5. main.ClassUnderTest.goToEditCurrentUserDashboardContainerPage()V: Line 726
   * Goal 6. main.ClassUnderTest.goToPagesPagesContainerPage()V: Line 1946
   * Goal 7. main.ClassUnderTest.goToPagesWidgetsContainerPage()V: Line 2988
   * Goal 8. main.ClassUnderTest.goToSettingsUserListContainerPage()V: Line 958
   * Goal 9. main.ClassUnderTest.goToSitePagesContainerPage()V: Line 1958
   * Goal 10. main.ClassUnderTest.goToSiteUserListContainerPage()V: Line 971
   * Goal 11. main.ClassUnderTest.goToUserListUserSettingsContainerPage()V: Line 1640
   * Goal 12. main.ClassUnderTest.goToUsersAddEditUserContainerPage()V: Line 1409
   * Goal 13. main.ClassUnderTest.goToWidgetsAddEditLinkContainerPage()V: Line 2730
   * Goal 14. main.ClassUnderTest.publishAllPagesAndLinksPagesContainerPage()V: Line 2047
   * Goal 15. main.ClassUnderTest.unpublishAllPagesAndLinksPagesContainerPage()V: Line 2091
   */

  @Test(timeout = 1001000)
  public void test03()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      classUnderTest0.goToEditCurrentUserDashboardContainerPage();
      classUnderTest0.goToUsersAddEditUserContainerPage();
      classUnderTest0.goToSettingsUserListContainerPage();
      classUnderTest0.goToUserListUserSettingsContainerPage();
      classUnderTest0.goToSiteUserListContainerPage();
      classUnderTest0.publishAllPagesAndLinksPagesContainerPage();
      classUnderTest0.goToSitePagesContainerPage();
      classUnderTest0.unpublishAllPagesAndLinksPagesContainerPage();
      classUnderTest0.deleteAllPagesAndLinksPagesContainerPage();
      SiteMenus siteMenus0 = SiteMenus.MAIN;
      classUnderTest0.addExistingMenuPagesContainerPage(siteMenus0);
      classUnderTest0.addItemAddEditItemPage();
      classUnderTest0.goToPagesPagesContainerPage();
      classUnderTest0.addLinkPagesContainerPage();
      classUnderTest0.goToWidgetsAddEditLinkContainerPage();
      classUnderTest0.goToPagesWidgetsContainerPage();
  }

  //Test case number: 4
  /*
   * 18 covered goals:
   * Goal 1. main.ClassUnderTest.addLinkPagesContainerPage()V: Line 1706
   * Goal 2. main.ClassUnderTest.addLoginWidgetsContainerPage()V: Line 2758
   * Goal 3. main.ClassUnderTest.addPagePagesContainerPage()V: Line 1747
   * Goal 4. main.ClassUnderTest.editFeedWidgetDashboardContainerPage(Lcustom_classes/Id;Lcustom_classes/WidgetFeedTitle;Lcustom_classes/WidgetFeedUrl;Lcustom_classes/WidgetFeedNumberOfPosts;Lcustom_classes/WidgetFeedPostContent;)V: Line 635
   * Goal 5. main.ClassUnderTest.goToEditCurrentUserUserListContainerPage()V: Line 919
   * Goal 6. main.ClassUnderTest.goToMenuWidgetsContainerPage(Lcustom_classes/WidgetMenus;)V: Line 2971
   * Goal 7. main.ClassUnderTest.goToPagesPagesContainerPage()V: Line 1946
   * Goal 8. main.ClassUnderTest.goToSettingsUserListContainerPage()V: Line 958
   * Goal 9. main.ClassUnderTest.goToSiteAddEditLinkContainerPage()V: Line 2706
   * Goal 10. main.ClassUnderTest.goToSiteAddEditPageContainerPage()V: Line 2293
   * Goal 11. main.ClassUnderTest.goToSiteDashboardContainerPage()V: Line 763
   * Goal 12. main.ClassUnderTest.goToSitePagesContainerPage()V: Line 1958
   * Goal 13. main.ClassUnderTest.goToSiteUserListContainerPage()V: Line 971
   * Goal 14. main.ClassUnderTest.goToUserListUserListContainerPage()V: Line 983
   * Goal 15. main.ClassUnderTest.goToUsersAddEditLoginWidgetContainerPage()V: Line 3277
   * Goal 16. main.ClassUnderTest.goToUsersAddEditUserContainerPage()V: Line 1409
   * Goal 17. main.ClassUnderTest.goToUsersUserSettingsContainerPage()V: Line 1652
   * Goal 18. main.ClassUnderTest.goToWidgetsPagesContainerPage()V: Line 1982
   */

  @Test(timeout = 1001000)
  public void test04()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      int int0 = 3587;
      Id id0 = new Id(int0);
      WidgetFeedTitle widgetFeedTitle0 = WidgetFeedTitle.PAGEKITNEWS;
      WidgetFeedUrl widgetFeedUrl0 = WidgetFeedUrl.PAGEKIT;
      WidgetFeedNumberOfPosts widgetFeedNumberOfPosts0 = new WidgetFeedNumberOfPosts(id0.value);
      WidgetFeedPostContent widgetFeedPostContent0 = WidgetFeedPostContent.DONTSHOW;
      classUnderTest0.editFeedWidgetDashboardContainerPage(id0, widgetFeedTitle0, widgetFeedUrl0, widgetFeedNumberOfPosts0, widgetFeedPostContent0);
      classUnderTest0.goToSiteDashboardContainerPage();
      classUnderTest0.goToPagesPagesContainerPage();
      classUnderTest0.addPagePagesContainerPage();
      classUnderTest0.goToSiteAddEditPageContainerPage();
      classUnderTest0.goToSitePagesContainerPage();
      classUnderTest0.addLinkPagesContainerPage();
      classUnderTest0.goToSiteAddEditLinkContainerPage();
      classUnderTest0.goToPagesPagesContainerPage();
      classUnderTest0.goToWidgetsPagesContainerPage();
      WidgetMenus widgetMenus0 = WidgetMenus.UNASSIGNED;
      classUnderTest0.goToMenuWidgetsContainerPage(widgetMenus0);
      classUnderTest0.addLoginWidgetsContainerPage();
      classUnderTest0.goToUsersAddEditLoginWidgetContainerPage();
      classUnderTest0.goToEditCurrentUserUserListContainerPage();
      classUnderTest0.goToUsersAddEditUserContainerPage();
      classUnderTest0.goToSettingsUserListContainerPage();
      classUnderTest0.goToUsersUserSettingsContainerPage();
      classUnderTest0.goToUserListUserListContainerPage();
      classUnderTest0.goToSiteUserListContainerPage();
  }

  //Test case number: 5
  /*
   * 11 covered goals:
   * Goal 1. main.ClassUnderTest.addLinkPagesContainerPage()V: Line 1706
   * Goal 2. main.ClassUnderTest.addLocationWidgetDashboardContainerPage(Lcustom_classes/WidgetLocation;Lcustom_classes/WidgetUnit;)V: Line 533
   * Goal 3. main.ClassUnderTest.addTextWidgetsContainerPage()V: Line 2786
   * Goal 4. main.ClassUnderTest.confirmOperationDeleteItemPage()V: Line 289
   * Goal 5. main.ClassUnderTest.deleteLocationWidgetDashboardContainerPage(Lcustom_classes/Id;)V: Line 575
   * Goal 6. main.ClassUnderTest.deleteUserOrFeedWidgetDashboardContainerPage(Lcustom_classes/Id;)V: Line 603
   * Goal 7. main.ClassUnderTest.goToSiteDashboardContainerPage()V: Line 763
   * Goal 8. main.ClassUnderTest.goToVisibilityAddEditTextWidgetContainerPage()V: Line 2498
   * Goal 9. main.ClassUnderTest.goToWidgetsAddEditLinkContainerPage()V: Line 2730
   * Goal 10. main.ClassUnderTest.publishAllPagesAndLinksPagesContainerPage()V: Line 2047
   * Goal 11. main.ClassUnderTest.unpublishAllPagesAndLinksPagesContainerPage()V: Line 2091
   */

  @Test(timeout = 1001000)
  public void test05()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      WidgetLocation widgetLocation0 = WidgetLocation.TRENTO;
      WidgetUnit widgetUnit0 = WidgetUnit.IMPERIAL;
      classUnderTest0.addLocationWidgetDashboardContainerPage(widgetLocation0, widgetUnit0);
      int int0 = 201;
      Id id0 = new Id(int0);
      classUnderTest0.deleteUserOrFeedWidgetDashboardContainerPage(id0);
      classUnderTest0.confirmOperationDeleteItemPage();
      classUnderTest0.deleteLocationWidgetDashboardContainerPage(id0);
      classUnderTest0.goToSiteDashboardContainerPage();
      classUnderTest0.unpublishAllPagesAndLinksPagesContainerPage();
      classUnderTest0.publishAllPagesAndLinksPagesContainerPage();
      classUnderTest0.addLinkPagesContainerPage();
      classUnderTest0.goToWidgetsAddEditLinkContainerPage();
      classUnderTest0.addTextWidgetsContainerPage();
      classUnderTest0.goToVisibilityAddEditTextWidgetContainerPage();
  }

  //Test case number: 6
  /*
   * 17 covered goals:
   * Goal 1. main.ClassUnderTest.addFeedWidgetDashboardContainerPage(Lcustom_classes/WidgetFeedTitle;Lcustom_classes/WidgetFeedUrl;Lcustom_classes/WidgetFeedNumberOfPosts;Lcustom_classes/WidgetFeedPostContent;)V: Line 515
   * Goal 2. main.ClassUnderTest.addLinkPagesContainerPage()V: Line 1706
   * Goal 3. main.ClassUnderTest.addMenuWidgetsContainerPage()V: Line 2772
   * Goal 4. main.ClassUnderTest.addUserAddEditUserContainerPage(Lcustom_classes/Username;Lcustom_classes/Name;Lcustom_classes/Email;Lcustom_classes/UserPassword;Lcustom_classes/UserStatus;)V: Line 1263
   * Goal 5. main.ClassUnderTest.addUserUserListContainerPage()V: Line 812
   * Goal 6. main.ClassUnderTest.goToDashboardAddEditLinkContainerPage()V: Line 2642
   * Goal 7. main.ClassUnderTest.goToEditCurrentUserDashboardContainerPage()V: Line 726
   * Goal 8. main.ClassUnderTest.goToMenuWidgetsContainerPage(Lcustom_classes/WidgetMenus;)V: Line 2971
   * Goal 9. main.ClassUnderTest.goToSiteAddEditUserContainerPage()V: Line 1385
   * Goal 10. main.ClassUnderTest.goToSiteDashboardContainerPage()V: Line 763
   * Goal 11. main.ClassUnderTest.goToSiteUserListContainerPage()V: Line 971
   * Goal 12. main.ClassUnderTest.goToUserListAddEditUserContainerPage()V: Line 1397
   * Goal 13. main.ClassUnderTest.goToUsersWidgetsContainerPage()V: Line 3012
   * Goal 14. main.ClassUnderTest.goToVisibilityAddEditMenuWidgetContainerPage()V: Line 3566
   * Goal 15. main.ClassUnderTest.goToWidgetsPagesContainerPage()V: Line 1982
   * Goal 16. main.ClassUnderTest.goToWidgetsWidgetsContainerPage()V: Line 3024
   * Goal 17. main.ClassUnderTest.moveAllPagesAndLinksToMenuPagesContainerPage(Lcustom_classes/SiteMenus;)V: Line 2000
   */

  @Test(timeout = 1001000)
  public void test06()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      WidgetFeedTitle widgetFeedTitle0 = WidgetFeedTitle.SPORTNEWS;
      WidgetFeedUrl widgetFeedUrl0 = WidgetFeedUrl.SPORT;
      int int0 = (-487);
      WidgetFeedNumberOfPosts widgetFeedNumberOfPosts0 = new WidgetFeedNumberOfPosts(int0);
      WidgetFeedPostContent widgetFeedPostContent0 = WidgetFeedPostContent.DONTSHOW;
      classUnderTest0.addFeedWidgetDashboardContainerPage(widgetFeedTitle0, widgetFeedUrl0, widgetFeedNumberOfPosts0, widgetFeedPostContent0);
      classUnderTest0.goToSiteDashboardContainerPage();
      classUnderTest0.addLinkPagesContainerPage();
      classUnderTest0.goToDashboardAddEditLinkContainerPage();
      classUnderTest0.goToEditCurrentUserDashboardContainerPage();
      classUnderTest0.goToUserListAddEditUserContainerPage();
      classUnderTest0.goToSiteUserListContainerPage();
      classUnderTest0.goToWidgetsPagesContainerPage();
      WidgetMenus widgetMenus0 = WidgetMenus.UNASSIGNED;
      classUnderTest0.goToMenuWidgetsContainerPage(widgetMenus0);
      classUnderTest0.goToWidgetsWidgetsContainerPage();
      classUnderTest0.goToUsersWidgetsContainerPage();
      classUnderTest0.addUserUserListContainerPage();
      Username username0 = Username.ADMIN;
      Name name0 = Name.JOHN;
      Email email0 = Email.ASD;
      UserPassword userPassword0 = UserPassword.ADMIN;
      UserStatus userStatus0 = UserStatus.BLOCKED;
      classUnderTest0.addUserAddEditUserContainerPage(username0, name0, email0, userPassword0, userStatus0);
      classUnderTest0.goToSiteAddEditUserContainerPage();
      SiteMenus siteMenus0 = SiteMenus.MAIN;
      classUnderTest0.moveAllPagesAndLinksToMenuPagesContainerPage(siteMenus0);
      classUnderTest0.goToWidgetsPagesContainerPage();
      classUnderTest0.addMenuWidgetsContainerPage();
      classUnderTest0.goToVisibilityAddEditMenuWidgetContainerPage();
  }

  //Test case number: 7
  /*
   * 19 covered goals:
   * Goal 1. main.ClassUnderTest.addLocationWidgetDashboardContainerPage(Lcustom_classes/WidgetLocation;Lcustom_classes/WidgetUnit;)V: Line 533
   * Goal 2. main.ClassUnderTest.addUserAddEditUserContainerPage(Lcustom_classes/Username;Lcustom_classes/Name;Lcustom_classes/Email;Lcustom_classes/UserPassword;Lcustom_classes/UserStatus;)V: Line 1266
   * Goal 3. main.ClassUnderTest.addUserUserListContainerPage()V: Line 812
   * Goal 4. main.ClassUnderTest.cancelOperationDeleteItemPage()V: Line 252
   * Goal 5. main.ClassUnderTest.closeOperationAddEditUserContainerPage()V: Line 1285
   * Goal 6. main.ClassUnderTest.deleteLocationWidgetDashboardContainerPage(Lcustom_classes/Id;)V: Line 575
   * Goal 7. main.ClassUnderTest.deleteUserOrFeedWidgetDashboardContainerPage(Lcustom_classes/Id;)V: Line 603
   * Goal 8. main.ClassUnderTest.editUserAddEditUserContainerPage(Lcustom_classes/Username;Lcustom_classes/Name;Lcustom_classes/Email;Lcustom_classes/UserPassword;)V: Line 1303
   * Goal 9. main.ClassUnderTest.goToDashboardAddEditUserContainerPage()V: Line 1320
   * Goal 10. main.ClassUnderTest.goToDashboardPagesContainerPage()V: Line 1901
   * Goal 11. main.ClassUnderTest.goToEditCurrentUserDashboardContainerPage()V: Line 726
   * Goal 12. main.ClassUnderTest.goToEditCurrentUserUserListContainerPage()V: Line 919
   * Goal 13. main.ClassUnderTest.goToPermissionsUserSettingsContainerPage()V: Line 1589
   * Goal 14. main.ClassUnderTest.goToSettingsAddEditUserContainerPage()V: Line 1372
   * Goal 15. main.ClassUnderTest.goToSettingsUserListContainerPage()V: Line 958
   * Goal 16. main.ClassUnderTest.goToSiteUserSettingsContainerPage()V: Line 1628
   * Goal 17. main.ClassUnderTest.goToUserListAddEditUserContainerPage()V: Line 1397
   * Goal 18. main.ClassUnderTest.goToUserListPermissionsContainerPage()V: Line 1523
   * Goal 19. main.ClassUnderTest.goToUsersDashboardContainerPage()V: Line 775
   */

  @Test(timeout = 1001000)
  public void test07()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      int int0 = (-988);
      Id id0 = new Id(int0);
      WidgetLocation widgetLocation0 = WidgetLocation.TRENTO;
      WidgetUnit widgetUnit0 = WidgetUnit.METRIC;
      classUnderTest0.addLocationWidgetDashboardContainerPage(widgetLocation0, widgetUnit0);
      classUnderTest0.deleteLocationWidgetDashboardContainerPage(id0);
      classUnderTest0.deleteUserOrFeedWidgetDashboardContainerPage(id0);
      classUnderTest0.cancelOperationDeleteItemPage();
      classUnderTest0.goToEditCurrentUserDashboardContainerPage();
      classUnderTest0.goToUserListAddEditUserContainerPage();
      classUnderTest0.goToEditCurrentUserUserListContainerPage();
      classUnderTest0.closeOperationAddEditUserContainerPage();
      classUnderTest0.goToEditCurrentUserUserListContainerPage();
      classUnderTest0.goToDashboardAddEditUserContainerPage();
      classUnderTest0.goToUsersDashboardContainerPage();
      classUnderTest0.addUserUserListContainerPage();
      Username username0 = Username.FOO;
      Name name0 = Name.JOHN;
      Email email0 = Email.FOO;
      UserPassword userPassword0 = UserPassword.FOO;
      UserStatus userStatus0 = UserStatus.BLOCKED;
      classUnderTest0.addUserAddEditUserContainerPage(username0, name0, email0, userPassword0, userStatus0);
      classUnderTest0.editUserAddEditUserContainerPage(username0, name0, email0, userPassword0);
      classUnderTest0.goToSettingsAddEditUserContainerPage();
      classUnderTest0.goToPermissionsUserSettingsContainerPage();
      classUnderTest0.goToUserListPermissionsContainerPage();
      classUnderTest0.goToSettingsUserListContainerPage();
      classUnderTest0.goToSiteUserSettingsContainerPage();
      classUnderTest0.goToDashboardPagesContainerPage();
  }

  //Test case number: 8
  /*
   * 12 covered goals:
   * Goal 1. main.ClassUnderTest.addFeedWidgetDashboardContainerPage(Lcustom_classes/WidgetFeedTitle;Lcustom_classes/WidgetFeedUrl;Lcustom_classes/WidgetFeedNumberOfPosts;Lcustom_classes/WidgetFeedPostContent;)V: Line 515
   * Goal 2. main.ClassUnderTest.addItemAddEditItemPage()V: Line 396
   * Goal 3. main.ClassUnderTest.addLinkPagesContainerPage()V: Line 1706
   * Goal 4. main.ClassUnderTest.addLocationWidgetDashboardContainerPage(Lcustom_classes/WidgetLocation;Lcustom_classes/WidgetUnit;)V: Line 533
   * Goal 5. main.ClassUnderTest.addMenuPagesContainerPage(Lcustom_classes/SiteMenus;)V: Line 1727
   * Goal 6. main.ClassUnderTest.addUserWidgetDashboardContainerPage(Lcustom_classes/WidgetUserType;Lcustom_classes/WidgetUserDisplay;Lcustom_classes/WidgetTotalUser;Lcustom_classes/WidgetNumberOfUsers;)V: Line 553
   * Goal 7. main.ClassUnderTest.editLocationWidgetDashboardContainerPage(Lcustom_classes/Id;Lcustom_classes/WidgetLocation;Lcustom_classes/WidgetUnit;)V: Line 664
   * Goal 8. main.ClassUnderTest.goToDashboardAddEditLinkContainerPage()V: Line 2642
   * Goal 9. main.ClassUnderTest.goToDashboardDashboardContainerPage()V: Line 713
   * Goal 10. main.ClassUnderTest.goToDashboardUserListContainerPage()V: Line 906
   * Goal 11. main.ClassUnderTest.goToSiteDashboardContainerPage()V: Line 763
   * Goal 12. main.ClassUnderTest.goToUsersPagesContainerPage()V: Line 1970
   */

  @Test(timeout = 1001000)
  public void test08()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      WidgetLocation widgetLocation0 = WidgetLocation.MILANO;
      WidgetUnit widgetUnit0 = WidgetUnit.METRIC;
      classUnderTest0.addLocationWidgetDashboardContainerPage(widgetLocation0, widgetUnit0);
      WidgetUserType widgetUserType0 = WidgetUserType.LOGGEDIN;
      WidgetUserDisplay widgetUserDisplay0 = WidgetUserDisplay.THUMBNAIL;
      WidgetTotalUser widgetTotalUser0 = WidgetTotalUser.SHOW;
      WidgetNumberOfUsers widgetNumberOfUsers0 = WidgetNumberOfUsers.TWENTYFOUR;
      classUnderTest0.addUserWidgetDashboardContainerPage(widgetUserType0, widgetUserDisplay0, widgetTotalUser0, widgetNumberOfUsers0);
      int int0 = (-1643);
      Id id0 = new Id(int0);
      WidgetUserType widgetUserType1 = WidgetUserType.LOGGEDIN;
      WidgetUserDisplay widgetUserDisplay1 = WidgetUserDisplay.LIST;
      WidgetUnit widgetUnit1 = WidgetUnit.IMPERIAL;
      classUnderTest0.addLocationWidgetDashboardContainerPage(widgetLocation0, widgetUnit1);
      classUnderTest0.goToDashboardDashboardContainerPage();
      WidgetUserType widgetUserType2 = WidgetUserType.LOGGEDIN;
      WidgetTotalUser widgetTotalUser1 = WidgetTotalUser.HIDE;
      classUnderTest0.addUserWidgetDashboardContainerPage(widgetUserType2, widgetUserDisplay1, widgetTotalUser1, widgetNumberOfUsers0);
      WidgetUnit widgetUnit2 = WidgetUnit.METRIC;
      classUnderTest0.editLocationWidgetDashboardContainerPage(id0, widgetLocation0, widgetUnit2);
      classUnderTest0.goToSiteDashboardContainerPage();
      SiteMenus siteMenus0 = SiteMenus.SIDE_MENU;
      classUnderTest0.addMenuPagesContainerPage(siteMenus0);
      classUnderTest0.addItemAddEditItemPage();
      classUnderTest0.goToUsersPagesContainerPage();
      classUnderTest0.goToDashboardUserListContainerPage();
      WidgetFeedUrl widgetFeedUrl0 = WidgetFeedUrl.SPORT;
      WidgetFeedNumberOfPosts widgetFeedNumberOfPosts0 = new WidgetFeedNumberOfPosts(int0);
      classUnderTest0.addLocationWidgetDashboardContainerPage(widgetLocation0, widgetUnit0);
      WidgetFeedPostContent widgetFeedPostContent0 = WidgetFeedPostContent.SHOWALLPOSTS;
      classUnderTest0.goToDashboardDashboardContainerPage();
      WidgetUserType widgetUserType3 = WidgetUserType.LASTREGISTERED;
      WidgetTotalUser widgetTotalUser2 = WidgetTotalUser.SHOW;
      WidgetNumberOfUsers widgetNumberOfUsers1 = WidgetNumberOfUsers.TWENTYFOUR;
      classUnderTest0.addUserWidgetDashboardContainerPage(widgetUserType3, widgetUserDisplay1, widgetTotalUser2, widgetNumberOfUsers1);
      WidgetUserDisplay widgetUserDisplay2 = WidgetUserDisplay.LIST;
      WidgetNumberOfUsers widgetNumberOfUsers2 = WidgetNumberOfUsers.SIX;
      classUnderTest0.addUserWidgetDashboardContainerPage(widgetUserType1, widgetUserDisplay2, widgetTotalUser0, widgetNumberOfUsers2);
      WidgetFeedTitle widgetFeedTitle0 = WidgetFeedTitle.WEATHER;
      classUnderTest0.addFeedWidgetDashboardContainerPage(widgetFeedTitle0, widgetFeedUrl0, widgetFeedNumberOfPosts0, widgetFeedPostContent0);
      classUnderTest0.goToSiteDashboardContainerPage();
      classUnderTest0.addLinkPagesContainerPage();
      classUnderTest0.goToDashboardAddEditLinkContainerPage();
  }

  //Test case number: 9
  /*
   * 9 covered goals:
   * Goal 1. main.ClassUnderTest.addUserWidgetDashboardContainerPage(Lcustom_classes/WidgetUserType;Lcustom_classes/WidgetUserDisplay;Lcustom_classes/WidgetTotalUser;Lcustom_classes/WidgetNumberOfUsers;)V: Line 553
   * Goal 2. main.ClassUnderTest.blockUserUserListContainerPage(Lcustom_classes/Id;)V: Line 834
   * Goal 3. main.ClassUnderTest.goToDashboardUserListContainerPage()V: Line 906
   * Goal 4. main.ClassUnderTest.goToEditUserDashboardContainerPage(Lcustom_classes/Id;)V: Line 746
   * Goal 5. main.ClassUnderTest.goToPermissionsUserListContainerPage()V: Line 932
   * Goal 6. main.ClassUnderTest.goToSitePermissionsContainerPage()V: Line 1511
   * Goal 7. main.ClassUnderTest.goToUserListUserListContainerPage()V: Line 983
   * Goal 8. main.ClassUnderTest.goToUsersDashboardContainerPage()V: Line 775
   * Goal 9. main.ClassUnderTest.goToUsersPagesContainerPage()V: Line 1970
   */

  @Test(timeout = 1001000)
  public void test09()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      WidgetUserType widgetUserType0 = WidgetUserType.LOGGEDIN;
      WidgetUserDisplay widgetUserDisplay0 = WidgetUserDisplay.THUMBNAIL;
      WidgetTotalUser widgetTotalUser0 = WidgetTotalUser.HIDE;
      WidgetNumberOfUsers widgetNumberOfUsers0 = WidgetNumberOfUsers.SIX;
      classUnderTest0.addUserWidgetDashboardContainerPage(widgetUserType0, widgetUserDisplay0, widgetTotalUser0, widgetNumberOfUsers0);
      classUnderTest0.goToUsersDashboardContainerPage();
      classUnderTest0.goToUserListUserListContainerPage();
      classUnderTest0.goToPermissionsUserListContainerPage();
      classUnderTest0.goToSitePermissionsContainerPage();
      classUnderTest0.goToUsersPagesContainerPage();
      int int0 = (-780);
      Id id0 = new Id(int0);
      classUnderTest0.blockUserUserListContainerPage(id0);
      classUnderTest0.goToDashboardUserListContainerPage();
      classUnderTest0.goToEditUserDashboardContainerPage(id0);
  }

  //Test case number: 10
  /*
   * 11 covered goals:
   * Goal 1. main.ClassUnderTest.cancelOperationSelectLinkPage()V: Line 30
   * Goal 2. main.ClassUnderTest.changeSettingsUserSettingsContainerPage(Lcustom_classes/RegistrationUserSettings;)V: Line 1550
   * Goal 3. main.ClassUnderTest.giveOrRemoveAllPermissionsToUserRolePermissionsContainerPage(Lcustom_classes/UserRoles;)V: Line 1428
   * Goal 4. main.ClassUnderTest.goToDashboardUserSettingsContainerPage()V: Line 1563
   * Goal 5. main.ClassUnderTest.goToEditCurrentUserDashboardContainerPage()V: Line 726
   * Goal 6. main.ClassUnderTest.goToRolesAddEditUserContainerPage()V: Line 1359
   * Goal 7. main.ClassUnderTest.goToSettingsPermissionsContainerPage()V: Line 1498
   * Goal 8. main.ClassUnderTest.goToSettingsUserSettingsContainerPage()V: Line 1615
   * Goal 9. main.ClassUnderTest.goToSiteDashboardContainerPage()V: Line 763
   * Goal 10. main.ClassUnderTest.goToWidgetsPagesContainerPage()V: Line 1982
   * Goal 11. main.ClassUnderTest.saveSettingsUserSettingsContainerPage()V: Line 1667
   */

  @Test(timeout = 1001000)
  public void test10()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      classUnderTest0.goToEditCurrentUserDashboardContainerPage();
      classUnderTest0.goToRolesAddEditUserContainerPage();
      UserRoles userRoles0 = UserRoles.AUTHENTICATED;
      classUnderTest0.giveOrRemoveAllPermissionsToUserRolePermissionsContainerPage(userRoles0);
      classUnderTest0.goToSettingsPermissionsContainerPage();
      classUnderTest0.goToSettingsUserSettingsContainerPage();
      RegistrationUserSettings registrationUserSettings0 = RegistrationUserSettings.ENABLED_BUT_APPROVAL;
      classUnderTest0.changeSettingsUserSettingsContainerPage(registrationUserSettings0);
      classUnderTest0.cancelOperationSelectLinkPage();
      classUnderTest0.saveSettingsUserSettingsContainerPage();
      classUnderTest0.goToDashboardUserSettingsContainerPage();
      classUnderTest0.goToSiteDashboardContainerPage();
      classUnderTest0.goToWidgetsPagesContainerPage();
  }

  //Test case number: 11
  /*
   * 8 covered goals:
   * Goal 1. main.ClassUnderTest.addLocationWidgetDashboardContainerPage(Lcustom_classes/WidgetLocation;Lcustom_classes/WidgetUnit;)V: Line 533
   * Goal 2. main.ClassUnderTest.addMenuWidgetsContainerPage()V: Line 2772
   * Goal 3. main.ClassUnderTest.closeEditMenuAddEditMenuWidgetContainerPage()V: Line 3478
   * Goal 4. main.ClassUnderTest.goToDashboardDashboardContainerPage()V: Line 713
   * Goal 5. main.ClassUnderTest.goToDashboardWidgetsContainerPage()V: Line 2942
   * Goal 6. main.ClassUnderTest.goToSiteDashboardContainerPage()V: Line 763
   * Goal 7. main.ClassUnderTest.goToWidgetsPagesContainerPage()V: Line 1982
   * Goal 8. main.ClassUnderTest.goToWidgetsWidgetsContainerPage()V: Line 3024
   */

  @Test(timeout = 1001000)
  public void test11()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      WidgetLocation widgetLocation0 = WidgetLocation.GENOA;
      WidgetUnit widgetUnit0 = WidgetUnit.IMPERIAL;
      classUnderTest0.addLocationWidgetDashboardContainerPage(widgetLocation0, widgetUnit0);
      classUnderTest0.goToSiteDashboardContainerPage();
      classUnderTest0.goToWidgetsPagesContainerPage();
      classUnderTest0.addMenuWidgetsContainerPage();
      classUnderTest0.closeEditMenuAddEditMenuWidgetContainerPage();
      classUnderTest0.goToWidgetsWidgetsContainerPage();
      classUnderTest0.goToDashboardWidgetsContainerPage();
      classUnderTest0.goToDashboardDashboardContainerPage();
  }

  //Test case number: 12
  /*
   * 8 covered goals:
   * Goal 1. main.ClassUnderTest.addLocationWidgetDashboardContainerPage(Lcustom_classes/WidgetLocation;Lcustom_classes/WidgetUnit;)V: Line 533
   * Goal 2. main.ClassUnderTest.addPagePagesContainerPage()V: Line 1747
   * Goal 3. main.ClassUnderTest.cancelOperationDeleteItemPage()V: Line 252
   * Goal 4. main.ClassUnderTest.closeEditPageAddEditPageContainerPage()V: Line 2216
   * Goal 5. main.ClassUnderTest.deleteUserOrFeedWidgetDashboardContainerPage(Lcustom_classes/Id;)V: Line 603
   * Goal 6. main.ClassUnderTest.goToDashboardDashboardContainerPage()V: Line 713
   * Goal 7. main.ClassUnderTest.goToPagesPagesContainerPage()V: Line 1946
   * Goal 8. main.ClassUnderTest.goToSiteDashboardContainerPage()V: Line 763
   */

  @Test(timeout = 1001000)
  public void test12()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      int int0 = (-165);
      Id id0 = new Id(int0);
      WidgetLocation widgetLocation0 = WidgetLocation.GENOA;
      WidgetUnit widgetUnit0 = WidgetUnit.METRIC;
      classUnderTest0.addLocationWidgetDashboardContainerPage(widgetLocation0, widgetUnit0);
      classUnderTest0.deleteUserOrFeedWidgetDashboardContainerPage(id0);
      classUnderTest0.cancelOperationDeleteItemPage();
      classUnderTest0.goToDashboardDashboardContainerPage();
      classUnderTest0.goToSiteDashboardContainerPage();
      classUnderTest0.goToPagesPagesContainerPage();
      classUnderTest0.addPagePagesContainerPage();
      classUnderTest0.closeEditPageAddEditPageContainerPage();
  }

  //Test case number: 13
  /*
   * 9 covered goals:
   * Goal 1. main.ClassUnderTest.addLocationWidgetDashboardContainerPage(Lcustom_classes/WidgetLocation;Lcustom_classes/WidgetUnit;)V: Line 533
   * Goal 2. main.ClassUnderTest.confirmOperationDeleteItemPage()V: Line 296
   * Goal 3. main.ClassUnderTest.deleteUserUserListContainerPage(Lcustom_classes/Id;)V: Line 889
   * Goal 4. main.ClassUnderTest.editUserWidgetDashboardContainerPage(Lcustom_classes/Id;Lcustom_classes/WidgetUserType;Lcustom_classes/WidgetUserDisplay;Lcustom_classes/WidgetTotalUser;Lcustom_classes/WidgetNumberOfUsers;)V: Line 696
   * Goal 5. main.ClassUnderTest.goToDashboardDashboardContainerPage()V: Line 713
   * Goal 6. main.ClassUnderTest.goToEditUserDashboardContainerPage(Lcustom_classes/Id;)V: Line 746
   * Goal 7. main.ClassUnderTest.goToSettingsAddEditUserContainerPage()V: Line 1372
   * Goal 8. main.ClassUnderTest.goToSiteUserSettingsContainerPage()V: Line 1628
   * Goal 9. main.ClassUnderTest.goToUsersPagesContainerPage()V: Line 1970
   */

  @Test(timeout = 1001000)
  public void test13()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      int int0 = (-1830);
      Id id0 = new Id(int0);
      WidgetUserType widgetUserType0 = WidgetUserType.LOGGEDIN;
      WidgetUserDisplay widgetUserDisplay0 = WidgetUserDisplay.LIST;
      WidgetTotalUser widgetTotalUser0 = WidgetTotalUser.SHOW;
      WidgetNumberOfUsers widgetNumberOfUsers0 = WidgetNumberOfUsers.TWELVE;
      classUnderTest0.editUserWidgetDashboardContainerPage(id0, widgetUserType0, widgetUserDisplay0, widgetTotalUser0, widgetNumberOfUsers0);
      classUnderTest0.goToDashboardDashboardContainerPage();
      classUnderTest0.goToDashboardDashboardContainerPage();
      classUnderTest0.goToDashboardDashboardContainerPage();
      WidgetLocation widgetLocation0 = WidgetLocation.MILANO;
      WidgetUnit widgetUnit0 = WidgetUnit.METRIC;
      classUnderTest0.addLocationWidgetDashboardContainerPage(widgetLocation0, widgetUnit0);
      int int1 = (-957);
      Id id1 = new Id(int1);
      classUnderTest0.goToEditUserDashboardContainerPage(id1);
      classUnderTest0.goToSettingsAddEditUserContainerPage();
      classUnderTest0.goToSiteUserSettingsContainerPage();
      classUnderTest0.goToUsersPagesContainerPage();
      classUnderTest0.deleteUserUserListContainerPage(id0);
      classUnderTest0.confirmOperationDeleteItemPage();
  }

  //Test case number: 14
  /*
   * 12 covered goals:
   * Goal 1. main.ClassUnderTest.addFeedWidgetDashboardContainerPage(Lcustom_classes/WidgetFeedTitle;Lcustom_classes/WidgetFeedUrl;Lcustom_classes/WidgetFeedNumberOfPosts;Lcustom_classes/WidgetFeedPostContent;)V: Line 515
   * Goal 2. main.ClassUnderTest.addMenuWidgetsContainerPage()V: Line 2772
   * Goal 3. main.ClassUnderTest.cancelOperationDeleteItemPage()V: Line 257
   * Goal 4. main.ClassUnderTest.deleteAdminUserUserListContainerPage(Lcustom_classes/Id;)V: Line 864
   * Goal 5. main.ClassUnderTest.editUserWidgetDashboardContainerPage(Lcustom_classes/Id;Lcustom_classes/WidgetUserType;Lcustom_classes/WidgetUserDisplay;Lcustom_classes/WidgetTotalUser;Lcustom_classes/WidgetNumberOfUsers;)V: Line 696
   * Goal 6. main.ClassUnderTest.goToPermissionsUserListContainerPage()V: Line 932
   * Goal 7. main.ClassUnderTest.goToRolesUserSettingsContainerPage()V: Line 1602
   * Goal 8. main.ClassUnderTest.goToSettingsPermissionsContainerPage()V: Line 1498
   * Goal 9. main.ClassUnderTest.goToSiteDashboardContainerPage()V: Line 763
   * Goal 10. main.ClassUnderTest.goToUserListUserListContainerPage()V: Line 983
   * Goal 11. main.ClassUnderTest.goToUsersAddEditMenuWidgetContainerPage()V: Line 3554
   * Goal 12. main.ClassUnderTest.goToWidgetsPagesContainerPage()V: Line 1982
   */

  @Test(timeout = 1001000)
  public void test14()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      WidgetFeedTitle widgetFeedTitle0 = WidgetFeedTitle.WEATHER;
      WidgetFeedUrl widgetFeedUrl0 = WidgetFeedUrl.SPORT;
      int int0 = 1294;
      WidgetFeedNumberOfPosts widgetFeedNumberOfPosts0 = new WidgetFeedNumberOfPosts(int0);
      WidgetFeedPostContent widgetFeedPostContent0 = WidgetFeedPostContent.SHOWFIRSTPOST;
      classUnderTest0.addFeedWidgetDashboardContainerPage(widgetFeedTitle0, widgetFeedUrl0, widgetFeedNumberOfPosts0, widgetFeedPostContent0);
      int int1 = 1881;
      Id id0 = new Id(int1);
      WidgetUserType widgetUserType0 = WidgetUserType.LASTREGISTERED;
      WidgetUserDisplay widgetUserDisplay0 = WidgetUserDisplay.THUMBNAIL;
      WidgetTotalUser widgetTotalUser0 = WidgetTotalUser.SHOW;
      WidgetNumberOfUsers widgetNumberOfUsers0 = WidgetNumberOfUsers.TWENTYFOUR;
      classUnderTest0.editUserWidgetDashboardContainerPage(id0, widgetUserType0, widgetUserDisplay0, widgetTotalUser0, widgetNumberOfUsers0);
      classUnderTest0.goToSiteDashboardContainerPage();
      classUnderTest0.goToWidgetsPagesContainerPage();
      classUnderTest0.addMenuWidgetsContainerPage();
      classUnderTest0.goToUsersAddEditMenuWidgetContainerPage();
      classUnderTest0.goToUserListUserListContainerPage();
      classUnderTest0.deleteAdminUserUserListContainerPage(id0);
      classUnderTest0.cancelOperationDeleteItemPage();
      classUnderTest0.goToUserListUserListContainerPage();
      classUnderTest0.goToPermissionsUserListContainerPage();
      classUnderTest0.goToSettingsPermissionsContainerPage();
      classUnderTest0.goToRolesUserSettingsContainerPage();
  }

  //Test case number: 15
  /*
   * 11 covered goals:
   * Goal 1. main.ClassUnderTest.addLocationWidgetDashboardContainerPage(Lcustom_classes/WidgetLocation;Lcustom_classes/WidgetUnit;)V: Line 533
   * Goal 2. main.ClassUnderTest.addMenuWidgetsContainerPage()V: Line 2772
   * Goal 3. main.ClassUnderTest.deleteLinkOrPagePagesContainerPage(Lcustom_classes/SiteLinkOrPage;)V: Line 1788
   * Goal 4. main.ClassUnderTest.editPagePagesContainerPage(Lcustom_classes/SitePages;)V: Line 1884
   * Goal 5. main.ClassUnderTest.goToPagesAddEditPageContainerPage()V: Line 2281
   * Goal 6. main.ClassUnderTest.goToPagesPagesContainerPage()V: Line 1946
   * Goal 7. main.ClassUnderTest.goToSiteDashboardContainerPage()V: Line 763
   * Goal 8. main.ClassUnderTest.goToSiteWidgetsContainerPage()V: Line 3000
   * Goal 9. main.ClassUnderTest.goToWidgetsAddEditMenuWidgetContainerPage()V: Line 3579
   * Goal 10. main.ClassUnderTest.goToWidgetsPagesContainerPage()V: Line 1982
   * Goal 11. main.ClassUnderTest.moveAllPagesAndLinksToMenuPagesContainerPage(Lcustom_classes/SiteMenus;)V: Line 2000
   */

  @Test(timeout = 1001000)
  public void test15()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      WidgetLocation widgetLocation0 = WidgetLocation.GENOA;
      WidgetUnit widgetUnit0 = WidgetUnit.IMPERIAL;
      classUnderTest0.addLocationWidgetDashboardContainerPage(widgetLocation0, widgetUnit0);
      classUnderTest0.goToSiteDashboardContainerPage();
      classUnderTest0.goToWidgetsPagesContainerPage();
      classUnderTest0.addMenuWidgetsContainerPage();
      classUnderTest0.goToWidgetsAddEditMenuWidgetContainerPage();
      classUnderTest0.goToSiteWidgetsContainerPage();
      classUnderTest0.goToPagesPagesContainerPage();
      SiteMenus siteMenus0 = SiteMenus.MAIN;
      classUnderTest0.moveAllPagesAndLinksToMenuPagesContainerPage(siteMenus0);
      SitePages sitePages0 = SitePages.HOME;
      classUnderTest0.editPagePagesContainerPage(sitePages0);
      classUnderTest0.goToPagesAddEditPageContainerPage();
      classUnderTest0.deleteLinkOrPagePagesContainerPage(sitePages0);
  }

  //Test case number: 16
  /*
   * 20 covered goals:
   * Goal 1. main.ClassUnderTest.addItemAddEditItemPage()V: Line 396
   * Goal 2. main.ClassUnderTest.addMenuWidgetsContainerPage()V: Line 2772
   * Goal 3. main.ClassUnderTest.cancelOperationAddEditItemPage()V: Line 426
   * Goal 4. main.ClassUnderTest.editMenuPagesContainerPage(Lcustom_classes/SiteMenus;Lcustom_classes/SiteMenus;)V: Line 1833
   * Goal 5. main.ClassUnderTest.goToEditCurrentUserDashboardContainerPage()V: Line 726
   * Goal 6. main.ClassUnderTest.goToPagesWidgetsContainerPage()V: Line 2988
   * Goal 7. main.ClassUnderTest.goToPermissionsPermissionsContainerPage()V: Line 1472
   * Goal 8. main.ClassUnderTest.goToPermissionsUserListContainerPage()V: Line 932
   * Goal 9. main.ClassUnderTest.goToSettingsPermissionsContainerPage()V: Line 1498
   * Goal 10. main.ClassUnderTest.goToSitePagesContainerPage()V: Line 1958
   * Goal 11. main.ClassUnderTest.goToSiteUserSettingsContainerPage()V: Line 1628
   * Goal 12. main.ClassUnderTest.goToSiteWidgetsContainerPage()V: Line 3000
   * Goal 13. main.ClassUnderTest.goToUserListUserListContainerPage()V: Line 983
   * Goal 14. main.ClassUnderTest.goToUsersAddEditMenuWidgetContainerPage()V: Line 3554
   * Goal 15. main.ClassUnderTest.goToUsersAddEditUserContainerPage()V: Line 1409
   * Goal 16. main.ClassUnderTest.goToWidgetsAddEditMenuWidgetContainerPage()V: Line 3579
   * Goal 17. main.ClassUnderTest.goToWidgetsPagesContainerPage()V: Line 1982
   * Goal 18. main.ClassUnderTest.goToWidgetsWidgetsContainerPage()V: Line 3024
   * Goal 19. main.ClassUnderTest.moveAllPagesAndLinksToMenuPagesContainerPage(Lcustom_classes/SiteMenus;)V: Line 2000
   * Goal 20. main.ClassUnderTest.publishAllPagesAndLinksPagesContainerPage()V: Line 2047
   */

  @Test(timeout = 1001000)
  public void test16()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      classUnderTest0.goToEditCurrentUserDashboardContainerPage();
      classUnderTest0.goToUsersAddEditUserContainerPage();
      classUnderTest0.goToUserListUserListContainerPage();
      classUnderTest0.goToPermissionsUserListContainerPage();
      classUnderTest0.goToPermissionsPermissionsContainerPage();
      classUnderTest0.goToPermissionsPermissionsContainerPage();
      classUnderTest0.goToSettingsPermissionsContainerPage();
      classUnderTest0.goToSiteUserSettingsContainerPage();
      SiteMenus siteMenus0 = SiteMenus.SIDE_MENU;
      classUnderTest0.goToWidgetsPagesContainerPage();
      classUnderTest0.goToSiteWidgetsContainerPage();
      SiteMenus siteMenus1 = SiteMenus.MAIN;
      classUnderTest0.editMenuPagesContainerPage(siteMenus1, siteMenus0);
      classUnderTest0.addItemAddEditItemPage();
      classUnderTest0.moveAllPagesAndLinksToMenuPagesContainerPage(siteMenus0);
      classUnderTest0.editMenuPagesContainerPage(siteMenus0, siteMenus1);
      classUnderTest0.cancelOperationAddEditItemPage();
      classUnderTest0.goToWidgetsPagesContainerPage();
      classUnderTest0.addMenuWidgetsContainerPage();
      classUnderTest0.goToWidgetsAddEditMenuWidgetContainerPage();
      classUnderTest0.goToWidgetsWidgetsContainerPage();
      classUnderTest0.goToPagesWidgetsContainerPage();
      classUnderTest0.publishAllPagesAndLinksPagesContainerPage();
      classUnderTest0.goToSitePagesContainerPage();
      classUnderTest0.publishAllPagesAndLinksPagesContainerPage();
      classUnderTest0.goToWidgetsPagesContainerPage();
      classUnderTest0.addMenuWidgetsContainerPage();
      classUnderTest0.goToUsersAddEditMenuWidgetContainerPage();
  }

  //Test case number: 17
  /*
   * 17 covered goals:
   * Goal 1. main.ClassUnderTest.addLinkPagesContainerPage()V: Line 1706
   * Goal 2. main.ClassUnderTest.addLocationWidgetDashboardContainerPage(Lcustom_classes/WidgetLocation;Lcustom_classes/WidgetUnit;)V: Line 533
   * Goal 3. main.ClassUnderTest.addLoginWidgetsContainerPage()V: Line 2758
   * Goal 4. main.ClassUnderTest.closeOperationAddEditUserContainerPage()V: Line 1285
   * Goal 5. main.ClassUnderTest.deleteLocationWidgetDashboardContainerPage(Lcustom_classes/Id;)V: Line 575
   * Goal 6. main.ClassUnderTest.goToDashboardAddEditLoginWidgetContainerPage()V: Line 3214
   * Goal 7. main.ClassUnderTest.goToDashboardUserListContainerPage()V: Line 906
   * Goal 8. main.ClassUnderTest.goToEditCurrentUserDashboardContainerPage()V: Line 726
   * Goal 9. main.ClassUnderTest.goToEditCurrentUserUserListContainerPage()V: Line 919
   * Goal 10. main.ClassUnderTest.goToEditCurrentUserUserSettingsContainerPage()V: Line 1576
   * Goal 11. main.ClassUnderTest.goToRolesAddEditUserContainerPage()V: Line 1359
   * Goal 12. main.ClassUnderTest.goToSettingsUserListContainerPage()V: Line 958
   * Goal 13. main.ClassUnderTest.goToSiteDashboardContainerPage()V: Line 763
   * Goal 14. main.ClassUnderTest.goToUserListAddEditUserContainerPage()V: Line 1397
   * Goal 15. main.ClassUnderTest.goToUsersDashboardContainerPage()V: Line 775
   * Goal 16. main.ClassUnderTest.goToUsersUserListContainerPage()V: Line 995
   * Goal 17. main.ClassUnderTest.goToWidgetsAddEditLinkContainerPage()V: Line 2730
   */

  @Test(timeout = 1001000)
  public void test17()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      int int0 = (-988);
      Id id0 = new Id(int0);
      WidgetLocation widgetLocation0 = WidgetLocation.TRENTO;
      WidgetUnit widgetUnit0 = WidgetUnit.METRIC;
      classUnderTest0.addLocationWidgetDashboardContainerPage(widgetLocation0, widgetUnit0);
      classUnderTest0.deleteLocationWidgetDashboardContainerPage(id0);
      classUnderTest0.goToEditCurrentUserDashboardContainerPage();
      classUnderTest0.goToUserListAddEditUserContainerPage();
      classUnderTest0.goToEditCurrentUserUserListContainerPage();
      classUnderTest0.closeOperationAddEditUserContainerPage();
      classUnderTest0.goToUsersUserListContainerPage();
      classUnderTest0.goToDashboardUserListContainerPage();
      classUnderTest0.goToSiteDashboardContainerPage();
      classUnderTest0.addLinkPagesContainerPage();
      classUnderTest0.goToWidgetsAddEditLinkContainerPage();
      classUnderTest0.addLoginWidgetsContainerPage();
      classUnderTest0.goToDashboardAddEditLoginWidgetContainerPage();
      classUnderTest0.goToUsersDashboardContainerPage();
      classUnderTest0.goToSettingsUserListContainerPage();
      classUnderTest0.goToEditCurrentUserUserSettingsContainerPage();
      classUnderTest0.goToRolesAddEditUserContainerPage();
  }

  //Test case number: 18
  /*
   * 16 covered goals:
   * Goal 1. main.ClassUnderTest.addFeedWidgetDashboardContainerPage(Lcustom_classes/WidgetFeedTitle;Lcustom_classes/WidgetFeedUrl;Lcustom_classes/WidgetFeedNumberOfPosts;Lcustom_classes/WidgetFeedPostContent;)V: Line 515
   * Goal 2. main.ClassUnderTest.addLinkPagesContainerPage()V: Line 1706
   * Goal 3. main.ClassUnderTest.editLocationWidgetDashboardContainerPage(Lcustom_classes/Id;Lcustom_classes/WidgetLocation;Lcustom_classes/WidgetUnit;)V: Line 664
   * Goal 4. main.ClassUnderTest.editUserAddEditUserContainerPage(Lcustom_classes/Username;Lcustom_classes/Name;Lcustom_classes/Email;Lcustom_classes/UserPassword;)V: Line 1303
   * Goal 5. main.ClassUnderTest.goToDashboardUserListContainerPage()V: Line 906
   * Goal 6. main.ClassUnderTest.goToEditCurrentUserAddEditLinkContainerPage()V: Line 2655
   * Goal 7. main.ClassUnderTest.goToEditCurrentUserDashboardContainerPage()V: Line 726
   * Goal 8. main.ClassUnderTest.goToEditCurrentUserUserListContainerPage()V: Line 919
   * Goal 9. main.ClassUnderTest.goToPermissionsAddEditUserContainerPage()V: Line 1346
   * Goal 10. main.ClassUnderTest.goToRolesAddEditUserContainerPage()V: Line 1359
   * Goal 11. main.ClassUnderTest.goToSiteAddEditUserContainerPage()V: Line 1385
   * Goal 12. main.ClassUnderTest.goToSiteUserListContainerPage()V: Line 971
   * Goal 13. main.ClassUnderTest.goToUserListAddEditUserContainerPage()V: Line 1397
   * Goal 14. main.ClassUnderTest.goToUserListPermissionsContainerPage()V: Line 1523
   * Goal 15. main.ClassUnderTest.goToUsersPagesContainerPage()V: Line 1970
   * Goal 16. main.ClassUnderTest.goToUsersUserListContainerPage()V: Line 995
   */

  @Test(timeout = 1001000)
  public void test18()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      WidgetFeedTitle widgetFeedTitle0 = WidgetFeedTitle.PAGEKITNEWS;
      WidgetFeedUrl widgetFeedUrl0 = WidgetFeedUrl.WEATHER;
      int int0 = (-1718);
      WidgetFeedNumberOfPosts widgetFeedNumberOfPosts0 = new WidgetFeedNumberOfPosts(int0);
      WidgetFeedPostContent widgetFeedPostContent0 = WidgetFeedPostContent.SHOWALLPOSTS;
      classUnderTest0.addFeedWidgetDashboardContainerPage(widgetFeedTitle0, widgetFeedUrl0, widgetFeedNumberOfPosts0, widgetFeedPostContent0);
      int int1 = 545;
      Id id0 = new Id(int1);
      WidgetLocation widgetLocation0 = WidgetLocation.TRENTO;
      WidgetUnit widgetUnit0 = WidgetUnit.IMPERIAL;
      classUnderTest0.editLocationWidgetDashboardContainerPage(id0, widgetLocation0, widgetUnit0);
      classUnderTest0.goToEditCurrentUserDashboardContainerPage();
      Username username0 = Username.FOO;
      Name name0 = Name.JOHN;
      Email email0 = Email.ASD;
      UserPassword userPassword0 = UserPassword.ADMIN;
      classUnderTest0.editUserAddEditUserContainerPage(username0, name0, email0, userPassword0);
      classUnderTest0.goToPermissionsAddEditUserContainerPage();
      classUnderTest0.goToUserListPermissionsContainerPage();
      classUnderTest0.goToDashboardUserListContainerPage();
      classUnderTest0.goToEditCurrentUserDashboardContainerPage();
      classUnderTest0.goToSiteAddEditUserContainerPage();
      classUnderTest0.addLinkPagesContainerPage();
      classUnderTest0.goToEditCurrentUserAddEditLinkContainerPage();
      classUnderTest0.goToUserListAddEditUserContainerPage();
      classUnderTest0.goToSiteUserListContainerPage();
      classUnderTest0.goToUsersPagesContainerPage();
      classUnderTest0.goToUsersUserListContainerPage();
      classUnderTest0.goToEditCurrentUserUserListContainerPage();
      classUnderTest0.goToRolesAddEditUserContainerPage();
  }

  //Test case number: 19
  /*
   * 17 covered goals:
   * Goal 1. main.ClassUnderTest.addLocationWidgetDashboardContainerPage(Lcustom_classes/WidgetLocation;Lcustom_classes/WidgetUnit;)V: Line 533
   * Goal 2. main.ClassUnderTest.addPagePagesContainerPage()V: Line 1747
   * Goal 3. main.ClassUnderTest.changeSettingsUserSettingsContainerPage(Lcustom_classes/RegistrationUserSettings;)V: Line 1550
   * Goal 4. main.ClassUnderTest.goToDashboardAddEditUserContainerPage()V: Line 1320
   * Goal 5. main.ClassUnderTest.goToDashboardPagesContainerPage()V: Line 1901
   * Goal 6. main.ClassUnderTest.goToEditCurrentUserAddEditUserContainerPage()V: Line 1333
   * Goal 7. main.ClassUnderTest.goToEditCurrentUserDashboardContainerPage()V: Line 726
   * Goal 8. main.ClassUnderTest.goToEditCurrentUserPermissionsContainerPage()V: Line 1459
   * Goal 9. main.ClassUnderTest.goToPagesAddEditPageContainerPage()V: Line 2281
   * Goal 10. main.ClassUnderTest.goToPagesPagesContainerPage()V: Line 1946
   * Goal 11. main.ClassUnderTest.goToRolesAddEditUserContainerPage()V: Line 1359
   * Goal 12. main.ClassUnderTest.goToRolesPermissionsContainerPage()V: Line 1485
   * Goal 13. main.ClassUnderTest.goToRolesUserListContainerPage()V: Line 945
   * Goal 14. main.ClassUnderTest.goToSettingsAddEditUserContainerPage()V: Line 1372
   * Goal 15. main.ClassUnderTest.goToSiteDashboardContainerPage()V: Line 763
   * Goal 16. main.ClassUnderTest.goToUsersDashboardContainerPage()V: Line 775
   * Goal 17. main.ClassUnderTest.selectLinkPageSelectLinkPage(Lcustom_classes/Extension;Lcustom_classes/SitePages;)V: Line 71
   */

  @Test(timeout = 1001000)
  public void test19()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      classUnderTest0.goToSiteDashboardContainerPage();
      classUnderTest0.addPagePagesContainerPage();
      classUnderTest0.goToPagesAddEditPageContainerPage();
      classUnderTest0.goToPagesPagesContainerPage();
      classUnderTest0.goToDashboardPagesContainerPage();
      WidgetLocation widgetLocation0 = WidgetLocation.TRENTO;
      WidgetUnit widgetUnit0 = WidgetUnit.IMPERIAL;
      classUnderTest0.addLocationWidgetDashboardContainerPage(widgetLocation0, widgetUnit0);
      classUnderTest0.goToUsersDashboardContainerPage();
      classUnderTest0.goToRolesUserListContainerPage();
      classUnderTest0.goToRolesPermissionsContainerPage();
      classUnderTest0.goToEditCurrentUserPermissionsContainerPage();
      classUnderTest0.goToDashboardAddEditUserContainerPage();
      classUnderTest0.goToEditCurrentUserDashboardContainerPage();
      classUnderTest0.goToRolesAddEditUserContainerPage();
      classUnderTest0.goToEditCurrentUserPermissionsContainerPage();
      classUnderTest0.goToEditCurrentUserAddEditUserContainerPage();
      classUnderTest0.goToSettingsAddEditUserContainerPage();
      RegistrationUserSettings registrationUserSettings0 = RegistrationUserSettings.ENABLED;
      classUnderTest0.changeSettingsUserSettingsContainerPage(registrationUserSettings0);
      Extension extension0 = Extension.PAGE;
      SitePages sitePages0 = SitePages.HOME;
      classUnderTest0.selectLinkPageSelectLinkPage(extension0, sitePages0);
  }

  //Test case number: 20
  /*
   * 17 covered goals:
   * Goal 1. main.ClassUnderTest.activateUserUserListContainerPage(Lcustom_classes/Id;)V: Line 793
   * Goal 2. main.ClassUnderTest.addLinkPagesContainerPage()V: Line 1706
   * Goal 3. main.ClassUnderTest.addMenuWidgetsContainerPage()V: Line 2772
   * Goal 4. main.ClassUnderTest.addPagePagesContainerPage()V: Line 1747
   * Goal 5. main.ClassUnderTest.goToEditCurrentUserAddEditUserContainerPage()V: Line 1333
   * Goal 6. main.ClassUnderTest.goToEditCurrentUserPagesContainerPage()V: Line 1914
   * Goal 7. main.ClassUnderTest.goToMenuPagesContainerPage(Lcustom_classes/SiteMenus;)V: Line 1929
   * Goal 8. main.ClassUnderTest.goToPagesAddEditMenuWidgetContainerPage()V: Line 3517
   * Goal 9. main.ClassUnderTest.goToSiteAddEditLinkContainerPage()V: Line 2706
   * Goal 10. main.ClassUnderTest.goToSiteAddEditPageContainerPage()V: Line 2293
   * Goal 11. main.ClassUnderTest.goToSiteDashboardContainerPage()V: Line 763
   * Goal 12. main.ClassUnderTest.goToSitePagesContainerPage()V: Line 1958
   * Goal 13. main.ClassUnderTest.goToSiteUserListContainerPage()V: Line 971
   * Goal 14. main.ClassUnderTest.goToUsersAddEditPageContainerPage()V: Line 2305
   * Goal 15. main.ClassUnderTest.goToUsersPagesContainerPage()V: Line 1970
   * Goal 16. main.ClassUnderTest.goToWidgetsPagesContainerPage()V: Line 1982
   * Goal 17. main.ClassUnderTest.publishAllPagesAndLinksPagesContainerPage()V: Line 2047
   */

  @Test(timeout = 1001000)
  public void test20()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      int int0 = 1251;
      Id id0 = new Id(int0);
      classUnderTest0.goToSiteDashboardContainerPage();
      SiteMenus siteMenus0 = SiteMenus.NOT_LINKED;
      classUnderTest0.goToUsersPagesContainerPage();
      classUnderTest0.goToSiteUserListContainerPage();
      classUnderTest0.goToSitePagesContainerPage();
      classUnderTest0.publishAllPagesAndLinksPagesContainerPage();
      classUnderTest0.addPagePagesContainerPage();
      classUnderTest0.goToSiteAddEditPageContainerPage();
      classUnderTest0.addLinkPagesContainerPage();
      classUnderTest0.goToSiteAddEditLinkContainerPage();
      classUnderTest0.goToWidgetsPagesContainerPage();
      classUnderTest0.addMenuWidgetsContainerPage();
      classUnderTest0.goToPagesAddEditMenuWidgetContainerPage();
      classUnderTest0.goToMenuPagesContainerPage(siteMenus0);
      classUnderTest0.addPagePagesContainerPage();
      classUnderTest0.goToUsersAddEditPageContainerPage();
      classUnderTest0.activateUserUserListContainerPage(id0);
      classUnderTest0.goToSiteUserListContainerPage();
      classUnderTest0.goToEditCurrentUserPagesContainerPage();
      classUnderTest0.goToEditCurrentUserAddEditUserContainerPage();
  }

  //Test case number: 21
  /*
   * 14 covered goals:
   * Goal 1. main.ClassUnderTest.addLocationWidgetDashboardContainerPage(Lcustom_classes/WidgetLocation;Lcustom_classes/WidgetUnit;)V: Line 533
   * Goal 2. main.ClassUnderTest.addMenuWidgetsContainerPage()V: Line 2772
   * Goal 3. main.ClassUnderTest.addPagePagesContainerPage()V: Line 1747
   * Goal 4. main.ClassUnderTest.goToEditCurrentUserPermissionsContainerPage()V: Line 1459
   * Goal 5. main.ClassUnderTest.goToMetaAddEditPageContainerPage()V: Line 2268
   * Goal 6. main.ClassUnderTest.goToPagesAddEditMenuWidgetContainerPage()V: Line 3517
   * Goal 7. main.ClassUnderTest.goToPagesAddEditPageContainerPage()V: Line 2281
   * Goal 8. main.ClassUnderTest.goToPermissionsUserListContainerPage()V: Line 932
   * Goal 9. main.ClassUnderTest.goToRolesAddEditUserContainerPage()V: Line 1359
   * Goal 10. main.ClassUnderTest.goToSiteAddEditMenuWidgetContainerPage()V: Line 3542
   * Goal 11. main.ClassUnderTest.goToSiteDashboardContainerPage()V: Line 763
   * Goal 12. main.ClassUnderTest.goToUserListUserListContainerPage()V: Line 983
   * Goal 13. main.ClassUnderTest.goToUsersWidgetsContainerPage()V: Line 3012
   * Goal 14. main.ClassUnderTest.goToWidgetsPagesContainerPage()V: Line 1982
   */

  @Test(timeout = 1001000)
  public void test21()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      WidgetLocation widgetLocation0 = WidgetLocation.GENOA;
      WidgetUnit widgetUnit0 = WidgetUnit.IMPERIAL;
      classUnderTest0.addLocationWidgetDashboardContainerPage(widgetLocation0, widgetUnit0);
      classUnderTest0.goToSiteDashboardContainerPage();
      classUnderTest0.goToWidgetsPagesContainerPage();
      classUnderTest0.addMenuWidgetsContainerPage();
      classUnderTest0.goToSiteAddEditMenuWidgetContainerPage();
      classUnderTest0.addPagePagesContainerPage();
      classUnderTest0.goToMetaAddEditPageContainerPage();
      classUnderTest0.goToPagesAddEditPageContainerPage();
      classUnderTest0.goToWidgetsPagesContainerPage();
      classUnderTest0.addMenuWidgetsContainerPage();
      classUnderTest0.goToPagesAddEditMenuWidgetContainerPage();
      classUnderTest0.goToWidgetsPagesContainerPage();
      classUnderTest0.goToUsersWidgetsContainerPage();
      classUnderTest0.goToUserListUserListContainerPage();
      classUnderTest0.goToUserListUserListContainerPage();
      classUnderTest0.goToPermissionsUserListContainerPage();
      classUnderTest0.goToEditCurrentUserPermissionsContainerPage();
      classUnderTest0.goToRolesAddEditUserContainerPage();
  }

  //Test case number: 22
  /*
   * 13 covered goals:
   * Goal 1. main.ClassUnderTest.cancelOperationDeleteItemPage()V: Line 257
   * Goal 2. main.ClassUnderTest.deleteAllPagesAndLinksPagesContainerPage()V: Line 1767
   * Goal 3. main.ClassUnderTest.deleteUserUserListContainerPage(Lcustom_classes/Id;)V: Line 889
   * Goal 4. main.ClassUnderTest.goToEditCurrentUserDashboardContainerPage()V: Line 726
   * Goal 5. main.ClassUnderTest.goToEditCurrentUserUserListContainerPage()V: Line 919
   * Goal 6. main.ClassUnderTest.goToPagesPagesContainerPage()V: Line 1946
   * Goal 7. main.ClassUnderTest.goToSiteAddEditUserContainerPage()V: Line 1385
   * Goal 8. main.ClassUnderTest.goToSitePagesContainerPage()V: Line 1958
   * Goal 9. main.ClassUnderTest.goToSiteUserListContainerPage()V: Line 971
   * Goal 10. main.ClassUnderTest.goToUserListAddEditUserContainerPage()V: Line 1397
   * Goal 11. main.ClassUnderTest.goToUsersPagesContainerPage()V: Line 1970
   * Goal 12. main.ClassUnderTest.goToUsersUserListContainerPage()V: Line 995
   * Goal 13. main.ClassUnderTest.moveLinkOrPageToMenuPagesContainerPage(Lcustom_classes/SiteLinkOrPage;Lcustom_classes/SiteMenus;)V: Line 2025
   */

  @Test(timeout = 1001000)
  public void test22()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      classUnderTest0.goToEditCurrentUserDashboardContainerPage();
      classUnderTest0.goToUserListAddEditUserContainerPage();
      classUnderTest0.goToEditCurrentUserUserListContainerPage();
      classUnderTest0.goToSiteAddEditUserContainerPage();
      classUnderTest0.goToUsersPagesContainerPage();
      int int0 = 999;
      Id id0 = new Id(int0);
      classUnderTest0.deleteUserUserListContainerPage(id0);
      classUnderTest0.cancelOperationDeleteItemPage();
      SitePages sitePages0 = SitePages.HOME;
      SiteMenus siteMenus0 = SiteMenus.NOT_LINKED;
      classUnderTest0.goToUsersUserListContainerPage();
      classUnderTest0.goToSiteUserListContainerPage();
      classUnderTest0.moveLinkOrPageToMenuPagesContainerPage(sitePages0, siteMenus0);
      classUnderTest0.goToSitePagesContainerPage();
      classUnderTest0.deleteAllPagesAndLinksPagesContainerPage();
      classUnderTest0.goToPagesPagesContainerPage();
  }

  //Test case number: 23
  /*
   * 13 covered goals:
   * Goal 1. main.ClassUnderTest.addExistingMenuPagesContainerPage(Lcustom_classes/SiteMenus;)V: Line 1686
   * Goal 2. main.ClassUnderTest.addLocationWidgetDashboardContainerPage(Lcustom_classes/WidgetLocation;Lcustom_classes/WidgetUnit;)V: Line 533
   * Goal 3. main.ClassUnderTest.cancelOperationAddEditItemPage()V: Line 426
   * Goal 4. main.ClassUnderTest.cancelOperationDeleteItemPage()V: Line 252
   * Goal 5. main.ClassUnderTest.changeSettingsUserSettingsContainerPage(Lcustom_classes/RegistrationUserSettings;)V: Line 1550
   * Goal 6. main.ClassUnderTest.deleteUserOrFeedWidgetDashboardContainerPage(Lcustom_classes/Id;)V: Line 603
   * Goal 7. main.ClassUnderTest.goToDashboardUserListContainerPage()V: Line 906
   * Goal 8. main.ClassUnderTest.goToEditCurrentUserPagesContainerPage()V: Line 1914
   * Goal 9. main.ClassUnderTest.goToPermissionsAddEditUserContainerPage()V: Line 1346
   * Goal 10. main.ClassUnderTest.goToSettingsPermissionsContainerPage()V: Line 1498
   * Goal 11. main.ClassUnderTest.goToSiteDashboardContainerPage()V: Line 763
   * Goal 12. main.ClassUnderTest.goToUsersPagesContainerPage()V: Line 1970
   * Goal 13. main.ClassUnderTest.unpublishLinkOrPagePagesContainerPage(Lcustom_classes/SiteLinkOrPage;)V: Line 2113
   */

  @Test(timeout = 1001000)
  public void test23()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      int int0 = 1839;
      Id id0 = new Id(int0);
      classUnderTest0.deleteUserOrFeedWidgetDashboardContainerPage(id0);
      classUnderTest0.cancelOperationDeleteItemPage();
      SiteMenus siteMenus0 = SiteMenus.MAIN;
      classUnderTest0.goToSiteDashboardContainerPage();
      classUnderTest0.goToUsersPagesContainerPage();
      classUnderTest0.goToDashboardUserListContainerPage();
      WidgetLocation widgetLocation0 = WidgetLocation.GENOA;
      WidgetUnit widgetUnit0 = WidgetUnit.METRIC;
      classUnderTest0.addLocationWidgetDashboardContainerPage(widgetLocation0, widgetUnit0);
      classUnderTest0.goToSiteDashboardContainerPage();
      SitePages sitePages0 = SitePages.HOME;
      classUnderTest0.unpublishLinkOrPagePagesContainerPage(sitePages0);
      classUnderTest0.addExistingMenuPagesContainerPage(siteMenus0);
      classUnderTest0.cancelOperationAddEditItemPage();
      classUnderTest0.goToEditCurrentUserPagesContainerPage();
      classUnderTest0.goToPermissionsAddEditUserContainerPage();
      classUnderTest0.goToSettingsPermissionsContainerPage();
      RegistrationUserSettings registrationUserSettings0 = RegistrationUserSettings.DISABLED;
      classUnderTest0.changeSettingsUserSettingsContainerPage(registrationUserSettings0);
  }

  //Test case number: 24
  /*
   * 6 covered goals:
   * Goal 1. main.ClassUnderTest.changeSettingsUserSettingsContainerPage(Lcustom_classes/RegistrationUserSettings;)V: Line 1550
   * Goal 2. main.ClassUnderTest.goToPermissionsPermissionsContainerPage()V: Line 1472
   * Goal 3. main.ClassUnderTest.goToPermissionsUserListContainerPage()V: Line 932
   * Goal 4. main.ClassUnderTest.goToSettingsPermissionsContainerPage()V: Line 1498
   * Goal 5. main.ClassUnderTest.goToUsersDashboardContainerPage()V: Line 775
   * Goal 6. main.ClassUnderTest.updateSelectLinkPage()V: Line 203
   */

  @Test(timeout = 1001000)
  public void test24()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      classUnderTest0.goToUsersDashboardContainerPage();
      classUnderTest0.goToPermissionsUserListContainerPage();
      classUnderTest0.goToPermissionsPermissionsContainerPage();
      classUnderTest0.goToSettingsPermissionsContainerPage();
      RegistrationUserSettings registrationUserSettings0 = RegistrationUserSettings.DISABLED;
      classUnderTest0.changeSettingsUserSettingsContainerPage(registrationUserSettings0);
      classUnderTest0.updateSelectLinkPage();
  }
}
