/*
 * This file was automatically generated by EvoSuite
 * Fri May 08 10:48:59 GMT 2020
 */

package main;

import org.junit.Test;
import static org.junit.Assert.*;
import custom_classes.Email;
import custom_classes.HTMLSnippets;
import custom_classes.HideInMenu;
import custom_classes.Id;
import custom_classes.Name;
import custom_classes.PageLinkStatus;
import custom_classes.RegistrationUserSettings;
import custom_classes.SiteMenus;
import custom_classes.SitePages;
import custom_classes.UserPassword;
import custom_classes.UserRoles;
import custom_classes.UserStatus;
import custom_classes.Username;
import custom_classes.WidgetFeedNumberOfPosts;
import custom_classes.WidgetFeedPostContent;
import custom_classes.WidgetFeedTitle;
import custom_classes.WidgetFeedUrl;
import custom_classes.WidgetLocation;
import custom_classes.WidgetMenus;
import custom_classes.WidgetNumberOfUsers;
import custom_classes.WidgetTotalUser;
import custom_classes.WidgetUnit;
import custom_classes.WidgetUserDisplay;
import custom_classes.WidgetUserType;
import main.ClassUnderTest;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, resetStaticState = true) 
public class ClassUnderTest_ESTest extends ClassUnderTest_ESTest_scaffolding {

  //Test case number: 0
  /*
   * 11 covered goals:
   * Goal 1. main.ClassUnderTest.activateUserUserListContainerPage(Lcustom_classes/Id;)V: Line 793
   * Goal 2. main.ClassUnderTest.addFeedWidgetDashboardContainerPage(Lcustom_classes/WidgetFeedTitle;Lcustom_classes/WidgetFeedUrl;Lcustom_classes/WidgetFeedNumberOfPosts;Lcustom_classes/WidgetFeedPostContent;)V: Line 515
   * Goal 3. main.ClassUnderTest.addLocationWidgetDashboardContainerPage(Lcustom_classes/WidgetLocation;Lcustom_classes/WidgetUnit;)V: Line 533
   * Goal 4. main.ClassUnderTest.cancelOperationDeleteItemPage()V: Line 257
   * Goal 5. main.ClassUnderTest.deleteUserUserListContainerPage(Lcustom_classes/Id;)V: Line 889
   * Goal 6. main.ClassUnderTest.goToDashboardDashboardContainerPage()V: Line 713
   * Goal 7. main.ClassUnderTest.goToDashboardUserListContainerPage()V: Line 906
   * Goal 8. main.ClassUnderTest.goToEditCurrentUserDashboardContainerPage()V: Line 726
   * Goal 9. main.ClassUnderTest.goToSettingsAddEditUserContainerPage()V: Line 1372
   * Goal 10. main.ClassUnderTest.goToUsersDashboardContainerPage()V: Line 775
   * Goal 11. main.ClassUnderTest.goToUsersUserSettingsContainerPage()V: Line 1652
   */

  @Test(timeout = 1001000)
  public void test00()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      int int0 = (-3144);
      Id id0 = new Id(int0);
      WidgetLocation widgetLocation0 = WidgetLocation.TRENTO;
      WidgetUnit widgetUnit0 = WidgetUnit.METRIC;
      WidgetFeedTitle widgetFeedTitle0 = WidgetFeedTitle.WEATHER;
      WidgetFeedUrl widgetFeedUrl0 = WidgetFeedUrl.WEATHER;
      int int1 = 592;
      WidgetFeedNumberOfPosts widgetFeedNumberOfPosts0 = new WidgetFeedNumberOfPosts(int1);
      WidgetFeedPostContent widgetFeedPostContent0 = WidgetFeedPostContent.SHOWALLPOSTS;
      classUnderTest0.addFeedWidgetDashboardContainerPage(widgetFeedTitle0, widgetFeedUrl0, widgetFeedNumberOfPosts0, widgetFeedPostContent0);
      WidgetFeedPostContent widgetFeedPostContent1 = WidgetFeedPostContent.SHOWALLPOSTS;
      classUnderTest0.addFeedWidgetDashboardContainerPage(widgetFeedTitle0, widgetFeedUrl0, widgetFeedNumberOfPosts0, widgetFeedPostContent1);
      classUnderTest0.goToEditCurrentUserDashboardContainerPage();
      classUnderTest0.goToSettingsAddEditUserContainerPage();
      classUnderTest0.goToUsersUserSettingsContainerPage();
      classUnderTest0.activateUserUserListContainerPage(id0);
      classUnderTest0.goToDashboardUserListContainerPage();
      WidgetFeedTitle widgetFeedTitle1 = WidgetFeedTitle.SPORTNEWS;
      WidgetFeedUrl widgetFeedUrl1 = WidgetFeedUrl.SPORT;
      WidgetFeedPostContent widgetFeedPostContent2 = WidgetFeedPostContent.DONTSHOW;
      classUnderTest0.addFeedWidgetDashboardContainerPage(widgetFeedTitle1, widgetFeedUrl1, widgetFeedNumberOfPosts0, widgetFeedPostContent2);
      classUnderTest0.goToDashboardDashboardContainerPage();
      classUnderTest0.addLocationWidgetDashboardContainerPage(widgetLocation0, widgetUnit0);
      classUnderTest0.goToUsersDashboardContainerPage();
      classUnderTest0.deleteUserUserListContainerPage(id0);
      classUnderTest0.cancelOperationDeleteItemPage();
  }

  //Test case number: 1
  /*
   * 30 covered goals:
   * Goal 1. main.ClassUnderTest.addEditPageAddEditPageContainerPage(Lcustom_classes/SitePages;Lcustom_classes/HTMLSnippets;Lcustom_classes/PageLinkStatus;Lcustom_classes/HideInMenu;)V: Line 2166
   * Goal 2. main.ClassUnderTest.addFeedWidgetDashboardContainerPage(Lcustom_classes/WidgetFeedTitle;Lcustom_classes/WidgetFeedUrl;Lcustom_classes/WidgetFeedNumberOfPosts;Lcustom_classes/WidgetFeedPostContent;)V: Line 515
   * Goal 3. main.ClassUnderTest.addLinkPagesContainerPage()V: Line 1706
   * Goal 4. main.ClassUnderTest.addPagePagesContainerPage()V: Line 1747
   * Goal 5. main.ClassUnderTest.addUserUserListContainerPage()V: Line 812
   * Goal 6. main.ClassUnderTest.blockUserUserListContainerPage(Lcustom_classes/Id;)V: Line 834
   * Goal 7. main.ClassUnderTest.cancelOperationDeleteItemPage()V: Line 252
   * Goal 8. main.ClassUnderTest.cancelOperationDeleteItemPage()V: Line 257
   * Goal 9. main.ClassUnderTest.closeOperationAddEditUserContainerPage()V: Line 1285
   * Goal 10. main.ClassUnderTest.confirmOperationDeleteItemPage()V: Line 289
   * Goal 11. main.ClassUnderTest.deleteLocationWidgetDashboardContainerPage(Lcustom_classes/Id;)V: Line 575
   * Goal 12. main.ClassUnderTest.deleteUserOrFeedWidgetDashboardContainerPage(Lcustom_classes/Id;)V: Line 603
   * Goal 13. main.ClassUnderTest.deleteUserUserListContainerPage(Lcustom_classes/Id;)V: Line 889
   * Goal 14. main.ClassUnderTest.editLocationWidgetDashboardContainerPage(Lcustom_classes/Id;Lcustom_classes/WidgetLocation;Lcustom_classes/WidgetUnit;)V: Line 664
   * Goal 15. main.ClassUnderTest.editUserAddEditUserContainerPage(Lcustom_classes/Username;Lcustom_classes/Name;Lcustom_classes/Email;Lcustom_classes/UserPassword;)V: Line 1303
   * Goal 16. main.ClassUnderTest.editUserWidgetDashboardContainerPage(Lcustom_classes/Id;Lcustom_classes/WidgetUserType;Lcustom_classes/WidgetUserDisplay;Lcustom_classes/WidgetTotalUser;Lcustom_classes/WidgetNumberOfUsers;)V: Line 696
   * Goal 17. main.ClassUnderTest.goToDashboardAddEditUserContainerPage()V: Line 1320
   * Goal 18. main.ClassUnderTest.goToDashboardDashboardContainerPage()V: Line 713
   * Goal 19. main.ClassUnderTest.goToDashboardUserListContainerPage()V: Line 906
   * Goal 20. main.ClassUnderTest.goToEditCurrentUserDashboardContainerPage()V: Line 726
   * Goal 21. main.ClassUnderTest.goToEditCurrentUserUserListContainerPage()V: Line 919
   * Goal 22. main.ClassUnderTest.goToRolesAddEditUserContainerPage()V: Line 1359
   * Goal 23. main.ClassUnderTest.goToSettingsAddEditLinkContainerPage()V: Line 2693
   * Goal 24. main.ClassUnderTest.goToSiteDashboardContainerPage()V: Line 763
   * Goal 25. main.ClassUnderTest.goToSitePagesContainerPage()V: Line 1958
   * Goal 26. main.ClassUnderTest.goToSitePermissionsContainerPage()V: Line 1511
   * Goal 27. main.ClassUnderTest.goToUsersAddEditLinkContainerPage()V: Line 2718
   * Goal 28. main.ClassUnderTest.goToUsersAddEditUserContainerPage()V: Line 1409
   * Goal 29. main.ClassUnderTest.goToUsersDashboardContainerPage()V: Line 775
   * Goal 30. main.ClassUnderTest.unpublishLinkOrPagePagesContainerPage(Lcustom_classes/SiteLinkOrPage;)V: Line 2113
   */

  @Test(timeout = 1001000)
  public void test01()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      classUnderTest0.goToUsersDashboardContainerPage();
      int int0 = (-522);
      Id id0 = new Id(int0);
      classUnderTest0.blockUserUserListContainerPage(id0);
      classUnderTest0.deleteUserUserListContainerPage(id0);
      classUnderTest0.cancelOperationDeleteItemPage();
      classUnderTest0.goToEditCurrentUserUserListContainerPage();
      Username username0 = Username.FOO;
      Name name0 = Name.JOHN;
      Email email0 = Email.ASD;
      UserPassword userPassword0 = UserPassword.FOO;
      classUnderTest0.editUserAddEditUserContainerPage(username0, name0, email0, userPassword0);
      classUnderTest0.goToUsersAddEditUserContainerPage();
      classUnderTest0.addUserUserListContainerPage();
      classUnderTest0.closeOperationAddEditUserContainerPage();
      classUnderTest0.goToDashboardUserListContainerPage();
      classUnderTest0.goToDashboardDashboardContainerPage();
      WidgetUserType widgetUserType0 = WidgetUserType.LOGGEDIN;
      WidgetUserDisplay widgetUserDisplay0 = WidgetUserDisplay.LIST;
      WidgetTotalUser widgetTotalUser0 = WidgetTotalUser.SHOW;
      WidgetNumberOfUsers widgetNumberOfUsers0 = WidgetNumberOfUsers.EIGHTEEN;
      classUnderTest0.editUserWidgetDashboardContainerPage(id0, widgetUserType0, widgetUserDisplay0, widgetTotalUser0, widgetNumberOfUsers0);
      WidgetFeedTitle widgetFeedTitle0 = WidgetFeedTitle.SPORTNEWS;
      WidgetFeedUrl widgetFeedUrl0 = WidgetFeedUrl.PAGEKIT;
      WidgetFeedNumberOfPosts widgetFeedNumberOfPosts0 = new WidgetFeedNumberOfPosts(int0);
      WidgetFeedPostContent widgetFeedPostContent0 = WidgetFeedPostContent.SHOWALLPOSTS;
      classUnderTest0.addFeedWidgetDashboardContainerPage(widgetFeedTitle0, widgetFeedUrl0, widgetFeedNumberOfPosts0, widgetFeedPostContent0);
      int int1 = 3928;
      Id id1 = new Id(int1);
      classUnderTest0.deleteUserOrFeedWidgetDashboardContainerPage(id1);
      classUnderTest0.confirmOperationDeleteItemPage();
      WidgetLocation widgetLocation0 = WidgetLocation.GENOA;
      WidgetUnit widgetUnit0 = WidgetUnit.IMPERIAL;
      classUnderTest0.editLocationWidgetDashboardContainerPage(id1, widgetLocation0, widgetUnit0);
      classUnderTest0.deleteLocationWidgetDashboardContainerPage(id1);
      classUnderTest0.goToEditCurrentUserDashboardContainerPage();
      classUnderTest0.goToRolesAddEditUserContainerPage();
      classUnderTest0.goToSitePermissionsContainerPage();
      classUnderTest0.goToSitePagesContainerPage();
      SitePages sitePages0 = SitePages.HOME;
      classUnderTest0.unpublishLinkOrPagePagesContainerPage(sitePages0);
      classUnderTest0.addLinkPagesContainerPage();
      classUnderTest0.goToSettingsAddEditLinkContainerPage();
      classUnderTest0.goToUsersAddEditLinkContainerPage();
      classUnderTest0.addUserUserListContainerPage();
      classUnderTest0.goToDashboardAddEditUserContainerPage();
      Id id2 = new Id(widgetFeedNumberOfPosts0.value);
      classUnderTest0.deleteUserOrFeedWidgetDashboardContainerPage(id2);
      classUnderTest0.cancelOperationDeleteItemPage();
      classUnderTest0.goToSiteDashboardContainerPage();
      classUnderTest0.addPagePagesContainerPage();
      SitePages sitePages1 = SitePages.DAILY_SECTION;
      HTMLSnippets hTMLSnippets0 = HTMLSnippets.HOME;
      PageLinkStatus pageLinkStatus0 = PageLinkStatus.DISABLED;
      HideInMenu hideInMenu0 = HideInMenu.NO;
      classUnderTest0.addEditPageAddEditPageContainerPage(sitePages1, hTMLSnippets0, pageLinkStatus0, hideInMenu0);
  }

  //Test case number: 2
  /*
   * 25 covered goals:
   * Goal 1. main.ClassUnderTest.addExistingMenuPagesContainerPage(Lcustom_classes/SiteMenus;)V: Line 1686
   * Goal 2. main.ClassUnderTest.addFeedWidgetDashboardContainerPage(Lcustom_classes/WidgetFeedTitle;Lcustom_classes/WidgetFeedUrl;Lcustom_classes/WidgetFeedNumberOfPosts;Lcustom_classes/WidgetFeedPostContent;)V: Line 515
   * Goal 3. main.ClassUnderTest.addLocationWidgetDashboardContainerPage(Lcustom_classes/WidgetLocation;Lcustom_classes/WidgetUnit;)V: Line 533
   * Goal 4. main.ClassUnderTest.addTextWidgetsContainerPage()V: Line 2786
   * Goal 5. main.ClassUnderTest.addUserAddEditUserContainerPage(Lcustom_classes/Username;Lcustom_classes/Name;Lcustom_classes/Email;Lcustom_classes/UserPassword;Lcustom_classes/UserStatus;)V: Line 1266
   * Goal 6. main.ClassUnderTest.addUserUserListContainerPage()V: Line 812
   * Goal 7. main.ClassUnderTest.addUserWidgetDashboardContainerPage(Lcustom_classes/WidgetUserType;Lcustom_classes/WidgetUserDisplay;Lcustom_classes/WidgetTotalUser;Lcustom_classes/WidgetNumberOfUsers;)V: Line 553
   * Goal 8. main.ClassUnderTest.cancelOperationAddEditItemPage()V: Line 426
   * Goal 9. main.ClassUnderTest.cancelOperationDeleteItemPage()V: Line 252
   * Goal 10. main.ClassUnderTest.closeOperationAddEditUserContainerPage()V: Line 1285
   * Goal 11. main.ClassUnderTest.deleteUserOrFeedWidgetDashboardContainerPage(Lcustom_classes/Id;)V: Line 603
   * Goal 12. main.ClassUnderTest.editLocationWidgetDashboardContainerPage(Lcustom_classes/Id;Lcustom_classes/WidgetLocation;Lcustom_classes/WidgetUnit;)V: Line 664
   * Goal 13. main.ClassUnderTest.editPagePagesContainerPage(Lcustom_classes/SitePages;)V: Line 1884
   * Goal 14. main.ClassUnderTest.editUserAddEditUserContainerPage(Lcustom_classes/Username;Lcustom_classes/Name;Lcustom_classes/Email;Lcustom_classes/UserPassword;)V: Line 1303
   * Goal 15. main.ClassUnderTest.goToDashboardDashboardContainerPage()V: Line 713
   * Goal 16. main.ClassUnderTest.goToDashboardPagesContainerPage()V: Line 1901
   * Goal 17. main.ClassUnderTest.goToDashboardUserListContainerPage()V: Line 906
   * Goal 18. main.ClassUnderTest.goToPagesAddEditTextWidgetContainerPage()V: Line 2449
   * Goal 19. main.ClassUnderTest.goToPagesPagesContainerPage()V: Line 1946
   * Goal 20. main.ClassUnderTest.goToSiteAddEditUserContainerPage()V: Line 1385
   * Goal 21. main.ClassUnderTest.goToSiteDashboardContainerPage()V: Line 763
   * Goal 22. main.ClassUnderTest.goToUserListUserListContainerPage()V: Line 983
   * Goal 23. main.ClassUnderTest.goToUsersDashboardContainerPage()V: Line 775
   * Goal 24. main.ClassUnderTest.goToWidgetsAddEditPageContainerPage()V: Line 2317
   * Goal 25. main.ClassUnderTest.publishAllPagesAndLinksPagesContainerPage()V: Line 2047
   */

  @Test(timeout = 1001000)
  public void test02()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      classUnderTest0.goToUsersDashboardContainerPage();
      classUnderTest0.addUserUserListContainerPage();
      classUnderTest0.closeOperationAddEditUserContainerPage();
      classUnderTest0.goToUserListUserListContainerPage();
      classUnderTest0.goToDashboardUserListContainerPage();
      int int0 = (-5);
      Id id0 = new Id(int0);
      Name name0 = Name.MARK;
      Email email0 = Email.FOO;
      UserPassword userPassword0 = UserPassword.ADMIN;
      UserStatus userStatus0 = UserStatus.BLOCKED;
      Username username0 = Username.FOO;
      WidgetFeedTitle widgetFeedTitle0 = WidgetFeedTitle.SPORTNEWS;
      WidgetFeedUrl widgetFeedUrl0 = WidgetFeedUrl.SPORT;
      int int1 = (-3010);
      WidgetFeedNumberOfPosts widgetFeedNumberOfPosts0 = new WidgetFeedNumberOfPosts(int1);
      WidgetFeedPostContent widgetFeedPostContent0 = WidgetFeedPostContent.DONTSHOW;
      classUnderTest0.addFeedWidgetDashboardContainerPage(widgetFeedTitle0, widgetFeedUrl0, widgetFeedNumberOfPosts0, widgetFeedPostContent0);
      classUnderTest0.goToDashboardDashboardContainerPage();
      classUnderTest0.goToUsersDashboardContainerPage();
      classUnderTest0.addUserUserListContainerPage();
      UserPassword userPassword1 = UserPassword.ADMIN;
      classUnderTest0.addUserAddEditUserContainerPage(username0, name0, email0, userPassword1, userStatus0);
      Name name1 = Name.JOHN;
      Email email1 = Email.FOO;
      classUnderTest0.editUserAddEditUserContainerPage(username0, name1, email1, userPassword0);
      classUnderTest0.goToSiteAddEditUserContainerPage();
      classUnderTest0.publishAllPagesAndLinksPagesContainerPage();
      SiteMenus siteMenus0 = SiteMenus.MAIN;
      classUnderTest0.addExistingMenuPagesContainerPage(siteMenus0);
      classUnderTest0.cancelOperationAddEditItemPage();
      SitePages sitePages0 = SitePages.HOME;
      classUnderTest0.editPagePagesContainerPage(sitePages0);
      classUnderTest0.goToWidgetsAddEditPageContainerPage();
      classUnderTest0.addTextWidgetsContainerPage();
      classUnderTest0.goToPagesAddEditTextWidgetContainerPage();
      classUnderTest0.goToDashboardPagesContainerPage();
      WidgetFeedTitle widgetFeedTitle1 = WidgetFeedTitle.PAGEKITNEWS;
      classUnderTest0.addFeedWidgetDashboardContainerPage(widgetFeedTitle1, widgetFeedUrl0, widgetFeedNumberOfPosts0, widgetFeedPostContent0);
      WidgetUserType widgetUserType0 = WidgetUserType.LASTREGISTERED;
      WidgetUserDisplay widgetUserDisplay0 = WidgetUserDisplay.THUMBNAIL;
      WidgetTotalUser widgetTotalUser0 = WidgetTotalUser.HIDE;
      WidgetNumberOfUsers widgetNumberOfUsers0 = WidgetNumberOfUsers.EIGHTEEN;
      classUnderTest0.addUserWidgetDashboardContainerPage(widgetUserType0, widgetUserDisplay0, widgetTotalUser0, widgetNumberOfUsers0);
      Id id1 = new Id(id0.value);
      WidgetLocation widgetLocation0 = WidgetLocation.TRENTO;
      WidgetUnit widgetUnit0 = WidgetUnit.IMPERIAL;
      classUnderTest0.editLocationWidgetDashboardContainerPage(id1, widgetLocation0, widgetUnit0);
      classUnderTest0.goToDashboardDashboardContainerPage();
      WidgetFeedTitle widgetFeedTitle2 = WidgetFeedTitle.PAGEKITNEWS;
      WidgetFeedNumberOfPosts widgetFeedNumberOfPosts1 = new WidgetFeedNumberOfPosts(int0);
      WidgetFeedPostContent widgetFeedPostContent1 = WidgetFeedPostContent.SHOWFIRSTPOST;
      classUnderTest0.addFeedWidgetDashboardContainerPage(widgetFeedTitle2, widgetFeedUrl0, widgetFeedNumberOfPosts1, widgetFeedPostContent1);
      classUnderTest0.deleteUserOrFeedWidgetDashboardContainerPage(id0);
      classUnderTest0.cancelOperationDeleteItemPage();
      classUnderTest0.goToDashboardDashboardContainerPage();
      WidgetUnit widgetUnit1 = WidgetUnit.METRIC;
      classUnderTest0.addLocationWidgetDashboardContainerPage(widgetLocation0, widgetUnit1);
      classUnderTest0.goToSiteDashboardContainerPage();
      classUnderTest0.goToPagesPagesContainerPage();
  }

  //Test case number: 3
  /*
   * 14 covered goals:
   * Goal 1. main.ClassUnderTest.addItemAddEditItemPage()V: Line 396
   * Goal 2. main.ClassUnderTest.addMenuPagesContainerPage(Lcustom_classes/SiteMenus;)V: Line 1727
   * Goal 3. main.ClassUnderTest.addMenuWidgetsContainerPage()V: Line 2772
   * Goal 4. main.ClassUnderTest.deleteAllPagesAndLinksPagesContainerPage()V: Line 1767
   * Goal 5. main.ClassUnderTest.deleteLocationWidgetDashboardContainerPage(Lcustom_classes/Id;)V: Line 575
   * Goal 6. main.ClassUnderTest.editMenuPagesContainerPage(Lcustom_classes/SiteMenus;Lcustom_classes/SiteMenus;)V: Line 1833
   * Goal 7. main.ClassUnderTest.goToDashboardPagesContainerPage()V: Line 1901
   * Goal 8. main.ClassUnderTest.goToPagesPagesContainerPage()V: Line 1946
   * Goal 9. main.ClassUnderTest.goToPermissionsUserListContainerPage()V: Line 932
   * Goal 10. main.ClassUnderTest.goToSiteDashboardContainerPage()V: Line 763
   * Goal 11. main.ClassUnderTest.goToSitePermissionsContainerPage()V: Line 1511
   * Goal 12. main.ClassUnderTest.goToUsersDashboardContainerPage()V: Line 775
   * Goal 13. main.ClassUnderTest.goToWidgetsPagesContainerPage()V: Line 1982
   * Goal 14. main.ClassUnderTest.publishAllPagesAndLinksPagesContainerPage()V: Line 2047
   */

  @Test(timeout = 1001000)
  public void test03()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      classUnderTest0.goToUsersDashboardContainerPage();
      classUnderTest0.goToPermissionsUserListContainerPage();
      classUnderTest0.goToSitePermissionsContainerPage();
      classUnderTest0.publishAllPagesAndLinksPagesContainerPage();
      int int0 = (-374);
      Id id0 = new Id(int0);
      SiteMenus siteMenus0 = SiteMenus.SIDE_MENU;
      classUnderTest0.addMenuPagesContainerPage(siteMenus0);
      classUnderTest0.addItemAddEditItemPage();
      classUnderTest0.goToPagesPagesContainerPage();
      classUnderTest0.deleteAllPagesAndLinksPagesContainerPage();
      SiteMenus siteMenus1 = SiteMenus.OTHER_MENU;
      classUnderTest0.editMenuPagesContainerPage(siteMenus0, siteMenus1);
      classUnderTest0.addItemAddEditItemPage();
      classUnderTest0.goToDashboardPagesContainerPage();
      classUnderTest0.deleteLocationWidgetDashboardContainerPage(id0);
      classUnderTest0.goToSiteDashboardContainerPage();
      classUnderTest0.goToWidgetsPagesContainerPage();
      classUnderTest0.addMenuWidgetsContainerPage();
  }

  //Test case number: 4
  /*
   * 22 covered goals:
   * Goal 1. main.ClassUnderTest.addFeedWidgetDashboardContainerPage(Lcustom_classes/WidgetFeedTitle;Lcustom_classes/WidgetFeedUrl;Lcustom_classes/WidgetFeedNumberOfPosts;Lcustom_classes/WidgetFeedPostContent;)V: Line 515
   * Goal 2. main.ClassUnderTest.addLocationWidgetDashboardContainerPage(Lcustom_classes/WidgetLocation;Lcustom_classes/WidgetUnit;)V: Line 533
   * Goal 3. main.ClassUnderTest.addLoginWidgetsContainerPage()V: Line 2758
   * Goal 4. main.ClassUnderTest.blockUserUserListContainerPage(Lcustom_classes/Id;)V: Line 834
   * Goal 5. main.ClassUnderTest.cancelOperationDeleteItemPage()V: Line 252
   * Goal 6. main.ClassUnderTest.cancelOperationDeleteItemPage()V: Line 257
   * Goal 7. main.ClassUnderTest.deleteAdminUserUserListContainerPage(Lcustom_classes/Id;)V: Line 864
   * Goal 8. main.ClassUnderTest.deleteUserOrFeedWidgetDashboardContainerPage(Lcustom_classes/Id;)V: Line 603
   * Goal 9. main.ClassUnderTest.deleteUserUserListContainerPage(Lcustom_classes/Id;)V: Line 889
   * Goal 10. main.ClassUnderTest.goToDashboardDashboardContainerPage()V: Line 713
   * Goal 11. main.ClassUnderTest.goToDashboardUserListContainerPage()V: Line 906
   * Goal 12. main.ClassUnderTest.goToDashboardUserSettingsContainerPage()V: Line 1563
   * Goal 13. main.ClassUnderTest.goToEditCurrentUserDashboardContainerPage()V: Line 726
   * Goal 14. main.ClassUnderTest.goToEditCurrentUserUserListContainerPage()V: Line 919
   * Goal 15. main.ClassUnderTest.goToPermissionsUserListContainerPage()V: Line 932
   * Goal 16. main.ClassUnderTest.goToRolesPermissionsContainerPage()V: Line 1485
   * Goal 17. main.ClassUnderTest.goToSettingsUserListContainerPage()V: Line 958
   * Goal 18. main.ClassUnderTest.goToSiteAddEditUserContainerPage()V: Line 1385
   * Goal 19. main.ClassUnderTest.goToUserListAddEditUserContainerPage()V: Line 1397
   * Goal 20. main.ClassUnderTest.goToUsersAddEditLoginWidgetContainerPage()V: Line 3277
   * Goal 21. main.ClassUnderTest.goToUsersDashboardContainerPage()V: Line 775
   * Goal 22. main.ClassUnderTest.goToWidgetsPagesContainerPage()V: Line 1982
   */

  @Test(timeout = 1001000)
  public void test04()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      classUnderTest0.goToEditCurrentUserDashboardContainerPage();
      classUnderTest0.goToUserListAddEditUserContainerPage();
      int int0 = 3678;
      Id id0 = new Id(int0);
      classUnderTest0.blockUserUserListContainerPage(id0);
      classUnderTest0.deleteUserUserListContainerPage(id0);
      classUnderTest0.cancelOperationDeleteItemPage();
      classUnderTest0.goToEditCurrentUserUserListContainerPage();
      classUnderTest0.goToSiteAddEditUserContainerPage();
      classUnderTest0.goToWidgetsPagesContainerPage();
      classUnderTest0.addLoginWidgetsContainerPage();
      classUnderTest0.goToUsersAddEditLoginWidgetContainerPage();
      classUnderTest0.deleteAdminUserUserListContainerPage(id0);
      classUnderTest0.cancelOperationDeleteItemPage();
      WidgetUnit widgetUnit0 = WidgetUnit.IMPERIAL;
      WidgetFeedTitle widgetFeedTitle0 = WidgetFeedTitle.SPORTNEWS;
      WidgetFeedUrl widgetFeedUrl0 = WidgetFeedUrl.SPORT;
      WidgetFeedNumberOfPosts widgetFeedNumberOfPosts0 = new WidgetFeedNumberOfPosts(id0.value);
      classUnderTest0.goToDashboardUserListContainerPage();
      classUnderTest0.goToDashboardDashboardContainerPage();
      classUnderTest0.goToUsersDashboardContainerPage();
      classUnderTest0.goToSettingsUserListContainerPage();
      classUnderTest0.goToDashboardUserSettingsContainerPage();
      WidgetLocation widgetLocation0 = WidgetLocation.GENOA;
      classUnderTest0.addLocationWidgetDashboardContainerPage(widgetLocation0, widgetUnit0);
      classUnderTest0.deleteUserOrFeedWidgetDashboardContainerPage(id0);
      classUnderTest0.cancelOperationDeleteItemPage();
      WidgetFeedPostContent widgetFeedPostContent0 = WidgetFeedPostContent.SHOWFIRSTPOST;
      classUnderTest0.addFeedWidgetDashboardContainerPage(widgetFeedTitle0, widgetFeedUrl0, widgetFeedNumberOfPosts0, widgetFeedPostContent0);
      classUnderTest0.goToUsersDashboardContainerPage();
      classUnderTest0.blockUserUserListContainerPage(id0);
      classUnderTest0.blockUserUserListContainerPage(id0);
      classUnderTest0.goToPermissionsUserListContainerPage();
      classUnderTest0.goToRolesPermissionsContainerPage();
  }

  //Test case number: 5
  /*
   * 8 covered goals:
   * Goal 1. main.ClassUnderTest.addUserAddEditUserContainerPage(Lcustom_classes/Username;Lcustom_classes/Name;Lcustom_classes/Email;Lcustom_classes/UserPassword;Lcustom_classes/UserStatus;)V: Line 1263
   * Goal 2. main.ClassUnderTest.addUserUserListContainerPage()V: Line 812
   * Goal 3. main.ClassUnderTest.blockUserUserListContainerPage(Lcustom_classes/Id;)V: Line 834
   * Goal 4. main.ClassUnderTest.closeOperationAddEditUserContainerPage()V: Line 1285
   * Goal 5. main.ClassUnderTest.goToEditUserDashboardContainerPage(Lcustom_classes/Id;)V: Line 746
   * Goal 6. main.ClassUnderTest.goToSiteAddEditUserContainerPage()V: Line 1385
   * Goal 7. main.ClassUnderTest.goToUserListUserListContainerPage()V: Line 983
   * Goal 8. main.ClassUnderTest.publishAllPagesAndLinksPagesContainerPage()V: Line 2047
   */

  @Test(timeout = 1001000)
  public void test05()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      int int0 = (-141);
      Id id0 = new Id(int0);
      classUnderTest0.goToEditUserDashboardContainerPage(id0);
      classUnderTest0.closeOperationAddEditUserContainerPage();
      classUnderTest0.blockUserUserListContainerPage(id0);
      classUnderTest0.goToUserListUserListContainerPage();
      classUnderTest0.addUserUserListContainerPage();
      Username username0 = Username.ADMIN;
      Name name0 = Name.MARK;
      Email email0 = Email.ASD;
      UserPassword userPassword0 = UserPassword.FOO;
      UserStatus userStatus0 = UserStatus.ACTIVE;
      classUnderTest0.addUserAddEditUserContainerPage(username0, name0, email0, userPassword0, userStatus0);
      classUnderTest0.goToSiteAddEditUserContainerPage();
      classUnderTest0.publishAllPagesAndLinksPagesContainerPage();
  }

  //Test case number: 6
  /*
   * 8 covered goals:
   * Goal 1. main.ClassUnderTest.cancelOperationSelectLinkPage()V: Line 30
   * Goal 2. main.ClassUnderTest.changeSettingsUserSettingsContainerPage(Lcustom_classes/RegistrationUserSettings;)V: Line 1550
   * Goal 3. main.ClassUnderTest.editLocationWidgetDashboardContainerPage(Lcustom_classes/Id;Lcustom_classes/WidgetLocation;Lcustom_classes/WidgetUnit;)V: Line 664
   * Goal 4. main.ClassUnderTest.goToMenuPagesContainerPage(Lcustom_classes/SiteMenus;)V: Line 1929
   * Goal 5. main.ClassUnderTest.goToPagesPagesContainerPage()V: Line 1946
   * Goal 6. main.ClassUnderTest.goToSettingsUserListContainerPage()V: Line 958
   * Goal 7. main.ClassUnderTest.goToSiteDashboardContainerPage()V: Line 763
   * Goal 8. main.ClassUnderTest.goToUsersPagesContainerPage()V: Line 1970
   */

  @Test(timeout = 1001000)
  public void test06()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      int int0 = 451;
      Id id0 = new Id(int0);
      WidgetLocation widgetLocation0 = WidgetLocation.TRENTO;
      WidgetUnit widgetUnit0 = WidgetUnit.IMPERIAL;
      classUnderTest0.editLocationWidgetDashboardContainerPage(id0, widgetLocation0, widgetUnit0);
      classUnderTest0.goToSiteDashboardContainerPage();
      SiteMenus siteMenus0 = SiteMenus.NOT_LINKED;
      classUnderTest0.goToMenuPagesContainerPage(siteMenus0);
      classUnderTest0.goToPagesPagesContainerPage();
      classUnderTest0.goToUsersPagesContainerPage();
      classUnderTest0.goToSettingsUserListContainerPage();
      RegistrationUserSettings registrationUserSettings0 = RegistrationUserSettings.DISABLED;
      classUnderTest0.changeSettingsUserSettingsContainerPage(registrationUserSettings0);
      classUnderTest0.cancelOperationSelectLinkPage();
  }

  //Test case number: 7
  /*
   * 6 covered goals:
   * Goal 1. main.ClassUnderTest.addLinkPagesContainerPage()V: Line 1706
   * Goal 2. main.ClassUnderTest.cancelOperationSelectLinkPage()V: Line 35
   * Goal 3. main.ClassUnderTest.goToEditCurrentUserDashboardContainerPage()V: Line 726
   * Goal 4. main.ClassUnderTest.goToPermissionsAddEditUserContainerPage()V: Line 1346
   * Goal 5. main.ClassUnderTest.goToSitePermissionsContainerPage()V: Line 1511
   * Goal 6. main.ClassUnderTest.selectUrlAddEditLinkContainerPage()V: Line 2744
   */

  @Test(timeout = 1001000)
  public void test07()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      classUnderTest0.goToEditCurrentUserDashboardContainerPage();
      classUnderTest0.goToPermissionsAddEditUserContainerPage();
      classUnderTest0.goToSitePermissionsContainerPage();
      classUnderTest0.addLinkPagesContainerPage();
      classUnderTest0.selectUrlAddEditLinkContainerPage();
      classUnderTest0.cancelOperationSelectLinkPage();
  }

  //Test case number: 8
  /*
   * 4 covered goals:
   * Goal 1. main.ClassUnderTest.addLinkPagesContainerPage()V: Line 1706
   * Goal 2. main.ClassUnderTest.closeEditLinkAddEditLinkContainerPage()V: Line 2629
   * Goal 3. main.ClassUnderTest.goToSiteDashboardContainerPage()V: Line 763
   * Goal 4. main.ClassUnderTest.goToSitePagesContainerPage()V: Line 1958
   */

  @Test(timeout = 1001000)
  public void test08()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      classUnderTest0.goToSiteDashboardContainerPage();
      classUnderTest0.goToSitePagesContainerPage();
      classUnderTest0.addLinkPagesContainerPage();
      classUnderTest0.closeEditLinkAddEditLinkContainerPage();
  }

  //Test case number: 9
  /*
   * 18 covered goals:
   * Goal 1. main.ClassUnderTest.addUserUserListContainerPage()V: Line 812
   * Goal 2. main.ClassUnderTest.confirmOperationDeleteItemPage()V: Line 296
   * Goal 3. main.ClassUnderTest.confirmOperationDeleteItemPage()V: Line 304
   * Goal 4. main.ClassUnderTest.deleteAdminUserUserListContainerPage(Lcustom_classes/Id;)V: Line 864
   * Goal 5. main.ClassUnderTest.deleteUserUserListContainerPage(Lcustom_classes/Id;)V: Line 889
   * Goal 6. main.ClassUnderTest.goToDashboardAddEditUserContainerPage()V: Line 1320
   * Goal 7. main.ClassUnderTest.goToDashboardPermissionsContainerPage()V: Line 1446
   * Goal 8. main.ClassUnderTest.goToEditCurrentUserPagesContainerPage()V: Line 1914
   * Goal 9. main.ClassUnderTest.goToEditCurrentUserUserSettingsContainerPage()V: Line 1576
   * Goal 10. main.ClassUnderTest.goToMenuPagesContainerPage(Lcustom_classes/SiteMenus;)V: Line 1929
   * Goal 11. main.ClassUnderTest.goToPermissionsAddEditUserContainerPage()V: Line 1346
   * Goal 12. main.ClassUnderTest.goToSettingsUserListContainerPage()V: Line 958
   * Goal 13. main.ClassUnderTest.goToSiteDashboardContainerPage()V: Line 763
   * Goal 14. main.ClassUnderTest.goToUserListAddEditUserContainerPage()V: Line 1397
   * Goal 15. main.ClassUnderTest.goToUserListUserListContainerPage()V: Line 983
   * Goal 16. main.ClassUnderTest.goToUsersDashboardContainerPage()V: Line 775
   * Goal 17. main.ClassUnderTest.goToUsersPagesContainerPage()V: Line 1970
   * Goal 18. main.ClassUnderTest.publishAllPagesAndLinksPagesContainerPage()V: Line 2047
   */

  @Test(timeout = 1001000)
  public void test09()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      classUnderTest0.goToSiteDashboardContainerPage();
      classUnderTest0.goToEditCurrentUserPagesContainerPage();
      classUnderTest0.goToUserListAddEditUserContainerPage();
      classUnderTest0.addUserUserListContainerPage();
      classUnderTest0.goToDashboardAddEditUserContainerPage();
      classUnderTest0.goToUsersDashboardContainerPage();
      int int0 = 297;
      Id id0 = new Id(int0);
      classUnderTest0.deleteAdminUserUserListContainerPage(id0);
      classUnderTest0.confirmOperationDeleteItemPage();
      classUnderTest0.goToSettingsUserListContainerPage();
      classUnderTest0.goToEditCurrentUserUserSettingsContainerPage();
      classUnderTest0.goToPermissionsAddEditUserContainerPage();
      classUnderTest0.goToDashboardPermissionsContainerPage();
      classUnderTest0.goToSiteDashboardContainerPage();
      classUnderTest0.publishAllPagesAndLinksPagesContainerPage();
      SiteMenus siteMenus0 = SiteMenus.MAIN;
      classUnderTest0.goToMenuPagesContainerPage(siteMenus0);
      classUnderTest0.goToUsersPagesContainerPage();
      classUnderTest0.goToUserListUserListContainerPage();
      classUnderTest0.deleteUserUserListContainerPage(id0);
      classUnderTest0.confirmOperationDeleteItemPage();
  }

  //Test case number: 10
  /*
   * 5 covered goals:
   * Goal 1. main.ClassUnderTest.addLinkPagesContainerPage()V: Line 1706
   * Goal 2. main.ClassUnderTest.addLocationWidgetDashboardContainerPage(Lcustom_classes/WidgetLocation;Lcustom_classes/WidgetUnit;)V: Line 533
   * Goal 3. main.ClassUnderTest.deleteLinkOrPagePagesContainerPage(Lcustom_classes/SiteLinkOrPage;)V: Line 1788
   * Goal 4. main.ClassUnderTest.goToSiteDashboardContainerPage()V: Line 763
   * Goal 5. main.ClassUnderTest.goToSitePagesContainerPage()V: Line 1958
   */

  @Test(timeout = 1001000)
  public void test10()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      WidgetLocation widgetLocation0 = WidgetLocation.MILANO;
      WidgetUnit widgetUnit0 = WidgetUnit.IMPERIAL;
      classUnderTest0.addLocationWidgetDashboardContainerPage(widgetLocation0, widgetUnit0);
      classUnderTest0.goToSiteDashboardContainerPage();
      SitePages sitePages0 = SitePages.HOME;
      classUnderTest0.deleteLinkOrPagePagesContainerPage(sitePages0);
      classUnderTest0.goToSitePagesContainerPage();
      classUnderTest0.addLinkPagesContainerPage();
  }

  //Test case number: 11
  /*
   * 4 covered goals:
   * Goal 1. main.ClassUnderTest.addUserWidgetDashboardContainerPage(Lcustom_classes/WidgetUserType;Lcustom_classes/WidgetUserDisplay;Lcustom_classes/WidgetTotalUser;Lcustom_classes/WidgetNumberOfUsers;)V: Line 553
   * Goal 2. main.ClassUnderTest.editFeedWidgetDashboardContainerPage(Lcustom_classes/Id;Lcustom_classes/WidgetFeedTitle;Lcustom_classes/WidgetFeedUrl;Lcustom_classes/WidgetFeedNumberOfPosts;Lcustom_classes/WidgetFeedPostContent;)V: Line 635
   * Goal 3. main.ClassUnderTest.editLocationWidgetDashboardContainerPage(Lcustom_classes/Id;Lcustom_classes/WidgetLocation;Lcustom_classes/WidgetUnit;)V: Line 664
   * Goal 4. main.ClassUnderTest.goToDashboardDashboardContainerPage()V: Line 713
   */

  @Test(timeout = 1001000)
  public void test11()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      int int0 = 1586;
      Id id0 = new Id(int0);
      WidgetUserDisplay widgetUserDisplay0 = WidgetUserDisplay.THUMBNAIL;
      WidgetNumberOfUsers widgetNumberOfUsers0 = WidgetNumberOfUsers.EIGHTEEN;
      WidgetFeedTitle widgetFeedTitle0 = WidgetFeedTitle.WEATHER;
      WidgetFeedUrl widgetFeedUrl0 = WidgetFeedUrl.SPORT;
      int int1 = (-307);
      WidgetFeedNumberOfPosts widgetFeedNumberOfPosts0 = new WidgetFeedNumberOfPosts(int1);
      WidgetFeedPostContent widgetFeedPostContent0 = WidgetFeedPostContent.SHOWALLPOSTS;
      classUnderTest0.editFeedWidgetDashboardContainerPage(id0, widgetFeedTitle0, widgetFeedUrl0, widgetFeedNumberOfPosts0, widgetFeedPostContent0);
      classUnderTest0.goToDashboardDashboardContainerPage();
      WidgetUserType widgetUserType0 = WidgetUserType.LASTREGISTERED;
      WidgetTotalUser widgetTotalUser0 = WidgetTotalUser.SHOW;
      classUnderTest0.addUserWidgetDashboardContainerPage(widgetUserType0, widgetUserDisplay0, widgetTotalUser0, widgetNumberOfUsers0);
      WidgetLocation widgetLocation0 = WidgetLocation.MILANO;
      WidgetUnit widgetUnit0 = WidgetUnit.IMPERIAL;
      classUnderTest0.editLocationWidgetDashboardContainerPage(id0, widgetLocation0, widgetUnit0);
  }

  //Test case number: 12
  /*
   * 14 covered goals:
   * Goal 1. main.ClassUnderTest.addTextWidgetsContainerPage()V: Line 2786
   * Goal 2. main.ClassUnderTest.blockUserUserListContainerPage(Lcustom_classes/Id;)V: Line 834
   * Goal 3. main.ClassUnderTest.cancelOperationDeleteItemPage()V: Line 257
   * Goal 4. main.ClassUnderTest.deleteUserUserListContainerPage(Lcustom_classes/Id;)V: Line 889
   * Goal 5. main.ClassUnderTest.editUserAddEditUserContainerPage(Lcustom_classes/Username;Lcustom_classes/Name;Lcustom_classes/Email;Lcustom_classes/UserPassword;)V: Line 1303
   * Goal 6. main.ClassUnderTest.giveOrRemoveAllPermissionsToUserRolePermissionsContainerPage(Lcustom_classes/UserRoles;)V: Line 1428
   * Goal 7. main.ClassUnderTest.goToDashboardAddEditTextWidgetContainerPage()V: Line 2423
   * Goal 8. main.ClassUnderTest.goToEditCurrentUserAddEditUserContainerPage()V: Line 1333
   * Goal 9. main.ClassUnderTest.goToEditCurrentUserPermissionsContainerPage()V: Line 1459
   * Goal 10. main.ClassUnderTest.goToEditCurrentUserUserListContainerPage()V: Line 919
   * Goal 11. main.ClassUnderTest.goToRolesAddEditUserContainerPage()V: Line 1359
   * Goal 12. main.ClassUnderTest.goToSiteAddEditUserContainerPage()V: Line 1385
   * Goal 13. main.ClassUnderTest.goToUsersDashboardContainerPage()V: Line 775
   * Goal 14. main.ClassUnderTest.goToWidgetsPagesContainerPage()V: Line 1982
   */

  @Test(timeout = 1001000)
  public void test12()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      classUnderTest0.goToUsersDashboardContainerPage();
      int int0 = (-522);
      Id id0 = new Id(int0);
      classUnderTest0.blockUserUserListContainerPage(id0);
      classUnderTest0.deleteUserUserListContainerPage(id0);
      classUnderTest0.cancelOperationDeleteItemPage();
      classUnderTest0.goToEditCurrentUserUserListContainerPage();
      Username username0 = Username.FOO;
      Name name0 = Name.JOHN;
      Email email0 = Email.ASD;
      UserPassword userPassword0 = UserPassword.FOO;
      classUnderTest0.editUserAddEditUserContainerPage(username0, name0, email0, userPassword0);
      classUnderTest0.goToRolesAddEditUserContainerPage();
      UserRoles userRoles0 = UserRoles.AUTHENTICATED;
      classUnderTest0.giveOrRemoveAllPermissionsToUserRolePermissionsContainerPage(userRoles0);
      classUnderTest0.goToEditCurrentUserPermissionsContainerPage();
      classUnderTest0.goToEditCurrentUserAddEditUserContainerPage();
      Username username1 = Username.ADMIN;
      Name name1 = Name.MARK;
      Email email1 = Email.FOO;
      UserPassword userPassword1 = UserPassword.FOO;
      classUnderTest0.editUserAddEditUserContainerPage(username1, name1, email1, userPassword1);
      classUnderTest0.goToEditCurrentUserAddEditUserContainerPage();
      classUnderTest0.goToSiteAddEditUserContainerPage();
      classUnderTest0.goToWidgetsPagesContainerPage();
      classUnderTest0.addTextWidgetsContainerPage();
      classUnderTest0.goToDashboardAddEditTextWidgetContainerPage();
  }

  //Test case number: 13
  /*
   * 12 covered goals:
   * Goal 1. main.ClassUnderTest.addLocationWidgetDashboardContainerPage(Lcustom_classes/WidgetLocation;Lcustom_classes/WidgetUnit;)V: Line 533
   * Goal 2. main.ClassUnderTest.addPagePagesContainerPage()V: Line 1747
   * Goal 3. main.ClassUnderTest.addUserWidgetDashboardContainerPage(Lcustom_classes/WidgetUserType;Lcustom_classes/WidgetUserDisplay;Lcustom_classes/WidgetTotalUser;Lcustom_classes/WidgetNumberOfUsers;)V: Line 553
   * Goal 4. main.ClassUnderTest.deleteLocationWidgetDashboardContainerPage(Lcustom_classes/Id;)V: Line 575
   * Goal 5. main.ClassUnderTest.editLocationWidgetDashboardContainerPage(Lcustom_classes/Id;Lcustom_classes/WidgetLocation;Lcustom_classes/WidgetUnit;)V: Line 664
   * Goal 6. main.ClassUnderTest.goToContentAddEditPageContainerPage()V: Line 2229
   * Goal 7. main.ClassUnderTest.goToDashboardUserSettingsContainerPage()V: Line 1563
   * Goal 8. main.ClassUnderTest.goToRolesPermissionsContainerPage()V: Line 1485
   * Goal 9. main.ClassUnderTest.goToRolesUserListContainerPage()V: Line 945
   * Goal 10. main.ClassUnderTest.goToSettingsPermissionsContainerPage()V: Line 1498
   * Goal 11. main.ClassUnderTest.goToSiteDashboardContainerPage()V: Line 763
   * Goal 12. main.ClassUnderTest.goToUsersDashboardContainerPage()V: Line 775
   */

  @Test(timeout = 1001000)
  public void test13()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      WidgetLocation widgetLocation0 = WidgetLocation.TRENTO;
      WidgetUnit widgetUnit0 = WidgetUnit.IMPERIAL;
      classUnderTest0.addLocationWidgetDashboardContainerPage(widgetLocation0, widgetUnit0);
      int int0 = (-980);
      Id id0 = new Id(int0);
      classUnderTest0.deleteLocationWidgetDashboardContainerPage(id0);
      classUnderTest0.editLocationWidgetDashboardContainerPage(id0, widgetLocation0, widgetUnit0);
      classUnderTest0.deleteLocationWidgetDashboardContainerPage(id0);
      classUnderTest0.goToUsersDashboardContainerPage();
      classUnderTest0.goToRolesUserListContainerPage();
      classUnderTest0.goToRolesPermissionsContainerPage();
      classUnderTest0.goToRolesPermissionsContainerPage();
      classUnderTest0.goToSettingsPermissionsContainerPage();
      classUnderTest0.goToDashboardUserSettingsContainerPage();
      WidgetUserType widgetUserType0 = WidgetUserType.LASTREGISTERED;
      WidgetUserDisplay widgetUserDisplay0 = WidgetUserDisplay.LIST;
      WidgetTotalUser widgetTotalUser0 = WidgetTotalUser.HIDE;
      WidgetNumberOfUsers widgetNumberOfUsers0 = WidgetNumberOfUsers.SIX;
      classUnderTest0.addUserWidgetDashboardContainerPage(widgetUserType0, widgetUserDisplay0, widgetTotalUser0, widgetNumberOfUsers0);
      classUnderTest0.goToSiteDashboardContainerPage();
      classUnderTest0.addPagePagesContainerPage();
      classUnderTest0.goToContentAddEditPageContainerPage();
  }

  //Test case number: 14
  /*
   * 21 covered goals:
   * Goal 1. main.ClassUnderTest.addLocationWidgetDashboardContainerPage(Lcustom_classes/WidgetLocation;Lcustom_classes/WidgetUnit;)V: Line 533
   * Goal 2. main.ClassUnderTest.addLoginWidgetsContainerPage()V: Line 2758
   * Goal 3. main.ClassUnderTest.addPagePagesContainerPage()V: Line 1747
   * Goal 4. main.ClassUnderTest.addUserWidgetDashboardContainerPage(Lcustom_classes/WidgetUserType;Lcustom_classes/WidgetUserDisplay;Lcustom_classes/WidgetTotalUser;Lcustom_classes/WidgetNumberOfUsers;)V: Line 553
   * Goal 5. main.ClassUnderTest.closeOperationAddEditUserContainerPage()V: Line 1285
   * Goal 6. main.ClassUnderTest.confirmOperationDeleteItemPage()V: Line 289
   * Goal 7. main.ClassUnderTest.deleteUserOrFeedWidgetDashboardContainerPage(Lcustom_classes/Id;)V: Line 603
   * Goal 8. main.ClassUnderTest.goToDashboardAddEditPageContainerPage()V: Line 2242
   * Goal 9. main.ClassUnderTest.goToDashboardAddEditUserContainerPage()V: Line 1320
   * Goal 10. main.ClassUnderTest.goToDashboardPagesContainerPage()V: Line 1901
   * Goal 11. main.ClassUnderTest.goToEditCurrentUserUserListContainerPage()V: Line 919
   * Goal 12. main.ClassUnderTest.goToEditUserDashboardContainerPage(Lcustom_classes/Id;)V: Line 746
   * Goal 13. main.ClassUnderTest.goToMenuPagesContainerPage(Lcustom_classes/SiteMenus;)V: Line 1929
   * Goal 14. main.ClassUnderTest.goToPagesAddEditLoginWidgetContainerPage()V: Line 3240
   * Goal 15. main.ClassUnderTest.goToPagesPagesContainerPage()V: Line 1946
   * Goal 16. main.ClassUnderTest.goToSettingsAddEditLoginWidgetContainerPage()V: Line 3252
   * Goal 17. main.ClassUnderTest.goToSiteAddEditUserContainerPage()V: Line 1385
   * Goal 18. main.ClassUnderTest.goToSiteUserListContainerPage()V: Line 971
   * Goal 19. main.ClassUnderTest.goToUsersDashboardContainerPage()V: Line 775
   * Goal 20. main.ClassUnderTest.goToWidgetsPagesContainerPage()V: Line 1982
   * Goal 21. main.ClassUnderTest.moveAllPagesAndLinksToMenuPagesContainerPage(Lcustom_classes/SiteMenus;)V: Line 2000
   */

  @Test(timeout = 1001000)
  public void test14()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      int int0 = 451;
      Id id0 = new Id(int0);
      WidgetUserType widgetUserType0 = WidgetUserType.LASTREGISTERED;
      WidgetUserDisplay widgetUserDisplay0 = WidgetUserDisplay.LIST;
      WidgetTotalUser widgetTotalUser0 = WidgetTotalUser.HIDE;
      WidgetNumberOfUsers widgetNumberOfUsers0 = WidgetNumberOfUsers.EIGHTEEN;
      classUnderTest0.addUserWidgetDashboardContainerPage(widgetUserType0, widgetUserDisplay0, widgetTotalUser0, widgetNumberOfUsers0);
      classUnderTest0.goToEditUserDashboardContainerPage(id0);
      classUnderTest0.goToSiteAddEditUserContainerPage();
      classUnderTest0.goToPagesPagesContainerPage();
      SiteMenus siteMenus0 = SiteMenus.MAIN;
      classUnderTest0.moveAllPagesAndLinksToMenuPagesContainerPage(siteMenus0);
      classUnderTest0.goToMenuPagesContainerPage(siteMenus0);
      classUnderTest0.addPagePagesContainerPage();
      classUnderTest0.goToDashboardAddEditPageContainerPage();
      classUnderTest0.goToEditUserDashboardContainerPage(id0);
      classUnderTest0.closeOperationAddEditUserContainerPage();
      classUnderTest0.goToEditCurrentUserUserListContainerPage();
      classUnderTest0.goToDashboardAddEditUserContainerPage();
      WidgetLocation widgetLocation0 = WidgetLocation.GENOA;
      WidgetUnit widgetUnit0 = WidgetUnit.IMPERIAL;
      classUnderTest0.addLocationWidgetDashboardContainerPage(widgetLocation0, widgetUnit0);
      classUnderTest0.deleteUserOrFeedWidgetDashboardContainerPage(id0);
      classUnderTest0.confirmOperationDeleteItemPage();
      classUnderTest0.goToUsersDashboardContainerPage();
      classUnderTest0.goToSiteUserListContainerPage();
      classUnderTest0.moveAllPagesAndLinksToMenuPagesContainerPage(siteMenus0);
      SiteMenus siteMenus1 = SiteMenus.MAIN;
      classUnderTest0.moveAllPagesAndLinksToMenuPagesContainerPage(siteMenus1);
      classUnderTest0.goToWidgetsPagesContainerPage();
      classUnderTest0.addLoginWidgetsContainerPage();
      classUnderTest0.goToSettingsAddEditLoginWidgetContainerPage();
      classUnderTest0.goToPagesAddEditLoginWidgetContainerPage();
      classUnderTest0.goToDashboardPagesContainerPage();
  }

  //Test case number: 15
  /*
   * 24 covered goals:
   * Goal 1. main.ClassUnderTest.addPagePagesContainerPage()V: Line 1747
   * Goal 2. main.ClassUnderTest.cancelOperationDeleteItemPage()V: Line 252
   * Goal 3. main.ClassUnderTest.deleteUserOrFeedWidgetDashboardContainerPage(Lcustom_classes/Id;)V: Line 603
   * Goal 4. main.ClassUnderTest.editUserWidgetDashboardContainerPage(Lcustom_classes/Id;Lcustom_classes/WidgetUserType;Lcustom_classes/WidgetUserDisplay;Lcustom_classes/WidgetTotalUser;Lcustom_classes/WidgetNumberOfUsers;)V: Line 696
   * Goal 5. main.ClassUnderTest.goToDashboardPagesContainerPage()V: Line 1901
   * Goal 6. main.ClassUnderTest.goToDashboardPermissionsContainerPage()V: Line 1446
   * Goal 7. main.ClassUnderTest.goToDashboardWidgetsContainerPage()V: Line 2942
   * Goal 8. main.ClassUnderTest.goToEditCurrentUserAddEditUserContainerPage()V: Line 1333
   * Goal 9. main.ClassUnderTest.goToEditCurrentUserPagesContainerPage()V: Line 1914
   * Goal 10. main.ClassUnderTest.goToEditCurrentUserUserListContainerPage()V: Line 919
   * Goal 11. main.ClassUnderTest.goToEditUserDashboardContainerPage(Lcustom_classes/Id;)V: Line 746
   * Goal 12. main.ClassUnderTest.goToMenuPagesContainerPage(Lcustom_classes/SiteMenus;)V: Line 1929
   * Goal 13. main.ClassUnderTest.goToPagesPagesContainerPage()V: Line 1946
   * Goal 14. main.ClassUnderTest.goToPermissionsAddEditUserContainerPage()V: Line 1346
   * Goal 15. main.ClassUnderTest.goToPermissionsPermissionsContainerPage()V: Line 1472
   * Goal 16. main.ClassUnderTest.goToPermissionsUserSettingsContainerPage()V: Line 1589
   * Goal 17. main.ClassUnderTest.goToSettingsUserListContainerPage()V: Line 958
   * Goal 18. main.ClassUnderTest.goToSettingsUserSettingsContainerPage()V: Line 1615
   * Goal 19. main.ClassUnderTest.goToSiteAddEditUserContainerPage()V: Line 1385
   * Goal 20. main.ClassUnderTest.goToSiteDashboardContainerPage()V: Line 763
   * Goal 21. main.ClassUnderTest.goToUsersAddEditPageContainerPage()V: Line 2305
   * Goal 22. main.ClassUnderTest.goToUsersPermissionsContainerPage()V: Line 1535
   * Goal 23. main.ClassUnderTest.goToWidgetsPagesContainerPage()V: Line 1982
   * Goal 24. main.ClassUnderTest.saveSettingsUserSettingsContainerPage()V: Line 1667
   */

  @Test(timeout = 1001000)
  public void test15()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      int int0 = (-3144);
      Id id0 = new Id(int0);
      WidgetUserType widgetUserType0 = WidgetUserType.LASTREGISTERED;
      WidgetUserDisplay widgetUserDisplay0 = WidgetUserDisplay.THUMBNAIL;
      WidgetTotalUser widgetTotalUser0 = WidgetTotalUser.SHOW;
      WidgetNumberOfUsers widgetNumberOfUsers0 = WidgetNumberOfUsers.TWELVE;
      classUnderTest0.editUserWidgetDashboardContainerPage(id0, widgetUserType0, widgetUserDisplay0, widgetTotalUser0, widgetNumberOfUsers0);
      classUnderTest0.goToSiteDashboardContainerPage();
      classUnderTest0.addPagePagesContainerPage();
      classUnderTest0.goToUsersAddEditPageContainerPage();
      classUnderTest0.goToEditCurrentUserUserListContainerPage();
      classUnderTest0.goToPermissionsAddEditUserContainerPage();
      classUnderTest0.goToUsersPermissionsContainerPage();
      classUnderTest0.goToSettingsUserListContainerPage();
      classUnderTest0.goToSettingsUserSettingsContainerPage();
      classUnderTest0.goToSettingsUserSettingsContainerPage();
      classUnderTest0.saveSettingsUserSettingsContainerPage();
      classUnderTest0.goToPermissionsUserSettingsContainerPage();
      classUnderTest0.goToPermissionsPermissionsContainerPage();
      classUnderTest0.goToDashboardPermissionsContainerPage();
      classUnderTest0.goToSiteDashboardContainerPage();
      classUnderTest0.goToDashboardPagesContainerPage();
      classUnderTest0.goToEditUserDashboardContainerPage(id0);
      classUnderTest0.goToEditCurrentUserAddEditUserContainerPage();
      classUnderTest0.goToSiteAddEditUserContainerPage();
      SiteMenus siteMenus0 = SiteMenus.NOT_LINKED;
      classUnderTest0.goToMenuPagesContainerPage(siteMenus0);
      classUnderTest0.goToEditCurrentUserPagesContainerPage();
      classUnderTest0.goToSiteAddEditUserContainerPage();
      classUnderTest0.goToPagesPagesContainerPage();
      classUnderTest0.goToWidgetsPagesContainerPage();
      classUnderTest0.goToDashboardWidgetsContainerPage();
      classUnderTest0.deleteUserOrFeedWidgetDashboardContainerPage(id0);
      classUnderTest0.cancelOperationDeleteItemPage();
      classUnderTest0.deleteUserOrFeedWidgetDashboardContainerPage(id0);
      classUnderTest0.cancelOperationDeleteItemPage();
  }

  //Test case number: 16
  /*
   * 9 covered goals:
   * Goal 1. main.ClassUnderTest.addLinkPagesContainerPage()V: Line 1706
   * Goal 2. main.ClassUnderTest.deleteLocationWidgetDashboardContainerPage(Lcustom_classes/Id;)V: Line 575
   * Goal 3. main.ClassUnderTest.editUserAddEditUserContainerPage(Lcustom_classes/Username;Lcustom_classes/Name;Lcustom_classes/Email;Lcustom_classes/UserPassword;)V: Line 1303
   * Goal 4. main.ClassUnderTest.goToDashboardPermissionsContainerPage()V: Line 1446
   * Goal 5. main.ClassUnderTest.goToEditCurrentUserAddEditLinkContainerPage()V: Line 2655
   * Goal 6. main.ClassUnderTest.goToEditCurrentUserPagesContainerPage()V: Line 1914
   * Goal 7. main.ClassUnderTest.goToRolesAddEditUserContainerPage()V: Line 1359
   * Goal 8. main.ClassUnderTest.goToSiteDashboardContainerPage()V: Line 763
   * Goal 9. main.ClassUnderTest.publishAllPagesAndLinksPagesContainerPage()V: Line 2047
   */

  @Test(timeout = 1001000)
  public void test16()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      int int0 = 535;
      Id id0 = new Id(int0);
      classUnderTest0.deleteLocationWidgetDashboardContainerPage(id0);
      classUnderTest0.goToSiteDashboardContainerPage();
      classUnderTest0.publishAllPagesAndLinksPagesContainerPage();
      classUnderTest0.goToEditCurrentUserPagesContainerPage();
      Username username0 = Username.FOO;
      Name name0 = Name.MARK;
      Email email0 = Email.FOO;
      UserPassword userPassword0 = UserPassword.FOO;
      classUnderTest0.editUserAddEditUserContainerPage(username0, name0, email0, userPassword0);
      classUnderTest0.goToRolesAddEditUserContainerPage();
      classUnderTest0.goToDashboardPermissionsContainerPage();
      classUnderTest0.goToSiteDashboardContainerPage();
      classUnderTest0.addLinkPagesContainerPage();
      classUnderTest0.goToEditCurrentUserAddEditLinkContainerPage();
  }

  //Test case number: 17
  /*
   * 7 covered goals:
   * Goal 1. main.ClassUnderTest.addLoginWidgetsContainerPage()V: Line 2758
   * Goal 2. main.ClassUnderTest.goToEditCurrentUserAddEditLoginWidgetContainerPage()V: Line 3227
   * Goal 3. main.ClassUnderTest.goToEditCurrentUserDashboardContainerPage()V: Line 726
   * Goal 4. main.ClassUnderTest.goToSiteUserListContainerPage()V: Line 971
   * Goal 5. main.ClassUnderTest.goToUserListAddEditUserContainerPage()V: Line 1397
   * Goal 6. main.ClassUnderTest.goToUsersAddEditUserContainerPage()V: Line 1409
   * Goal 7. main.ClassUnderTest.goToWidgetsPagesContainerPage()V: Line 1982
   */

  @Test(timeout = 1001000)
  public void test17()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      classUnderTest0.goToEditCurrentUserDashboardContainerPage();
      classUnderTest0.goToUserListAddEditUserContainerPage();
      classUnderTest0.goToSiteUserListContainerPage();
      classUnderTest0.goToWidgetsPagesContainerPage();
      classUnderTest0.addLoginWidgetsContainerPage();
      classUnderTest0.goToEditCurrentUserAddEditLoginWidgetContainerPage();
      classUnderTest0.goToUsersAddEditUserContainerPage();
  }

  //Test case number: 18
  /*
   * 9 covered goals:
   * Goal 1. main.ClassUnderTest.addPagePagesContainerPage()V: Line 1747
   * Goal 2. main.ClassUnderTest.goToDashboardDashboardContainerPage()V: Line 713
   * Goal 3. main.ClassUnderTest.goToEditCurrentUserAddEditPageContainerPage()V: Line 2255
   * Goal 4. main.ClassUnderTest.goToSettingsAddEditUserContainerPage()V: Line 1372
   * Goal 5. main.ClassUnderTest.goToSiteDashboardContainerPage()V: Line 763
   * Goal 6. main.ClassUnderTest.goToSitePagesContainerPage()V: Line 1958
   * Goal 7. main.ClassUnderTest.goToSiteWidgetsContainerPage()V: Line 3000
   * Goal 8. main.ClassUnderTest.goToWidgetsPagesContainerPage()V: Line 1982
   * Goal 9. main.ClassUnderTest.saveSettingsUserSettingsContainerPage()V: Line 1667
   */

  @Test(timeout = 1001000)
  public void test18()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      classUnderTest0.goToDashboardDashboardContainerPage();
      classUnderTest0.goToSiteDashboardContainerPage();
      classUnderTest0.goToSitePagesContainerPage();
      classUnderTest0.goToWidgetsPagesContainerPage();
      classUnderTest0.goToSiteWidgetsContainerPage();
      classUnderTest0.addPagePagesContainerPage();
      classUnderTest0.goToEditCurrentUserAddEditPageContainerPage();
      classUnderTest0.goToSettingsAddEditUserContainerPage();
      classUnderTest0.saveSettingsUserSettingsContainerPage();
  }

  //Test case number: 19
  /*
   * 13 covered goals:
   * Goal 1. main.ClassUnderTest.addFeedWidgetDashboardContainerPage(Lcustom_classes/WidgetFeedTitle;Lcustom_classes/WidgetFeedUrl;Lcustom_classes/WidgetFeedNumberOfPosts;Lcustom_classes/WidgetFeedPostContent;)V: Line 515
   * Goal 2. main.ClassUnderTest.addLocationWidgetDashboardContainerPage(Lcustom_classes/WidgetLocation;Lcustom_classes/WidgetUnit;)V: Line 533
   * Goal 3. main.ClassUnderTest.deleteLocationWidgetDashboardContainerPage(Lcustom_classes/Id;)V: Line 575
   * Goal 4. main.ClassUnderTest.goToEditCurrentUserPagesContainerPage()V: Line 1914
   * Goal 5. main.ClassUnderTest.goToEditCurrentUserWidgetsContainerPage()V: Line 2955
   * Goal 6. main.ClassUnderTest.goToSettingsAddEditUserContainerPage()V: Line 1372
   * Goal 7. main.ClassUnderTest.goToSiteAddEditUserContainerPage()V: Line 1385
   * Goal 8. main.ClassUnderTest.goToSitePagesContainerPage()V: Line 1958
   * Goal 9. main.ClassUnderTest.goToSiteUserListContainerPage()V: Line 971
   * Goal 10. main.ClassUnderTest.goToSiteUserSettingsContainerPage()V: Line 1628
   * Goal 11. main.ClassUnderTest.goToUsersDashboardContainerPage()V: Line 775
   * Goal 12. main.ClassUnderTest.goToWidgetsPagesContainerPage()V: Line 1982
   * Goal 13. main.ClassUnderTest.publishAllPagesAndLinksPagesContainerPage()V: Line 2047
   */

  @Test(timeout = 1001000)
  public void test19()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      int int0 = 901;
      Id id0 = new Id(int0);
      WidgetLocation widgetLocation0 = WidgetLocation.GENOA;
      WidgetUnit widgetUnit0 = WidgetUnit.IMPERIAL;
      classUnderTest0.addLocationWidgetDashboardContainerPage(widgetLocation0, widgetUnit0);
      WidgetFeedTitle widgetFeedTitle0 = WidgetFeedTitle.PAGEKITNEWS;
      WidgetFeedUrl widgetFeedUrl0 = WidgetFeedUrl.SPORT;
      WidgetFeedNumberOfPosts widgetFeedNumberOfPosts0 = new WidgetFeedNumberOfPosts(int0);
      WidgetFeedPostContent widgetFeedPostContent0 = WidgetFeedPostContent.SHOWFIRSTPOST;
      classUnderTest0.addFeedWidgetDashboardContainerPage(widgetFeedTitle0, widgetFeedUrl0, widgetFeedNumberOfPosts0, widgetFeedPostContent0);
      classUnderTest0.deleteLocationWidgetDashboardContainerPage(id0);
      classUnderTest0.goToUsersDashboardContainerPage();
      classUnderTest0.goToSiteUserListContainerPage();
      classUnderTest0.goToEditCurrentUserPagesContainerPage();
      classUnderTest0.goToSiteAddEditUserContainerPage();
      classUnderTest0.goToSitePagesContainerPage();
      classUnderTest0.goToWidgetsPagesContainerPage();
      classUnderTest0.goToEditCurrentUserWidgetsContainerPage();
      classUnderTest0.goToSettingsAddEditUserContainerPage();
      classUnderTest0.goToSiteUserSettingsContainerPage();
      classUnderTest0.publishAllPagesAndLinksPagesContainerPage();
  }

  //Test case number: 20
  /*
   * 14 covered goals:
   * Goal 1. main.ClassUnderTest.addUserUserListContainerPage()V: Line 812
   * Goal 2. main.ClassUnderTest.blockUserUserListContainerPage(Lcustom_classes/Id;)V: Line 834
   * Goal 3. main.ClassUnderTest.cancelOperationDeleteItemPage()V: Line 257
   * Goal 4. main.ClassUnderTest.confirmOperationDeleteItemPage()V: Line 304
   * Goal 5. main.ClassUnderTest.deleteAdminUserUserListContainerPage(Lcustom_classes/Id;)V: Line 864
   * Goal 6. main.ClassUnderTest.goToDashboardAddEditUserContainerPage()V: Line 1320
   * Goal 7. main.ClassUnderTest.goToEditCurrentUserPagesContainerPage()V: Line 1914
   * Goal 8. main.ClassUnderTest.goToMenuWidgetsContainerPage(Lcustom_classes/WidgetMenus;)V: Line 2971
   * Goal 9. main.ClassUnderTest.goToSiteDashboardContainerPage()V: Line 763
   * Goal 10. main.ClassUnderTest.goToSiteUserListContainerPage()V: Line 971
   * Goal 11. main.ClassUnderTest.goToUserListAddEditUserContainerPage()V: Line 1397
   * Goal 12. main.ClassUnderTest.goToUserListUserListContainerPage()V: Line 983
   * Goal 13. main.ClassUnderTest.goToUsersDashboardContainerPage()V: Line 775
   * Goal 14. main.ClassUnderTest.goToWidgetsPagesContainerPage()V: Line 1982
   */

  @Test(timeout = 1001000)
  public void test20()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      classUnderTest0.goToSiteDashboardContainerPage();
      classUnderTest0.goToEditCurrentUserPagesContainerPage();
      classUnderTest0.goToUserListAddEditUserContainerPage();
      classUnderTest0.addUserUserListContainerPage();
      classUnderTest0.goToDashboardAddEditUserContainerPage();
      classUnderTest0.goToUsersDashboardContainerPage();
      int int0 = 297;
      Id id0 = new Id(int0);
      classUnderTest0.deleteAdminUserUserListContainerPage(id0);
      classUnderTest0.confirmOperationDeleteItemPage();
      classUnderTest0.goToUserListUserListContainerPage();
      classUnderTest0.goToUserListUserListContainerPage();
      classUnderTest0.blockUserUserListContainerPage(id0);
      classUnderTest0.deleteAdminUserUserListContainerPage(id0);
      classUnderTest0.cancelOperationDeleteItemPage();
      classUnderTest0.goToSiteUserListContainerPage();
      classUnderTest0.goToWidgetsPagesContainerPage();
      WidgetMenus widgetMenus0 = WidgetMenus.ALL;
      classUnderTest0.goToMenuWidgetsContainerPage(widgetMenus0);
  }

  //Test case number: 21
  /*
   * 10 covered goals:
   * Goal 1. main.ClassUnderTest.addExistingMenuPagesContainerPage(Lcustom_classes/SiteMenus;)V: Line 1686
   * Goal 2. main.ClassUnderTest.addLinkPagesContainerPage()V: Line 1706
   * Goal 3. main.ClassUnderTest.cancelOperationAddEditItemPage()V: Line 426
   * Goal 4. main.ClassUnderTest.goToMenuPagesContainerPage(Lcustom_classes/SiteMenus;)V: Line 1929
   * Goal 5. main.ClassUnderTest.goToMetaAddEditLinkContainerPage()V: Line 2668
   * Goal 6. main.ClassUnderTest.goToPagesPagesContainerPage()V: Line 1946
   * Goal 7. main.ClassUnderTest.goToSiteDashboardContainerPage()V: Line 763
   * Goal 8. main.ClassUnderTest.goToUsersAddEditLinkContainerPage()V: Line 2718
   * Goal 9. main.ClassUnderTest.goToUsersUserListContainerPage()V: Line 995
   * Goal 10. main.ClassUnderTest.unpublishAllPagesAndLinksPagesContainerPage()V: Line 2091
   */

  @Test(timeout = 1001000)
  public void test21()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      classUnderTest0.goToSiteDashboardContainerPage();
      classUnderTest0.goToPagesPagesContainerPage();
      classUnderTest0.unpublishAllPagesAndLinksPagesContainerPage();
      SiteMenus siteMenus0 = SiteMenus.MAIN;
      classUnderTest0.addExistingMenuPagesContainerPage(siteMenus0);
      classUnderTest0.cancelOperationAddEditItemPage();
      classUnderTest0.goToMenuPagesContainerPage(siteMenus0);
      classUnderTest0.addLinkPagesContainerPage();
      classUnderTest0.goToMetaAddEditLinkContainerPage();
      classUnderTest0.goToUsersAddEditLinkContainerPage();
      classUnderTest0.goToUsersUserListContainerPage();
  }

  //Test case number: 22
  /*
   * 20 covered goals:
   * Goal 1. main.ClassUnderTest.addFeedWidgetDashboardContainerPage(Lcustom_classes/WidgetFeedTitle;Lcustom_classes/WidgetFeedUrl;Lcustom_classes/WidgetFeedNumberOfPosts;Lcustom_classes/WidgetFeedPostContent;)V: Line 515
   * Goal 2. main.ClassUnderTest.addUserWidgetDashboardContainerPage(Lcustom_classes/WidgetUserType;Lcustom_classes/WidgetUserDisplay;Lcustom_classes/WidgetTotalUser;Lcustom_classes/WidgetNumberOfUsers;)V: Line 553
   * Goal 3. main.ClassUnderTest.editPagePagesContainerPage(Lcustom_classes/SitePages;)V: Line 1884
   * Goal 4. main.ClassUnderTest.editUserWidgetDashboardContainerPage(Lcustom_classes/Id;Lcustom_classes/WidgetUserType;Lcustom_classes/WidgetUserDisplay;Lcustom_classes/WidgetTotalUser;Lcustom_classes/WidgetNumberOfUsers;)V: Line 696
   * Goal 5. main.ClassUnderTest.goToEditCurrentUserDashboardContainerPage()V: Line 726
   * Goal 6. main.ClassUnderTest.goToEditCurrentUserPagesContainerPage()V: Line 1914
   * Goal 7. main.ClassUnderTest.goToEditCurrentUserUserSettingsContainerPage()V: Line 1576
   * Goal 8. main.ClassUnderTest.goToEditCurrentUserWidgetsContainerPage()V: Line 2955
   * Goal 9. main.ClassUnderTest.goToMetaAddEditPageContainerPage()V: Line 2268
   * Goal 10. main.ClassUnderTest.goToPermissionsAddEditUserContainerPage()V: Line 1346
   * Goal 11. main.ClassUnderTest.goToPermissionsPermissionsContainerPage()V: Line 1472
   * Goal 12. main.ClassUnderTest.goToPermissionsUserListContainerPage()V: Line 932
   * Goal 13. main.ClassUnderTest.goToSettingsAddEditUserContainerPage()V: Line 1372
   * Goal 14. main.ClassUnderTest.goToSiteAddEditUserContainerPage()V: Line 1385
   * Goal 15. main.ClassUnderTest.goToSitePagesContainerPage()V: Line 1958
   * Goal 16. main.ClassUnderTest.goToSitePermissionsContainerPage()V: Line 1511
   * Goal 17. main.ClassUnderTest.goToUsersAddEditUserContainerPage()V: Line 1409
   * Goal 18. main.ClassUnderTest.goToWidgetsAddEditPageContainerPage()V: Line 2317
   * Goal 19. main.ClassUnderTest.goToWidgetsPagesContainerPage()V: Line 1982
   * Goal 20. main.ClassUnderTest.publishAllPagesAndLinksPagesContainerPage()V: Line 2047
   */

  @Test(timeout = 1001000)
  public void test22()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      WidgetFeedTitle widgetFeedTitle0 = WidgetFeedTitle.SPORTNEWS;
      WidgetFeedUrl widgetFeedUrl0 = WidgetFeedUrl.PAGEKIT;
      int int0 = 918;
      WidgetFeedNumberOfPosts widgetFeedNumberOfPosts0 = new WidgetFeedNumberOfPosts(int0);
      WidgetFeedPostContent widgetFeedPostContent0 = WidgetFeedPostContent.SHOWALLPOSTS;
      classUnderTest0.addFeedWidgetDashboardContainerPage(widgetFeedTitle0, widgetFeedUrl0, widgetFeedNumberOfPosts0, widgetFeedPostContent0);
      WidgetFeedTitle widgetFeedTitle1 = WidgetFeedTitle.PAGEKITNEWS;
      WidgetFeedUrl widgetFeedUrl1 = WidgetFeedUrl.PAGEKIT;
      classUnderTest0.addFeedWidgetDashboardContainerPage(widgetFeedTitle1, widgetFeedUrl1, widgetFeedNumberOfPosts0, widgetFeedPostContent0);
      Id id0 = new Id(int0);
      WidgetUserType widgetUserType0 = WidgetUserType.LASTREGISTERED;
      WidgetUserDisplay widgetUserDisplay0 = WidgetUserDisplay.LIST;
      WidgetTotalUser widgetTotalUser0 = WidgetTotalUser.HIDE;
      WidgetNumberOfUsers widgetNumberOfUsers0 = WidgetNumberOfUsers.EIGHTEEN;
      classUnderTest0.addUserWidgetDashboardContainerPage(widgetUserType0, widgetUserDisplay0, widgetTotalUser0, widgetNumberOfUsers0);
      WidgetUserDisplay widgetUserDisplay1 = WidgetUserDisplay.LIST;
      WidgetTotalUser widgetTotalUser1 = WidgetTotalUser.SHOW;
      classUnderTest0.editUserWidgetDashboardContainerPage(id0, widgetUserType0, widgetUserDisplay1, widgetTotalUser1, widgetNumberOfUsers0);
      classUnderTest0.goToEditCurrentUserDashboardContainerPage();
      classUnderTest0.goToPermissionsAddEditUserContainerPage();
      classUnderTest0.goToSitePermissionsContainerPage();
      classUnderTest0.publishAllPagesAndLinksPagesContainerPage();
      SitePages sitePages0 = SitePages.HOME;
      classUnderTest0.goToSitePagesContainerPage();
      classUnderTest0.editPagePagesContainerPage(sitePages0);
      classUnderTest0.goToMetaAddEditPageContainerPage();
      classUnderTest0.goToWidgetsAddEditPageContainerPage();
      classUnderTest0.goToEditCurrentUserWidgetsContainerPage();
      classUnderTest0.goToSettingsAddEditUserContainerPage();
      classUnderTest0.goToEditCurrentUserUserSettingsContainerPage();
      classUnderTest0.goToUsersAddEditUserContainerPage();
      classUnderTest0.goToPermissionsUserListContainerPage();
      classUnderTest0.goToPermissionsPermissionsContainerPage();
      classUnderTest0.goToSitePermissionsContainerPage();
      classUnderTest0.goToEditCurrentUserPagesContainerPage();
      classUnderTest0.goToSiteAddEditUserContainerPage();
      classUnderTest0.goToWidgetsPagesContainerPage();
  }

  //Test case number: 23
  /*
   * 6 covered goals:
   * Goal 1. main.ClassUnderTest.addFeedWidgetDashboardContainerPage(Lcustom_classes/WidgetFeedTitle;Lcustom_classes/WidgetFeedUrl;Lcustom_classes/WidgetFeedNumberOfPosts;Lcustom_classes/WidgetFeedPostContent;)V: Line 515
   * Goal 2. main.ClassUnderTest.addMenuWidgetsContainerPage()V: Line 2772
   * Goal 3. main.ClassUnderTest.goToPagesAddEditMenuWidgetContainerPage()V: Line 3517
   * Goal 4. main.ClassUnderTest.goToSiteUserListContainerPage()V: Line 971
   * Goal 5. main.ClassUnderTest.goToUsersDashboardContainerPage()V: Line 775
   * Goal 6. main.ClassUnderTest.goToWidgetsPagesContainerPage()V: Line 1982
   */

  @Test(timeout = 1001000)
  public void test23()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      WidgetFeedTitle widgetFeedTitle0 = WidgetFeedTitle.WEATHER;
      WidgetFeedUrl widgetFeedUrl0 = WidgetFeedUrl.WEATHER;
      int int0 = 1041;
      WidgetFeedNumberOfPosts widgetFeedNumberOfPosts0 = new WidgetFeedNumberOfPosts(int0);
      WidgetFeedPostContent widgetFeedPostContent0 = WidgetFeedPostContent.DONTSHOW;
      classUnderTest0.addFeedWidgetDashboardContainerPage(widgetFeedTitle0, widgetFeedUrl0, widgetFeedNumberOfPosts0, widgetFeedPostContent0);
      classUnderTest0.goToUsersDashboardContainerPage();
      classUnderTest0.goToSiteUserListContainerPage();
      classUnderTest0.goToWidgetsPagesContainerPage();
      classUnderTest0.addMenuWidgetsContainerPage();
      classUnderTest0.goToPagesAddEditMenuWidgetContainerPage();
  }

  //Test case number: 24
  /*
   * 8 covered goals:
   * Goal 1. main.ClassUnderTest.addPagePagesContainerPage()V: Line 1747
   * Goal 2. main.ClassUnderTest.addUserWidgetDashboardContainerPage(Lcustom_classes/WidgetUserType;Lcustom_classes/WidgetUserDisplay;Lcustom_classes/WidgetTotalUser;Lcustom_classes/WidgetNumberOfUsers;)V: Line 553
   * Goal 3. main.ClassUnderTest.goToEditCurrentUserWidgetsContainerPage()V: Line 2955
   * Goal 4. main.ClassUnderTest.goToPagesAddEditPageContainerPage()V: Line 2281
   * Goal 5. main.ClassUnderTest.goToRolesAddEditUserContainerPage()V: Line 1359
   * Goal 6. main.ClassUnderTest.goToSiteDashboardContainerPage()V: Line 763
   * Goal 7. main.ClassUnderTest.goToSitePagesContainerPage()V: Line 1958
   * Goal 8. main.ClassUnderTest.goToWidgetsPagesContainerPage()V: Line 1982
   */

  @Test(timeout = 1001000)
  public void test24()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      WidgetUserType widgetUserType0 = WidgetUserType.LASTREGISTERED;
      WidgetUserDisplay widgetUserDisplay0 = WidgetUserDisplay.THUMBNAIL;
      WidgetTotalUser widgetTotalUser0 = WidgetTotalUser.HIDE;
      WidgetNumberOfUsers widgetNumberOfUsers0 = WidgetNumberOfUsers.SIX;
      classUnderTest0.addUserWidgetDashboardContainerPage(widgetUserType0, widgetUserDisplay0, widgetTotalUser0, widgetNumberOfUsers0);
      classUnderTest0.goToSiteDashboardContainerPage();
      classUnderTest0.addPagePagesContainerPage();
      classUnderTest0.goToPagesAddEditPageContainerPage();
      classUnderTest0.goToSitePagesContainerPage();
      classUnderTest0.goToWidgetsPagesContainerPage();
      classUnderTest0.goToEditCurrentUserWidgetsContainerPage();
      classUnderTest0.goToRolesAddEditUserContainerPage();
  }

  //Test case number: 25
  /*
   * 16 covered goals:
   * Goal 1. main.ClassUnderTest.addLocationWidgetDashboardContainerPage(Lcustom_classes/WidgetLocation;Lcustom_classes/WidgetUnit;)V: Line 533
   * Goal 2. main.ClassUnderTest.addUserUserListContainerPage()V: Line 812
   * Goal 3. main.ClassUnderTest.cancelOperationDeleteItemPage()V: Line 257
   * Goal 4. main.ClassUnderTest.deleteAdminUserUserListContainerPage(Lcustom_classes/Id;)V: Line 864
   * Goal 5. main.ClassUnderTest.editUserAddEditUserContainerPage(Lcustom_classes/Username;Lcustom_classes/Name;Lcustom_classes/Email;Lcustom_classes/UserPassword;)V: Line 1303
   * Goal 6. main.ClassUnderTest.editUserWidgetDashboardContainerPage(Lcustom_classes/Id;Lcustom_classes/WidgetUserType;Lcustom_classes/WidgetUserDisplay;Lcustom_classes/WidgetTotalUser;Lcustom_classes/WidgetNumberOfUsers;)V: Line 696
   * Goal 7. main.ClassUnderTest.goToDashboardUserListContainerPage()V: Line 906
   * Goal 8. main.ClassUnderTest.goToEditCurrentUserDashboardContainerPage()V: Line 726
   * Goal 9. main.ClassUnderTest.goToEditCurrentUserUserListContainerPage()V: Line 919
   * Goal 10. main.ClassUnderTest.goToPermissionsAddEditUserContainerPage()V: Line 1346
   * Goal 11. main.ClassUnderTest.goToRolesUserSettingsContainerPage()V: Line 1602
   * Goal 12. main.ClassUnderTest.goToSettingsPermissionsContainerPage()V: Line 1498
   * Goal 13. main.ClassUnderTest.goToUserListAddEditUserContainerPage()V: Line 1397
   * Goal 14. main.ClassUnderTest.goToUserListUserListContainerPage()V: Line 983
   * Goal 15. main.ClassUnderTest.goToUsersDashboardContainerPage()V: Line 775
   * Goal 16. main.ClassUnderTest.goToUsersUserListContainerPage()V: Line 995
   */

  @Test(timeout = 1001000)
  public void test25()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      classUnderTest0.goToEditCurrentUserDashboardContainerPage();
      classUnderTest0.goToUserListAddEditUserContainerPage();
      classUnderTest0.goToDashboardUserListContainerPage();
      int int0 = (-1917);
      Id id0 = new Id(int0);
      WidgetUserType widgetUserType0 = WidgetUserType.LASTREGISTERED;
      WidgetUserDisplay widgetUserDisplay0 = WidgetUserDisplay.THUMBNAIL;
      WidgetTotalUser widgetTotalUser0 = WidgetTotalUser.HIDE;
      WidgetNumberOfUsers widgetNumberOfUsers0 = WidgetNumberOfUsers.SIX;
      classUnderTest0.editUserWidgetDashboardContainerPage(id0, widgetUserType0, widgetUserDisplay0, widgetTotalUser0, widgetNumberOfUsers0);
      WidgetLocation widgetLocation0 = WidgetLocation.MILANO;
      WidgetUnit widgetUnit0 = WidgetUnit.IMPERIAL;
      classUnderTest0.addLocationWidgetDashboardContainerPage(widgetLocation0, widgetUnit0);
      classUnderTest0.goToUsersDashboardContainerPage();
      classUnderTest0.deleteAdminUserUserListContainerPage(id0);
      classUnderTest0.cancelOperationDeleteItemPage();
      classUnderTest0.goToUserListUserListContainerPage();
      classUnderTest0.goToEditCurrentUserUserListContainerPage();
      Username username0 = Username.FOO;
      Name name0 = Name.MARK;
      Email email0 = Email.ASD;
      UserPassword userPassword0 = UserPassword.ADMIN;
      classUnderTest0.editUserAddEditUserContainerPage(username0, name0, email0, userPassword0);
      classUnderTest0.goToUserListAddEditUserContainerPage();
      classUnderTest0.goToUsersUserListContainerPage();
      classUnderTest0.addUserUserListContainerPage();
      classUnderTest0.goToPermissionsAddEditUserContainerPage();
      classUnderTest0.goToSettingsPermissionsContainerPage();
      classUnderTest0.goToRolesUserSettingsContainerPage();
  }

  //Test case number: 26
  /*
   * 8 covered goals:
   * Goal 1. main.ClassUnderTest.addFeedWidgetDashboardContainerPage(Lcustom_classes/WidgetFeedTitle;Lcustom_classes/WidgetFeedUrl;Lcustom_classes/WidgetFeedNumberOfPosts;Lcustom_classes/WidgetFeedPostContent;)V: Line 515
   * Goal 2. main.ClassUnderTest.addLoginWidgetsContainerPage()V: Line 2758
   * Goal 3. main.ClassUnderTest.addUserWidgetDashboardContainerPage(Lcustom_classes/WidgetUserType;Lcustom_classes/WidgetUserDisplay;Lcustom_classes/WidgetTotalUser;Lcustom_classes/WidgetNumberOfUsers;)V: Line 553
   * Goal 4. main.ClassUnderTest.confirmOperationDeleteItemPage()V: Line 289
   * Goal 5. main.ClassUnderTest.deleteUserOrFeedWidgetDashboardContainerPage(Lcustom_classes/Id;)V: Line 603
   * Goal 6. main.ClassUnderTest.goToSiteAddEditLoginWidgetContainerPage()V: Line 3265
   * Goal 7. main.ClassUnderTest.goToSiteDashboardContainerPage()V: Line 763
   * Goal 8. main.ClassUnderTest.goToWidgetsPagesContainerPage()V: Line 1982
   */

  @Test(timeout = 1001000)
  public void test26()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      int int0 = 566;
      Id id0 = new Id(int0);
      classUnderTest0.deleteUserOrFeedWidgetDashboardContainerPage(id0);
      classUnderTest0.confirmOperationDeleteItemPage();
      WidgetUserType widgetUserType0 = WidgetUserType.LOGGEDIN;
      WidgetUserDisplay widgetUserDisplay0 = WidgetUserDisplay.LIST;
      WidgetTotalUser widgetTotalUser0 = WidgetTotalUser.SHOW;
      WidgetNumberOfUsers widgetNumberOfUsers0 = WidgetNumberOfUsers.EIGHTEEN;
      classUnderTest0.addUserWidgetDashboardContainerPage(widgetUserType0, widgetUserDisplay0, widgetTotalUser0, widgetNumberOfUsers0);
      WidgetFeedTitle widgetFeedTitle0 = WidgetFeedTitle.PAGEKITNEWS;
      WidgetFeedUrl widgetFeedUrl0 = WidgetFeedUrl.WEATHER;
      int int1 = 3005;
      WidgetFeedNumberOfPosts widgetFeedNumberOfPosts0 = new WidgetFeedNumberOfPosts(int1);
      WidgetFeedPostContent widgetFeedPostContent0 = WidgetFeedPostContent.SHOWFIRSTPOST;
      classUnderTest0.addFeedWidgetDashboardContainerPage(widgetFeedTitle0, widgetFeedUrl0, widgetFeedNumberOfPosts0, widgetFeedPostContent0);
      classUnderTest0.goToSiteDashboardContainerPage();
      classUnderTest0.goToWidgetsPagesContainerPage();
      classUnderTest0.addLoginWidgetsContainerPage();
      classUnderTest0.goToSiteAddEditLoginWidgetContainerPage();
  }

  //Test case number: 27
  /*
   * 14 covered goals:
   * Goal 1. main.ClassUnderTest.addFeedWidgetDashboardContainerPage(Lcustom_classes/WidgetFeedTitle;Lcustom_classes/WidgetFeedUrl;Lcustom_classes/WidgetFeedNumberOfPosts;Lcustom_classes/WidgetFeedPostContent;)V: Line 515
   * Goal 2. main.ClassUnderTest.addLocationWidgetDashboardContainerPage(Lcustom_classes/WidgetLocation;Lcustom_classes/WidgetUnit;)V: Line 533
   * Goal 3. main.ClassUnderTest.addPagePagesContainerPage()V: Line 1747
   * Goal 4. main.ClassUnderTest.editLocationWidgetDashboardContainerPage(Lcustom_classes/Id;Lcustom_classes/WidgetLocation;Lcustom_classes/WidgetUnit;)V: Line 664
   * Goal 5. main.ClassUnderTest.goToDashboardDashboardContainerPage()V: Line 713
   * Goal 6. main.ClassUnderTest.goToDashboardPagesContainerPage()V: Line 1901
   * Goal 7. main.ClassUnderTest.goToDashboardPermissionsContainerPage()V: Line 1446
   * Goal 8. main.ClassUnderTest.goToEditCurrentUserAddEditUserContainerPage()V: Line 1333
   * Goal 9. main.ClassUnderTest.goToEditCurrentUserDashboardContainerPage()V: Line 726
   * Goal 10. main.ClassUnderTest.goToPermissionsUserListContainerPage()V: Line 932
   * Goal 11. main.ClassUnderTest.goToSiteAddEditPageContainerPage()V: Line 2293
   * Goal 12. main.ClassUnderTest.goToSiteDashboardContainerPage()V: Line 763
   * Goal 13. main.ClassUnderTest.goToSiteUserListContainerPage()V: Line 971
   * Goal 14. main.ClassUnderTest.goToUserListAddEditUserContainerPage()V: Line 1397
   */

  @Test(timeout = 1001000)
  public void test27()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      int int0 = (-3145);
      Id id0 = new Id(int0);
      classUnderTest0.goToEditCurrentUserDashboardContainerPage();
      classUnderTest0.goToUserListAddEditUserContainerPage();
      classUnderTest0.goToPermissionsUserListContainerPage();
      classUnderTest0.goToDashboardPermissionsContainerPage();
      WidgetFeedTitle widgetFeedTitle0 = WidgetFeedTitle.SPORTNEWS;
      WidgetFeedUrl widgetFeedUrl0 = WidgetFeedUrl.SPORT;
      int int1 = (-507);
      WidgetFeedNumberOfPosts widgetFeedNumberOfPosts0 = new WidgetFeedNumberOfPosts(int1);
      WidgetFeedPostContent widgetFeedPostContent0 = WidgetFeedPostContent.DONTSHOW;
      classUnderTest0.addFeedWidgetDashboardContainerPage(widgetFeedTitle0, widgetFeedUrl0, widgetFeedNumberOfPosts0, widgetFeedPostContent0);
      classUnderTest0.goToDashboardDashboardContainerPage();
      classUnderTest0.goToEditCurrentUserDashboardContainerPage();
      classUnderTest0.goToEditCurrentUserAddEditUserContainerPage();
      classUnderTest0.goToUserListAddEditUserContainerPage();
      classUnderTest0.goToSiteUserListContainerPage();
      classUnderTest0.goToDashboardPagesContainerPage();
      WidgetUnit widgetUnit0 = WidgetUnit.METRIC;
      WidgetLocation widgetLocation0 = WidgetLocation.MILANO;
      classUnderTest0.editLocationWidgetDashboardContainerPage(id0, widgetLocation0, widgetUnit0);
      classUnderTest0.editLocationWidgetDashboardContainerPage(id0, widgetLocation0, widgetUnit0);
      WidgetLocation widgetLocation1 = WidgetLocation.TRENTO;
      WidgetUnit widgetUnit1 = WidgetUnit.METRIC;
      classUnderTest0.addLocationWidgetDashboardContainerPage(widgetLocation1, widgetUnit1);
      classUnderTest0.goToSiteDashboardContainerPage();
      classUnderTest0.addPagePagesContainerPage();
      classUnderTest0.goToSiteAddEditPageContainerPage();
  }

  //Test case number: 28
  /*
   * 10 covered goals:
   * Goal 1. main.ClassUnderTest.addMenuWidgetsContainerPage()V: Line 2772
   * Goal 2. main.ClassUnderTest.addUserUserListContainerPage()V: Line 812
   * Goal 3. main.ClassUnderTest.goToPermissionsUserListContainerPage()V: Line 932
   * Goal 4. main.ClassUnderTest.goToRolesUserListContainerPage()V: Line 945
   * Goal 5. main.ClassUnderTest.goToSitePermissionsContainerPage()V: Line 1511
   * Goal 6. main.ClassUnderTest.goToUserListAddEditUserContainerPage()V: Line 1397
   * Goal 7. main.ClassUnderTest.goToUserListPermissionsContainerPage()V: Line 1523
   * Goal 8. main.ClassUnderTest.goToUserListUserListContainerPage()V: Line 983
   * Goal 9. main.ClassUnderTest.goToUsersDashboardContainerPage()V: Line 775
   * Goal 10. main.ClassUnderTest.goToWidgetsPagesContainerPage()V: Line 1982
   */

  @Test(timeout = 1001000)
  public void test28()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      classUnderTest0.goToUsersDashboardContainerPage();
      classUnderTest0.goToPermissionsUserListContainerPage();
      classUnderTest0.goToUserListPermissionsContainerPage();
      classUnderTest0.goToUserListUserListContainerPage();
      classUnderTest0.addUserUserListContainerPage();
      classUnderTest0.goToUserListAddEditUserContainerPage();
      classUnderTest0.goToRolesUserListContainerPage();
      classUnderTest0.goToSitePermissionsContainerPage();
      classUnderTest0.goToWidgetsPagesContainerPage();
      classUnderTest0.addMenuWidgetsContainerPage();
  }

  //Test case number: 29
  /*
   * 11 covered goals:
   * Goal 1. main.ClassUnderTest.addFeedWidgetDashboardContainerPage(Lcustom_classes/WidgetFeedTitle;Lcustom_classes/WidgetFeedUrl;Lcustom_classes/WidgetFeedNumberOfPosts;Lcustom_classes/WidgetFeedPostContent;)V: Line 515
   * Goal 2. main.ClassUnderTest.cancelOperationDeleteItemPage()V: Line 252
   * Goal 3. main.ClassUnderTest.deleteUserOrFeedWidgetDashboardContainerPage(Lcustom_classes/Id;)V: Line 603
   * Goal 4. main.ClassUnderTest.editUserAddEditUserContainerPage(Lcustom_classes/Username;Lcustom_classes/Name;Lcustom_classes/Email;Lcustom_classes/UserPassword;)V: Line 1303
   * Goal 5. main.ClassUnderTest.goToDashboardUserListContainerPage()V: Line 906
   * Goal 6. main.ClassUnderTest.goToEditCurrentUserUserListContainerPage()V: Line 919
   * Goal 7. main.ClassUnderTest.goToEditUserDashboardContainerPage(Lcustom_classes/Id;)V: Line 746
   * Goal 8. main.ClassUnderTest.goToSiteAddEditUserContainerPage()V: Line 1385
   * Goal 9. main.ClassUnderTest.goToUsersAddEditUserContainerPage()V: Line 1409
   * Goal 10. main.ClassUnderTest.goToUsersWidgetsContainerPage()V: Line 3012
   * Goal 11. main.ClassUnderTest.goToWidgetsPagesContainerPage()V: Line 1982
   */

  @Test(timeout = 1001000)
  public void test29()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      int int0 = (-651);
      Id id0 = new Id(int0);
      classUnderTest0.goToEditUserDashboardContainerPage(id0);
      Username username0 = Username.FOO;
      Name name0 = Name.JOHN;
      Email email0 = Email.ASD;
      UserPassword userPassword0 = UserPassword.ADMIN;
      classUnderTest0.editUserAddEditUserContainerPage(username0, name0, email0, userPassword0);
      classUnderTest0.goToUsersAddEditUserContainerPage();
      classUnderTest0.goToEditCurrentUserUserListContainerPage();
      classUnderTest0.goToSiteAddEditUserContainerPage();
      classUnderTest0.goToWidgetsPagesContainerPage();
      classUnderTest0.goToUsersWidgetsContainerPage();
      classUnderTest0.goToDashboardUserListContainerPage();
      WidgetFeedTitle widgetFeedTitle0 = WidgetFeedTitle.PAGEKITNEWS;
      WidgetFeedUrl widgetFeedUrl0 = WidgetFeedUrl.WEATHER;
      WidgetFeedNumberOfPosts widgetFeedNumberOfPosts0 = new WidgetFeedNumberOfPosts(int0);
      WidgetFeedPostContent widgetFeedPostContent0 = WidgetFeedPostContent.SHOWFIRSTPOST;
      classUnderTest0.addFeedWidgetDashboardContainerPage(widgetFeedTitle0, widgetFeedUrl0, widgetFeedNumberOfPosts0, widgetFeedPostContent0);
      classUnderTest0.deleteUserOrFeedWidgetDashboardContainerPage(id0);
      classUnderTest0.cancelOperationDeleteItemPage();
  }

  //Test case number: 30
  /*
   * 12 covered goals:
   * Goal 1. main.ClassUnderTest.addLoginWidgetsContainerPage()V: Line 2758
   * Goal 2. main.ClassUnderTest.addMenuPagesContainerPage(Lcustom_classes/SiteMenus;)V: Line 1727
   * Goal 3. main.ClassUnderTest.cancelOperationAddEditItemPage()V: Line 426
   * Goal 4. main.ClassUnderTest.goToEditCurrentUserDashboardContainerPage()V: Line 726
   * Goal 5. main.ClassUnderTest.goToPagesPagesContainerPage()V: Line 1946
   * Goal 6. main.ClassUnderTest.goToRolesAddEditUserContainerPage()V: Line 1359
   * Goal 7. main.ClassUnderTest.goToSitePagesContainerPage()V: Line 1958
   * Goal 8. main.ClassUnderTest.goToSitePermissionsContainerPage()V: Line 1511
   * Goal 9. main.ClassUnderTest.goToSiteWidgetsContainerPage()V: Line 3000
   * Goal 10. main.ClassUnderTest.goToWidgetsAddEditLoginWidgetContainerPage()V: Line 3302
   * Goal 11. main.ClassUnderTest.goToWidgetsPagesContainerPage()V: Line 1982
   * Goal 12. main.ClassUnderTest.selectLoginRedirectLinkAddEditLoginWidgetContainerPage()V: Line 3341
   */

  @Test(timeout = 1001000)
  public void test30()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      classUnderTest0.goToEditCurrentUserDashboardContainerPage();
      classUnderTest0.goToRolesAddEditUserContainerPage();
      classUnderTest0.goToSitePermissionsContainerPage();
      SiteMenus siteMenus0 = SiteMenus.SIDE_MENU;
      classUnderTest0.addMenuPagesContainerPage(siteMenus0);
      classUnderTest0.cancelOperationAddEditItemPage();
      classUnderTest0.goToPagesPagesContainerPage();
      classUnderTest0.goToWidgetsPagesContainerPage();
      classUnderTest0.addLoginWidgetsContainerPage();
      classUnderTest0.goToWidgetsAddEditLoginWidgetContainerPage();
      classUnderTest0.goToSiteWidgetsContainerPage();
      classUnderTest0.goToSitePagesContainerPage();
      classUnderTest0.goToWidgetsPagesContainerPage();
      classUnderTest0.addLoginWidgetsContainerPage();
      classUnderTest0.selectLoginRedirectLinkAddEditLoginWidgetContainerPage();
  }

  //Test case number: 31
  /*
   * 8 covered goals:
   * Goal 1. main.ClassUnderTest.addPagePagesContainerPage()V: Line 1747
   * Goal 2. main.ClassUnderTest.deleteAllPagesAndLinksPagesContainerPage()V: Line 1767
   * Goal 3. main.ClassUnderTest.goToSiteUserListContainerPage()V: Line 971
   * Goal 4. main.ClassUnderTest.goToSiteWidgetsContainerPage()V: Line 3000
   * Goal 5. main.ClassUnderTest.goToUsersDashboardContainerPage()V: Line 775
   * Goal 6. main.ClassUnderTest.goToWidgetsAddEditPageContainerPage()V: Line 2317
   * Goal 7. main.ClassUnderTest.goToWidgetsPagesContainerPage()V: Line 1982
   * Goal 8. main.ClassUnderTest.goToWidgetsWidgetsContainerPage()V: Line 3024
   */

  @Test(timeout = 1001000)
  public void test31()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      classUnderTest0.goToUsersDashboardContainerPage();
      classUnderTest0.goToSiteUserListContainerPage();
      classUnderTest0.deleteAllPagesAndLinksPagesContainerPage();
      classUnderTest0.addPagePagesContainerPage();
      classUnderTest0.goToWidgetsAddEditPageContainerPage();
      classUnderTest0.goToSiteWidgetsContainerPage();
      classUnderTest0.goToWidgetsPagesContainerPage();
      classUnderTest0.goToWidgetsWidgetsContainerPage();
  }
}
