/*
 * This file was automatically generated by EvoSuite
 * Fri May 08 08:32:57 GMT 2020
 */

package main;

import org.junit.Test;
import static org.junit.Assert.*;
import custom_classes.Email;
import custom_classes.Extension;
import custom_classes.HTMLSnippets;
import custom_classes.HideInMenu;
import custom_classes.Id;
import custom_classes.Name;
import custom_classes.PageLinkStatus;
import custom_classes.RegistrationUserSettings;
import custom_classes.SiteMenus;
import custom_classes.SitePages;
import custom_classes.UserPassword;
import custom_classes.UserRoles;
import custom_classes.UserStatus;
import custom_classes.Username;
import custom_classes.WidgetFeedNumberOfPosts;
import custom_classes.WidgetFeedPostContent;
import custom_classes.WidgetFeedTitle;
import custom_classes.WidgetFeedUrl;
import custom_classes.WidgetLocation;
import custom_classes.WidgetLoginTitles;
import custom_classes.WidgetMenus;
import custom_classes.WidgetNumberOfUsers;
import custom_classes.WidgetTotalUser;
import custom_classes.WidgetUnit;
import custom_classes.WidgetUserDisplay;
import custom_classes.WidgetUserType;
import main.ClassUnderTest;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, resetStaticState = true) 
public class ClassUnderTest_ESTest extends ClassUnderTest_ESTest_scaffolding {

  //Test case number: 0
  /*
   * 20 covered goals:
   * Goal 1. main.ClassUnderTest.addEditLoginDetailsAddEditLoginWidgetContainerPage(Lcustom_classes/WidgetLoginTitles;Lcustom_classes/PageLinkStatus;)V: Line 3126
   * Goal 2. main.ClassUnderTest.addEditPageAddEditPageContainerPage(Lcustom_classes/SitePages;Lcustom_classes/HTMLSnippets;Lcustom_classes/PageLinkStatus;Lcustom_classes/HideInMenu;)V: Line 2166
   * Goal 3. main.ClassUnderTest.addEditPageRestrictAccessAddEditPageContainerPage(Lcustom_classes/SitePages;Lcustom_classes/HTMLSnippets;Lcustom_classes/PageLinkStatus;Lcustom_classes/UserRoles;Lcustom_classes/HideInMenu;)V: Line 2198
   * Goal 4. main.ClassUnderTest.addLocationWidgetDashboardContainerPage(Lcustom_classes/WidgetLocation;Lcustom_classes/WidgetUnit;)V: Line 533
   * Goal 5. main.ClassUnderTest.addLoginWidgetsContainerPage()V: Line 2758
   * Goal 6. main.ClassUnderTest.addPagePagesContainerPage()V: Line 1747
   * Goal 7. main.ClassUnderTest.addUserUserListContainerPage()V: Line 812
   * Goal 8. main.ClassUnderTest.addUserWidgetDashboardContainerPage(Lcustom_classes/WidgetUserType;Lcustom_classes/WidgetUserDisplay;Lcustom_classes/WidgetTotalUser;Lcustom_classes/WidgetNumberOfUsers;)V: Line 553
   * Goal 9. main.ClassUnderTest.closeOperationAddEditUserContainerPage()V: Line 1285
   * Goal 10. main.ClassUnderTest.goToContentAddEditPageContainerPage()V: Line 2229
   * Goal 11. main.ClassUnderTest.goToEditCurrentUserAddEditLoginWidgetContainerPage()V: Line 3227
   * Goal 12. main.ClassUnderTest.goToRolesAddEditUserContainerPage()V: Line 1359
   * Goal 13. main.ClassUnderTest.goToSettingsAddEditLoginWidgetContainerPage()V: Line 3252
   * Goal 14. main.ClassUnderTest.goToSiteUserListContainerPage()V: Line 971
   * Goal 15. main.ClassUnderTest.goToUserListUserListContainerPage()V: Line 983
   * Goal 16. main.ClassUnderTest.goToUsersAddEditUserContainerPage()V: Line 1409
   * Goal 17. main.ClassUnderTest.goToUsersDashboardContainerPage()V: Line 775
   * Goal 18. main.ClassUnderTest.goToUsersPagesContainerPage()V: Line 1970
   * Goal 19. main.ClassUnderTest.goToWidgetsAddEditPageContainerPage()V: Line 2317
   * Goal 20. main.ClassUnderTest.goToWidgetsWidgetsContainerPage()V: Line 3024
   */

  @Test(timeout = 1001000)
  public void test00()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      WidgetUserType widgetUserType0 = WidgetUserType.LASTREGISTERED;
      WidgetUserDisplay widgetUserDisplay0 = WidgetUserDisplay.LIST;
      WidgetTotalUser widgetTotalUser0 = WidgetTotalUser.SHOW;
      WidgetNumberOfUsers widgetNumberOfUsers0 = WidgetNumberOfUsers.SIX;
      classUnderTest0.addUserWidgetDashboardContainerPage(widgetUserType0, widgetUserDisplay0, widgetTotalUser0, widgetNumberOfUsers0);
      WidgetLocation widgetLocation0 = WidgetLocation.TRENTO;
      WidgetUnit widgetUnit0 = WidgetUnit.METRIC;
      classUnderTest0.addLocationWidgetDashboardContainerPage(widgetLocation0, widgetUnit0);
      classUnderTest0.goToUsersDashboardContainerPage();
      classUnderTest0.goToSiteUserListContainerPage();
      classUnderTest0.goToUsersPagesContainerPage();
      classUnderTest0.goToUserListUserListContainerPage();
      classUnderTest0.addUserUserListContainerPage();
      classUnderTest0.closeOperationAddEditUserContainerPage();
      classUnderTest0.goToSiteUserListContainerPage();
      classUnderTest0.addPagePagesContainerPage();
      classUnderTest0.goToContentAddEditPageContainerPage();
      SitePages sitePages0 = SitePages.SPECIAL_POSTS;
      HTMLSnippets hTMLSnippets0 = HTMLSnippets.IMAGE_TITLE_PRICE;
      PageLinkStatus pageLinkStatus0 = PageLinkStatus.DISABLED;
      HideInMenu hideInMenu0 = HideInMenu.YES;
      classUnderTest0.addEditPageAddEditPageContainerPage(sitePages0, hTMLSnippets0, pageLinkStatus0, hideInMenu0);
      SitePages sitePages1 = SitePages.SPECIAL_POSTS;
      PageLinkStatus pageLinkStatus1 = PageLinkStatus.ENABLED;
      UserRoles userRoles0 = UserRoles.AUTHENTICATED;
      HideInMenu hideInMenu1 = HideInMenu.YES;
      classUnderTest0.addEditPageRestrictAccessAddEditPageContainerPage(sitePages1, hTMLSnippets0, pageLinkStatus1, userRoles0, hideInMenu1);
      classUnderTest0.goToWidgetsAddEditPageContainerPage();
      classUnderTest0.goToWidgetsWidgetsContainerPage();
      classUnderTest0.addLoginWidgetsContainerPage();
      WidgetLoginTitles widgetLoginTitles0 = WidgetLoginTitles.LOGGED_IN;
      PageLinkStatus pageLinkStatus2 = PageLinkStatus.ENABLED;
      classUnderTest0.addEditLoginDetailsAddEditLoginWidgetContainerPage(widgetLoginTitles0, pageLinkStatus2);
      classUnderTest0.goToSettingsAddEditLoginWidgetContainerPage();
      classUnderTest0.goToEditCurrentUserAddEditLoginWidgetContainerPage();
      classUnderTest0.goToUsersAddEditUserContainerPage();
      classUnderTest0.addUserUserListContainerPage();
      classUnderTest0.goToRolesAddEditUserContainerPage();
  }

  //Test case number: 1
  /*
   * 11 covered goals:
   * Goal 1. main.ClassUnderTest.addExistingMenuPagesContainerPage(Lcustom_classes/SiteMenus;)V: Line 1686
   * Goal 2. main.ClassUnderTest.addFeedWidgetDashboardContainerPage(Lcustom_classes/WidgetFeedTitle;Lcustom_classes/WidgetFeedUrl;Lcustom_classes/WidgetFeedNumberOfPosts;Lcustom_classes/WidgetFeedPostContent;)V: Line 515
   * Goal 3. main.ClassUnderTest.addItemAddEditItemPage()V: Line 380
   * Goal 4. main.ClassUnderTest.addLinkPagesContainerPage()V: Line 1706
   * Goal 5. main.ClassUnderTest.addLocationWidgetDashboardContainerPage(Lcustom_classes/WidgetLocation;Lcustom_classes/WidgetUnit;)V: Line 533
   * Goal 6. main.ClassUnderTest.deleteLocationWidgetDashboardContainerPage(Lcustom_classes/Id;)V: Line 575
   * Goal 7. main.ClassUnderTest.editFeedWidgetDashboardContainerPage(Lcustom_classes/Id;Lcustom_classes/WidgetFeedTitle;Lcustom_classes/WidgetFeedUrl;Lcustom_classes/WidgetFeedNumberOfPosts;Lcustom_classes/WidgetFeedPostContent;)V: Line 635
   * Goal 8. main.ClassUnderTest.goToDashboardAddEditUserContainerPage()V: Line 1320
   * Goal 9. main.ClassUnderTest.goToDashboardDashboardContainerPage()V: Line 713
   * Goal 10. main.ClassUnderTest.goToEditCurrentUserDashboardContainerPage()V: Line 726
   * Goal 11. main.ClassUnderTest.goToSiteDashboardContainerPage()V: Line 763
   */

  @Test(timeout = 1001000)
  public void test01()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      WidgetLocation widgetLocation0 = WidgetLocation.TRENTO;
      WidgetUnit widgetUnit0 = WidgetUnit.IMPERIAL;
      classUnderTest0.addLocationWidgetDashboardContainerPage(widgetLocation0, widgetUnit0);
      WidgetFeedTitle widgetFeedTitle0 = WidgetFeedTitle.SPORTNEWS;
      WidgetFeedUrl widgetFeedUrl0 = WidgetFeedUrl.WEATHER;
      int int0 = (-1834);
      WidgetFeedNumberOfPosts widgetFeedNumberOfPosts0 = new WidgetFeedNumberOfPosts(int0);
      WidgetFeedPostContent widgetFeedPostContent0 = WidgetFeedPostContent.SHOWALLPOSTS;
      classUnderTest0.addFeedWidgetDashboardContainerPage(widgetFeedTitle0, widgetFeedUrl0, widgetFeedNumberOfPosts0, widgetFeedPostContent0);
      classUnderTest0.goToEditCurrentUserDashboardContainerPage();
      classUnderTest0.goToDashboardAddEditUserContainerPage();
      Id id0 = new Id(int0);
      classUnderTest0.deleteLocationWidgetDashboardContainerPage(id0);
      classUnderTest0.goToDashboardDashboardContainerPage();
      WidgetFeedTitle widgetFeedTitle1 = WidgetFeedTitle.WEATHER;
      classUnderTest0.editFeedWidgetDashboardContainerPage(id0, widgetFeedTitle1, widgetFeedUrl0, widgetFeedNumberOfPosts0, widgetFeedPostContent0);
      classUnderTest0.goToSiteDashboardContainerPage();
      SiteMenus siteMenus0 = SiteMenus.MAIN;
      classUnderTest0.addExistingMenuPagesContainerPage(siteMenus0);
      classUnderTest0.addItemAddEditItemPage();
      classUnderTest0.addLinkPagesContainerPage();
  }

  //Test case number: 2
  /*
   * 23 covered goals:
   * Goal 1. main.ClassUnderTest.addItemAddEditItemPage()V: Line 396
   * Goal 2. main.ClassUnderTest.addLocationWidgetDashboardContainerPage(Lcustom_classes/WidgetLocation;Lcustom_classes/WidgetUnit;)V: Line 533
   * Goal 3. main.ClassUnderTest.addMenuPagesContainerPage(Lcustom_classes/SiteMenus;)V: Line 1727
   * Goal 4. main.ClassUnderTest.addPagePagesContainerPage()V: Line 1747
   * Goal 5. main.ClassUnderTest.addTextWidgetsContainerPage()V: Line 2786
   * Goal 6. main.ClassUnderTest.confirmOperationDeleteItemPage()V: Line 296
   * Goal 7. main.ClassUnderTest.deleteAllPagesAndLinksPagesContainerPage()V: Line 1767
   * Goal 8. main.ClassUnderTest.deleteUserUserListContainerPage(Lcustom_classes/Id;)V: Line 889
   * Goal 9. main.ClassUnderTest.editUserAddEditUserContainerPage(Lcustom_classes/Username;Lcustom_classes/Name;Lcustom_classes/Email;Lcustom_classes/UserPassword;)V: Line 1303
   * Goal 10. main.ClassUnderTest.editUserWidgetDashboardContainerPage(Lcustom_classes/Id;Lcustom_classes/WidgetUserType;Lcustom_classes/WidgetUserDisplay;Lcustom_classes/WidgetTotalUser;Lcustom_classes/WidgetNumberOfUsers;)V: Line 696
   * Goal 11. main.ClassUnderTest.goToEditCurrentUserAddEditTextWidgetContainerPage()V: Line 2436
   * Goal 12. main.ClassUnderTest.goToEditCurrentUserDashboardContainerPage()V: Line 726
   * Goal 13. main.ClassUnderTest.goToEditCurrentUserPagesContainerPage()V: Line 1914
   * Goal 14. main.ClassUnderTest.goToPermissionsAddEditUserContainerPage()V: Line 1346
   * Goal 15. main.ClassUnderTest.goToPermissionsPermissionsContainerPage()V: Line 1472
   * Goal 16. main.ClassUnderTest.goToRolesPermissionsContainerPage()V: Line 1485
   * Goal 17. main.ClassUnderTest.goToRolesUserListContainerPage()V: Line 945
   * Goal 18. main.ClassUnderTest.goToSiteUserListContainerPage()V: Line 971
   * Goal 19. main.ClassUnderTest.goToUserListPermissionsContainerPage()V: Line 1523
   * Goal 20. main.ClassUnderTest.goToUserListUserListContainerPage()V: Line 983
   * Goal 21. main.ClassUnderTest.goToUsersAddEditUserContainerPage()V: Line 1409
   * Goal 22. main.ClassUnderTest.goToUsersUserListContainerPage()V: Line 995
   * Goal 23. main.ClassUnderTest.goToWidgetsAddEditPageContainerPage()V: Line 2317
   */

  @Test(timeout = 1001000)
  public void test02()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      int int0 = 3510;
      Id id0 = new Id(int0);
      WidgetUserType widgetUserType0 = WidgetUserType.LOGGEDIN;
      WidgetUserDisplay widgetUserDisplay0 = WidgetUserDisplay.LIST;
      WidgetTotalUser widgetTotalUser0 = WidgetTotalUser.HIDE;
      WidgetNumberOfUsers widgetNumberOfUsers0 = WidgetNumberOfUsers.SIX;
      classUnderTest0.editUserWidgetDashboardContainerPage(id0, widgetUserType0, widgetUserDisplay0, widgetTotalUser0, widgetNumberOfUsers0);
      WidgetLocation widgetLocation0 = WidgetLocation.TRENTO;
      WidgetUnit widgetUnit0 = WidgetUnit.IMPERIAL;
      classUnderTest0.addLocationWidgetDashboardContainerPage(widgetLocation0, widgetUnit0);
      classUnderTest0.goToEditCurrentUserDashboardContainerPage();
      classUnderTest0.goToPermissionsAddEditUserContainerPage();
      classUnderTest0.goToPermissionsPermissionsContainerPage();
      classUnderTest0.goToRolesPermissionsContainerPage();
      SiteMenus siteMenus0 = SiteMenus.OTHER_MENU;
      classUnderTest0.goToUserListPermissionsContainerPage();
      classUnderTest0.goToUserListUserListContainerPage();
      classUnderTest0.goToSiteUserListContainerPage();
      classUnderTest0.deleteAllPagesAndLinksPagesContainerPage();
      classUnderTest0.addMenuPagesContainerPage(siteMenus0);
      classUnderTest0.addItemAddEditItemPage();
      classUnderTest0.addPagePagesContainerPage();
      classUnderTest0.goToWidgetsAddEditPageContainerPage();
      classUnderTest0.addTextWidgetsContainerPage();
      classUnderTest0.goToEditCurrentUserAddEditTextWidgetContainerPage();
      classUnderTest0.goToUsersAddEditUserContainerPage();
      classUnderTest0.deleteUserUserListContainerPage(id0);
      classUnderTest0.confirmOperationDeleteItemPage();
      classUnderTest0.goToSiteUserListContainerPage();
      classUnderTest0.goToEditCurrentUserPagesContainerPage();
      Username username0 = Username.FOO;
      Name name0 = Name.JOHN;
      Email email0 = Email.ASD;
      UserPassword userPassword0 = UserPassword.FOO;
      classUnderTest0.editUserAddEditUserContainerPage(username0, name0, email0, userPassword0);
      classUnderTest0.goToUsersAddEditUserContainerPage();
      classUnderTest0.goToUsersUserListContainerPage();
      classUnderTest0.goToRolesUserListContainerPage();
  }

  //Test case number: 3
  /*
   * 18 covered goals:
   * Goal 1. main.ClassUnderTest.activateUserUserListContainerPage(Lcustom_classes/Id;)V: Line 793
   * Goal 2. main.ClassUnderTest.addMenuWidgetsContainerPage()V: Line 2772
   * Goal 3. main.ClassUnderTest.addUserUserListContainerPage()V: Line 812
   * Goal 4. main.ClassUnderTest.cancelOperationDeleteItemPage()V: Line 252
   * Goal 5. main.ClassUnderTest.cancelOperationDeleteItemPage()V: Line 257
   * Goal 6. main.ClassUnderTest.deleteUserOrFeedWidgetDashboardContainerPage(Lcustom_classes/Id;)V: Line 603
   * Goal 7. main.ClassUnderTest.deleteUserUserListContainerPage(Lcustom_classes/Id;)V: Line 889
   * Goal 8. main.ClassUnderTest.goToDashboardDashboardContainerPage()V: Line 713
   * Goal 9. main.ClassUnderTest.goToDashboardUserListContainerPage()V: Line 906
   * Goal 10. main.ClassUnderTest.goToEditCurrentUserDashboardContainerPage()V: Line 726
   * Goal 11. main.ClassUnderTest.goToEditCurrentUserUserListContainerPage()V: Line 919
   * Goal 12. main.ClassUnderTest.goToRolesAddEditUserContainerPage()V: Line 1359
   * Goal 13. main.ClassUnderTest.goToSiteAddEditUserContainerPage()V: Line 1385
   * Goal 14. main.ClassUnderTest.goToUserListAddEditUserContainerPage()V: Line 1397
   * Goal 15. main.ClassUnderTest.goToUserListPermissionsContainerPage()V: Line 1523
   * Goal 16. main.ClassUnderTest.goToUsersAddEditMenuWidgetContainerPage()V: Line 3554
   * Goal 17. main.ClassUnderTest.goToUsersDashboardContainerPage()V: Line 775
   * Goal 18. main.ClassUnderTest.goToWidgetsPagesContainerPage()V: Line 1982
   */

  @Test(timeout = 1001000)
  public void test03()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      int int0 = 3363;
      Id id0 = new Id(int0);
      classUnderTest0.deleteUserOrFeedWidgetDashboardContainerPage(id0);
      classUnderTest0.cancelOperationDeleteItemPage();
      classUnderTest0.goToDashboardDashboardContainerPage();
      classUnderTest0.goToUsersDashboardContainerPage();
      classUnderTest0.goToDashboardUserListContainerPage();
      classUnderTest0.goToEditCurrentUserDashboardContainerPage();
      classUnderTest0.goToRolesAddEditUserContainerPage();
      classUnderTest0.goToUserListPermissionsContainerPage();
      classUnderTest0.activateUserUserListContainerPage(id0);
      classUnderTest0.goToEditCurrentUserUserListContainerPage();
      classUnderTest0.goToUserListAddEditUserContainerPage();
      classUnderTest0.deleteUserUserListContainerPage(id0);
      classUnderTest0.cancelOperationDeleteItemPage();
      classUnderTest0.addUserUserListContainerPage();
      classUnderTest0.goToSiteAddEditUserContainerPage();
      classUnderTest0.goToWidgetsPagesContainerPage();
      classUnderTest0.addMenuWidgetsContainerPage();
      classUnderTest0.goToUsersAddEditMenuWidgetContainerPage();
  }

  //Test case number: 4
  /*
   * 20 covered goals:
   * Goal 1. main.ClassUnderTest.addPagePagesContainerPage()V: Line 1747
   * Goal 2. main.ClassUnderTest.addUserAddEditUserContainerPage(Lcustom_classes/Username;Lcustom_classes/Name;Lcustom_classes/Email;Lcustom_classes/UserPassword;Lcustom_classes/UserStatus;)V: Line 1263
   * Goal 3. main.ClassUnderTest.addUserUserListContainerPage()V: Line 812
   * Goal 4. main.ClassUnderTest.addUserWidgetDashboardContainerPage(Lcustom_classes/WidgetUserType;Lcustom_classes/WidgetUserDisplay;Lcustom_classes/WidgetTotalUser;Lcustom_classes/WidgetNumberOfUsers;)V: Line 553
   * Goal 5. main.ClassUnderTest.cancelOperationSelectLinkPage()V: Line 30
   * Goal 6. main.ClassUnderTest.changeSettingsUserSettingsContainerPage(Lcustom_classes/RegistrationUserSettings;)V: Line 1550
   * Goal 7. main.ClassUnderTest.editUserAddEditUserContainerPage(Lcustom_classes/Username;Lcustom_classes/Name;Lcustom_classes/Email;Lcustom_classes/UserPassword;)V: Line 1303
   * Goal 8. main.ClassUnderTest.giveOrRemoveAllPermissionsToUserRolePermissionsContainerPage(Lcustom_classes/UserRoles;)V: Line 1428
   * Goal 9. main.ClassUnderTest.goToDashboardDashboardContainerPage()V: Line 713
   * Goal 10. main.ClassUnderTest.goToDashboardUserListContainerPage()V: Line 906
   * Goal 11. main.ClassUnderTest.goToEditCurrentUserAddEditUserContainerPage()V: Line 1333
   * Goal 12. main.ClassUnderTest.goToEditCurrentUserDashboardContainerPage()V: Line 726
   * Goal 13. main.ClassUnderTest.goToEditCurrentUserPermissionsContainerPage()V: Line 1459
   * Goal 14. main.ClassUnderTest.goToMetaAddEditPageContainerPage()V: Line 2268
   * Goal 15. main.ClassUnderTest.goToPermissionsAddEditUserContainerPage()V: Line 1346
   * Goal 16. main.ClassUnderTest.goToSettingsAddEditUserContainerPage()V: Line 1372
   * Goal 17. main.ClassUnderTest.goToSiteDashboardContainerPage()V: Line 763
   * Goal 18. main.ClassUnderTest.goToUsersAddEditPageContainerPage()V: Line 2305
   * Goal 19. main.ClassUnderTest.goToUsersAddEditUserContainerPage()V: Line 1409
   * Goal 20. main.ClassUnderTest.goToUsersUserListContainerPage()V: Line 995
   */

  @Test(timeout = 1001000)
  public void test04()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      classUnderTest0.goToEditCurrentUserDashboardContainerPage();
      Username username0 = Username.FOO;
      Name name0 = Name.JOHN;
      Email email0 = Email.ASD;
      UserPassword userPassword0 = UserPassword.FOO;
      classUnderTest0.editUserAddEditUserContainerPage(username0, name0, email0, userPassword0);
      classUnderTest0.goToEditCurrentUserAddEditUserContainerPage();
      classUnderTest0.goToUsersAddEditUserContainerPage();
      classUnderTest0.goToDashboardUserListContainerPage();
      WidgetUserType widgetUserType0 = WidgetUserType.LASTREGISTERED;
      WidgetUserDisplay widgetUserDisplay0 = WidgetUserDisplay.LIST;
      WidgetTotalUser widgetTotalUser0 = WidgetTotalUser.HIDE;
      WidgetNumberOfUsers widgetNumberOfUsers0 = WidgetNumberOfUsers.TWELVE;
      classUnderTest0.goToDashboardDashboardContainerPage();
      classUnderTest0.addUserWidgetDashboardContainerPage(widgetUserType0, widgetUserDisplay0, widgetTotalUser0, widgetNumberOfUsers0);
      WidgetUserDisplay widgetUserDisplay1 = WidgetUserDisplay.THUMBNAIL;
      WidgetTotalUser widgetTotalUser1 = WidgetTotalUser.HIDE;
      classUnderTest0.addUserWidgetDashboardContainerPage(widgetUserType0, widgetUserDisplay1, widgetTotalUser1, widgetNumberOfUsers0);
      classUnderTest0.goToSiteDashboardContainerPage();
      classUnderTest0.addPagePagesContainerPage();
      classUnderTest0.goToMetaAddEditPageContainerPage();
      classUnderTest0.goToUsersAddEditPageContainerPage();
      classUnderTest0.goToUsersUserListContainerPage();
      classUnderTest0.addUserUserListContainerPage();
      Username username1 = Username.FOO;
      Name name1 = Name.MARK;
      UserPassword userPassword1 = UserPassword.ADMIN;
      UserStatus userStatus0 = UserStatus.BLOCKED;
      classUnderTest0.addUserAddEditUserContainerPage(username1, name1, email0, userPassword1, userStatus0);
      classUnderTest0.goToPermissionsAddEditUserContainerPage();
      UserRoles userRoles0 = UserRoles.AUTHENTICATED;
      classUnderTest0.giveOrRemoveAllPermissionsToUserRolePermissionsContainerPage(userRoles0);
      classUnderTest0.goToEditCurrentUserPermissionsContainerPage();
      classUnderTest0.goToSettingsAddEditUserContainerPage();
      RegistrationUserSettings registrationUserSettings0 = RegistrationUserSettings.ENABLED_BUT_APPROVAL;
      classUnderTest0.changeSettingsUserSettingsContainerPage(registrationUserSettings0);
      classUnderTest0.cancelOperationSelectLinkPage();
  }

  //Test case number: 5
  /*
   * 10 covered goals:
   * Goal 1. main.ClassUnderTest.addLocationWidgetDashboardContainerPage(Lcustom_classes/WidgetLocation;Lcustom_classes/WidgetUnit;)V: Line 533
   * Goal 2. main.ClassUnderTest.addUserWidgetDashboardContainerPage(Lcustom_classes/WidgetUserType;Lcustom_classes/WidgetUserDisplay;Lcustom_classes/WidgetTotalUser;Lcustom_classes/WidgetNumberOfUsers;)V: Line 553
   * Goal 3. main.ClassUnderTest.blockUserUserListContainerPage(Lcustom_classes/Id;)V: Line 834
   * Goal 4. main.ClassUnderTest.editUserWidgetDashboardContainerPage(Lcustom_classes/Id;Lcustom_classes/WidgetUserType;Lcustom_classes/WidgetUserDisplay;Lcustom_classes/WidgetTotalUser;Lcustom_classes/WidgetNumberOfUsers;)V: Line 696
   * Goal 5. main.ClassUnderTest.goToDashboardDashboardContainerPage()V: Line 713
   * Goal 6. main.ClassUnderTest.goToEditCurrentUserPermissionsContainerPage()V: Line 1459
   * Goal 7. main.ClassUnderTest.goToRolesUserListContainerPage()V: Line 945
   * Goal 8. main.ClassUnderTest.goToUsersAddEditUserContainerPage()V: Line 1409
   * Goal 9. main.ClassUnderTest.goToUsersDashboardContainerPage()V: Line 775
   * Goal 10. main.ClassUnderTest.goToUsersUserListContainerPage()V: Line 995
   */

  @Test(timeout = 1001000)
  public void test05()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      WidgetLocation widgetLocation0 = WidgetLocation.TRENTO;
      WidgetUnit widgetUnit0 = WidgetUnit.METRIC;
      classUnderTest0.addLocationWidgetDashboardContainerPage(widgetLocation0, widgetUnit0);
      int int0 = (-1068);
      Id id0 = new Id(int0);
      WidgetUserType widgetUserType0 = WidgetUserType.LOGGEDIN;
      WidgetUserDisplay widgetUserDisplay0 = WidgetUserDisplay.THUMBNAIL;
      WidgetTotalUser widgetTotalUser0 = WidgetTotalUser.HIDE;
      WidgetNumberOfUsers widgetNumberOfUsers0 = WidgetNumberOfUsers.SIX;
      classUnderTest0.editUserWidgetDashboardContainerPage(id0, widgetUserType0, widgetUserDisplay0, widgetTotalUser0, widgetNumberOfUsers0);
      WidgetNumberOfUsers widgetNumberOfUsers1 = WidgetNumberOfUsers.TWELVE;
      classUnderTest0.editUserWidgetDashboardContainerPage(id0, widgetUserType0, widgetUserDisplay0, widgetTotalUser0, widgetNumberOfUsers1);
      classUnderTest0.goToDashboardDashboardContainerPage();
      WidgetTotalUser widgetTotalUser1 = WidgetTotalUser.SHOW;
      WidgetNumberOfUsers widgetNumberOfUsers2 = WidgetNumberOfUsers.TWELVE;
      classUnderTest0.addUserWidgetDashboardContainerPage(widgetUserType0, widgetUserDisplay0, widgetTotalUser1, widgetNumberOfUsers2);
      classUnderTest0.goToUsersDashboardContainerPage();
      classUnderTest0.blockUserUserListContainerPage(id0);
      classUnderTest0.goToUsersUserListContainerPage();
      classUnderTest0.goToRolesUserListContainerPage();
      classUnderTest0.goToEditCurrentUserPermissionsContainerPage();
      classUnderTest0.goToUsersAddEditUserContainerPage();
  }

  //Test case number: 6
  /*
   * 17 covered goals:
   * Goal 1. main.ClassUnderTest.addUserUserListContainerPage()V: Line 812
   * Goal 2. main.ClassUnderTest.addUserWidgetDashboardContainerPage(Lcustom_classes/WidgetUserType;Lcustom_classes/WidgetUserDisplay;Lcustom_classes/WidgetTotalUser;Lcustom_classes/WidgetNumberOfUsers;)V: Line 553
   * Goal 3. main.ClassUnderTest.cancelOperationSelectImagePage()V: Line 447
   * Goal 4. main.ClassUnderTest.changeSettingsUserSettingsContainerPage(Lcustom_classes/RegistrationUserSettings;)V: Line 1550
   * Goal 5. main.ClassUnderTest.closeOperationAddEditUserContainerPage()V: Line 1285
   * Goal 6. main.ClassUnderTest.goToEditCurrentUserUserListContainerPage()V: Line 919
   * Goal 7. main.ClassUnderTest.goToEditCurrentUserUserSettingsContainerPage()V: Line 1576
   * Goal 8. main.ClassUnderTest.goToEditUserDashboardContainerPage(Lcustom_classes/Id;)V: Line 746
   * Goal 9. main.ClassUnderTest.goToSettingsAddEditUserContainerPage()V: Line 1372
   * Goal 10. main.ClassUnderTest.goToSettingsUserListContainerPage()V: Line 958
   * Goal 11. main.ClassUnderTest.goToSettingsUserSettingsContainerPage()V: Line 1615
   * Goal 12. main.ClassUnderTest.goToUserListUserListContainerPage()V: Line 983
   * Goal 13. main.ClassUnderTest.goToUsersAddEditUserContainerPage()V: Line 1409
   * Goal 14. main.ClassUnderTest.goToUsersUserSettingsContainerPage()V: Line 1652
   * Goal 15. main.ClassUnderTest.saveSettingsUserSettingsContainerPage()V: Line 1667
   * Goal 16. main.ClassUnderTest.selectLinkStorageSelectLinkPage(Lcustom_classes/Extension;)V: Line 126
   * Goal 17. main.ClassUnderTest.updateSelectLinkPage()V: Line 203
   */

  @Test(timeout = 1001000)
  public void test06()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      WidgetUserType widgetUserType0 = WidgetUserType.LASTREGISTERED;
      WidgetUserDisplay widgetUserDisplay0 = WidgetUserDisplay.THUMBNAIL;
      WidgetTotalUser widgetTotalUser0 = WidgetTotalUser.SHOW;
      WidgetNumberOfUsers widgetNumberOfUsers0 = WidgetNumberOfUsers.EIGHTEEN;
      classUnderTest0.addUserWidgetDashboardContainerPage(widgetUserType0, widgetUserDisplay0, widgetTotalUser0, widgetNumberOfUsers0);
      int int0 = 2863;
      Id id0 = new Id(int0);
      classUnderTest0.goToEditUserDashboardContainerPage(id0);
      classUnderTest0.goToSettingsAddEditUserContainerPage();
      classUnderTest0.saveSettingsUserSettingsContainerPage();
      classUnderTest0.goToEditCurrentUserUserSettingsContainerPage();
      classUnderTest0.closeOperationAddEditUserContainerPage();
      classUnderTest0.goToEditCurrentUserUserListContainerPage();
      classUnderTest0.goToUsersAddEditUserContainerPage();
      classUnderTest0.goToUserListUserListContainerPage();
      classUnderTest0.addUserUserListContainerPage();
      classUnderTest0.goToSettingsAddEditUserContainerPage();
      classUnderTest0.goToEditCurrentUserUserSettingsContainerPage();
      classUnderTest0.goToUsersAddEditUserContainerPage();
      classUnderTest0.goToSettingsUserListContainerPage();
      RegistrationUserSettings registrationUserSettings0 = RegistrationUserSettings.DISABLED;
      classUnderTest0.changeSettingsUserSettingsContainerPage(registrationUserSettings0);
      classUnderTest0.updateSelectLinkPage();
      classUnderTest0.goToSettingsUserSettingsContainerPage();
      classUnderTest0.goToUsersUserSettingsContainerPage();
      classUnderTest0.goToSettingsUserListContainerPage();
      RegistrationUserSettings registrationUserSettings1 = RegistrationUserSettings.DISABLED;
      classUnderTest0.changeSettingsUserSettingsContainerPage(registrationUserSettings1);
      Extension extension0 = Extension.STORAGE;
      classUnderTest0.selectLinkStorageSelectLinkPage(extension0);
      classUnderTest0.cancelOperationSelectImagePage();
  }

  //Test case number: 7
  /*
   * 15 covered goals:
   * Goal 1. main.ClassUnderTest.addLinkPagesContainerPage()V: Line 1706
   * Goal 2. main.ClassUnderTest.closeEditLinkAddEditLinkContainerPage()V: Line 2629
   * Goal 3. main.ClassUnderTest.editUserAddEditUserContainerPage(Lcustom_classes/Username;Lcustom_classes/Name;Lcustom_classes/Email;Lcustom_classes/UserPassword;)V: Line 1303
   * Goal 4. main.ClassUnderTest.goToDashboardPagesContainerPage()V: Line 1901
   * Goal 5. main.ClassUnderTest.goToDashboardUserListContainerPage()V: Line 906
   * Goal 6. main.ClassUnderTest.goToEditCurrentUserAddEditUserContainerPage()V: Line 1333
   * Goal 7. main.ClassUnderTest.goToEditCurrentUserDashboardContainerPage()V: Line 726
   * Goal 8. main.ClassUnderTest.goToEditCurrentUserUserListContainerPage()V: Line 919
   * Goal 9. main.ClassUnderTest.goToEditCurrentUserUserSettingsContainerPage()V: Line 1576
   * Goal 10. main.ClassUnderTest.goToRolesAddEditUserContainerPage()V: Line 1359
   * Goal 11. main.ClassUnderTest.goToSettingsAddEditUserContainerPage()V: Line 1372
   * Goal 12. main.ClassUnderTest.goToSiteDashboardContainerPage()V: Line 763
   * Goal 13. main.ClassUnderTest.goToSitePermissionsContainerPage()V: Line 1511
   * Goal 14. main.ClassUnderTest.goToUsersAddEditUserContainerPage()V: Line 1409
   * Goal 15. main.ClassUnderTest.goToUsersDashboardContainerPage()V: Line 775
   */

  @Test(timeout = 1001000)
  public void test07()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      classUnderTest0.goToEditCurrentUserDashboardContainerPage();
      Username username0 = Username.FOO;
      Name name0 = Name.JOHN;
      Email email0 = Email.ASD;
      UserPassword userPassword0 = UserPassword.ADMIN;
      classUnderTest0.editUserAddEditUserContainerPage(username0, name0, email0, userPassword0);
      classUnderTest0.goToEditCurrentUserAddEditUserContainerPage();
      classUnderTest0.goToUsersAddEditUserContainerPage();
      classUnderTest0.goToDashboardUserListContainerPage();
      classUnderTest0.goToSiteDashboardContainerPage();
      classUnderTest0.goToDashboardPagesContainerPage();
      classUnderTest0.goToUsersDashboardContainerPage();
      classUnderTest0.goToEditCurrentUserUserListContainerPage();
      classUnderTest0.goToSettingsAddEditUserContainerPage();
      classUnderTest0.goToEditCurrentUserUserSettingsContainerPage();
      classUnderTest0.goToRolesAddEditUserContainerPage();
      classUnderTest0.goToSitePermissionsContainerPage();
      classUnderTest0.addLinkPagesContainerPage();
      classUnderTest0.closeEditLinkAddEditLinkContainerPage();
  }

  //Test case number: 8
  /*
   * 17 covered goals:
   * Goal 1. main.ClassUnderTest.addEditPageAddEditPageContainerPage(Lcustom_classes/SitePages;Lcustom_classes/HTMLSnippets;Lcustom_classes/PageLinkStatus;Lcustom_classes/HideInMenu;)V: Line 2166
   * Goal 2. main.ClassUnderTest.addFeedWidgetDashboardContainerPage(Lcustom_classes/WidgetFeedTitle;Lcustom_classes/WidgetFeedUrl;Lcustom_classes/WidgetFeedNumberOfPosts;Lcustom_classes/WidgetFeedPostContent;)V: Line 515
   * Goal 3. main.ClassUnderTest.addLocationWidgetDashboardContainerPage(Lcustom_classes/WidgetLocation;Lcustom_classes/WidgetUnit;)V: Line 533
   * Goal 4. main.ClassUnderTest.addPagePagesContainerPage()V: Line 1747
   * Goal 5. main.ClassUnderTest.addUserWidgetDashboardContainerPage(Lcustom_classes/WidgetUserType;Lcustom_classes/WidgetUserDisplay;Lcustom_classes/WidgetTotalUser;Lcustom_classes/WidgetNumberOfUsers;)V: Line 553
   * Goal 6. main.ClassUnderTest.closeEditPageAddEditPageContainerPage()V: Line 2216
   * Goal 7. main.ClassUnderTest.goToDashboardAddEditPageContainerPage()V: Line 2242
   * Goal 8. main.ClassUnderTest.goToPagesAddEditPageContainerPage()V: Line 2281
   * Goal 9. main.ClassUnderTest.goToSiteDashboardContainerPage()V: Line 763
   * Goal 10. main.ClassUnderTest.goToSitePagesContainerPage()V: Line 1958
   * Goal 11. main.ClassUnderTest.goToSiteUserListContainerPage()V: Line 971
   * Goal 12. main.ClassUnderTest.goToUsersAddEditPageContainerPage()V: Line 2305
   * Goal 13. main.ClassUnderTest.goToUsersDashboardContainerPage()V: Line 775
   * Goal 14. main.ClassUnderTest.goToUsersPagesContainerPage()V: Line 1970
   * Goal 15. main.ClassUnderTest.moveAllPagesAndLinksToMenuPagesContainerPage(Lcustom_classes/SiteMenus;)V: Line 2000
   * Goal 16. main.ClassUnderTest.moveLinkOrPageToMenuPagesContainerPage(Lcustom_classes/SiteLinkOrPage;Lcustom_classes/SiteMenus;)V: Line 2025
   * Goal 17. main.ClassUnderTest.unpublishLinkOrPagePagesContainerPage(Lcustom_classes/SiteLinkOrPage;)V: Line 2113
   */

  @Test(timeout = 1001000)
  public void test08()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      WidgetLocation widgetLocation0 = WidgetLocation.TRENTO;
      WidgetUnit widgetUnit0 = WidgetUnit.IMPERIAL;
      classUnderTest0.addLocationWidgetDashboardContainerPage(widgetLocation0, widgetUnit0);
      WidgetUserType widgetUserType0 = WidgetUserType.LASTREGISTERED;
      WidgetUserDisplay widgetUserDisplay0 = WidgetUserDisplay.THUMBNAIL;
      WidgetTotalUser widgetTotalUser0 = WidgetTotalUser.HIDE;
      WidgetNumberOfUsers widgetNumberOfUsers0 = WidgetNumberOfUsers.TWELVE;
      classUnderTest0.addUserWidgetDashboardContainerPage(widgetUserType0, widgetUserDisplay0, widgetTotalUser0, widgetNumberOfUsers0);
      int int0 = (-1246);
      Id id0 = new Id(int0);
      WidgetUserType widgetUserType1 = WidgetUserType.LOGGEDIN;
      WidgetTotalUser widgetTotalUser1 = WidgetTotalUser.HIDE;
      classUnderTest0.addUserWidgetDashboardContainerPage(widgetUserType1, widgetUserDisplay0, widgetTotalUser1, widgetNumberOfUsers0);
      WidgetFeedTitle widgetFeedTitle0 = WidgetFeedTitle.PAGEKITNEWS;
      WidgetFeedUrl widgetFeedUrl0 = WidgetFeedUrl.SPORT;
      WidgetFeedNumberOfPosts widgetFeedNumberOfPosts0 = new WidgetFeedNumberOfPosts(id0.value);
      WidgetFeedPostContent widgetFeedPostContent0 = WidgetFeedPostContent.SHOWALLPOSTS;
      classUnderTest0.addFeedWidgetDashboardContainerPage(widgetFeedTitle0, widgetFeedUrl0, widgetFeedNumberOfPosts0, widgetFeedPostContent0);
      WidgetLocation widgetLocation1 = WidgetLocation.MILANO;
      WidgetUnit widgetUnit1 = WidgetUnit.METRIC;
      classUnderTest0.addLocationWidgetDashboardContainerPage(widgetLocation1, widgetUnit1);
      classUnderTest0.goToSiteDashboardContainerPage();
      SiteMenus siteMenus0 = SiteMenus.NOT_LINKED;
      classUnderTest0.moveAllPagesAndLinksToMenuPagesContainerPage(siteMenus0);
      classUnderTest0.addPagePagesContainerPage();
      SitePages sitePages0 = SitePages.HOME;
      HTMLSnippets hTMLSnippets0 = HTMLSnippets.HOME;
      PageLinkStatus pageLinkStatus0 = PageLinkStatus.ENABLED;
      HideInMenu hideInMenu0 = HideInMenu.NO;
      classUnderTest0.addEditPageAddEditPageContainerPage(sitePages0, hTMLSnippets0, pageLinkStatus0, hideInMenu0);
      classUnderTest0.goToDashboardAddEditPageContainerPage();
      classUnderTest0.goToUsersDashboardContainerPage();
      classUnderTest0.goToSiteUserListContainerPage();
      classUnderTest0.unpublishLinkOrPagePagesContainerPage(sitePages0);
      classUnderTest0.addPagePagesContainerPage();
      classUnderTest0.goToPagesAddEditPageContainerPage();
      classUnderTest0.addPagePagesContainerPage();
      SitePages sitePages1 = SitePages.SPECIAL_POSTS;
      HTMLSnippets hTMLSnippets1 = HTMLSnippets.IMAGE_TITLE;
      PageLinkStatus pageLinkStatus1 = PageLinkStatus.ENABLED;
      HideInMenu hideInMenu1 = HideInMenu.YES;
      classUnderTest0.addEditPageAddEditPageContainerPage(sitePages1, hTMLSnippets1, pageLinkStatus1, hideInMenu1);
      classUnderTest0.closeEditPageAddEditPageContainerPage();
      classUnderTest0.goToSitePagesContainerPage();
      SitePages sitePages2 = SitePages.SPECIAL_POSTS;
      classUnderTest0.moveLinkOrPageToMenuPagesContainerPage(sitePages2, siteMenus0);
      classUnderTest0.goToUsersPagesContainerPage();
      classUnderTest0.goToSiteUserListContainerPage();
      classUnderTest0.addPagePagesContainerPage();
      classUnderTest0.goToUsersAddEditPageContainerPage();
  }

  //Test case number: 9
  /*
   * 12 covered goals:
   * Goal 1. main.ClassUnderTest.addTextWidgetsContainerPage()V: Line 2786
   * Goal 2. main.ClassUnderTest.closeEditTextAddEditTextWidgetContainerPage()V: Line 2410
   * Goal 3. main.ClassUnderTest.goToDashboardPermissionsContainerPage()V: Line 1446
   * Goal 4. main.ClassUnderTest.goToEditCurrentUserDashboardContainerPage()V: Line 726
   * Goal 5. main.ClassUnderTest.goToEditUserDashboardContainerPage(Lcustom_classes/Id;)V: Line 746
   * Goal 6. main.ClassUnderTest.goToPermissionsPermissionsContainerPage()V: Line 1472
   * Goal 7. main.ClassUnderTest.goToRolesUserSettingsContainerPage()V: Line 1602
   * Goal 8. main.ClassUnderTest.goToSettingsUserListContainerPage()V: Line 958
   * Goal 9. main.ClassUnderTest.goToSiteAddEditUserContainerPage()V: Line 1385
   * Goal 10. main.ClassUnderTest.goToUsersAddEditUserContainerPage()V: Line 1409
   * Goal 11. main.ClassUnderTest.goToUsersUserListContainerPage()V: Line 995
   * Goal 12. main.ClassUnderTest.goToWidgetsPagesContainerPage()V: Line 1982
   */

  @Test(timeout = 1001000)
  public void test09()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      classUnderTest0.goToEditCurrentUserDashboardContainerPage();
      classUnderTest0.goToUsersAddEditUserContainerPage();
      classUnderTest0.goToUsersUserListContainerPage();
      classUnderTest0.goToSettingsUserListContainerPage();
      classUnderTest0.goToRolesUserSettingsContainerPage();
      int int0 = 4439;
      Id id0 = new Id(int0);
      Id id1 = new Id(id0.value);
      classUnderTest0.goToPermissionsPermissionsContainerPage();
      classUnderTest0.goToDashboardPermissionsContainerPage();
      classUnderTest0.goToEditUserDashboardContainerPage(id1);
      classUnderTest0.goToSiteAddEditUserContainerPage();
      classUnderTest0.goToWidgetsPagesContainerPage();
      classUnderTest0.addTextWidgetsContainerPage();
      classUnderTest0.closeEditTextAddEditTextWidgetContainerPage();
  }

  //Test case number: 10
  /*
   * 13 covered goals:
   * Goal 1. main.ClassUnderTest.activateUserUserListContainerPage(Lcustom_classes/Id;)V: Line 793
   * Goal 2. main.ClassUnderTest.addLocationWidgetDashboardContainerPage(Lcustom_classes/WidgetLocation;Lcustom_classes/WidgetUnit;)V: Line 533
   * Goal 3. main.ClassUnderTest.cancelOperationDeleteItemPage()V: Line 252
   * Goal 4. main.ClassUnderTest.changeSettingsUserSettingsContainerPage(Lcustom_classes/RegistrationUserSettings;)V: Line 1550
   * Goal 5. main.ClassUnderTest.confirmOperationDeleteItemPage()V: Line 289
   * Goal 6. main.ClassUnderTest.deleteLinkOrPagePagesContainerPage(Lcustom_classes/SiteLinkOrPage;)V: Line 1788
   * Goal 7. main.ClassUnderTest.deleteUserOrFeedWidgetDashboardContainerPage(Lcustom_classes/Id;)V: Line 603
   * Goal 8. main.ClassUnderTest.goToPagesPagesContainerPage()V: Line 1946
   * Goal 9. main.ClassUnderTest.goToPermissionsUserListContainerPage()V: Line 932
   * Goal 10. main.ClassUnderTest.goToSettingsPermissionsContainerPage()V: Line 1498
   * Goal 11. main.ClassUnderTest.goToSiteDashboardContainerPage()V: Line 763
   * Goal 12. main.ClassUnderTest.goToUsersPagesContainerPage()V: Line 1970
   * Goal 13. main.ClassUnderTest.unpublishLinkOrPagePagesContainerPage(Lcustom_classes/SiteLinkOrPage;)V: Line 2113
   */

  @Test(timeout = 1001000)
  public void test10()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      int int0 = (-1014);
      Id id0 = new Id(int0);
      classUnderTest0.deleteUserOrFeedWidgetDashboardContainerPage(id0);
      classUnderTest0.cancelOperationDeleteItemPage();
      WidgetLocation widgetLocation0 = WidgetLocation.GENOA;
      WidgetUnit widgetUnit0 = WidgetUnit.METRIC;
      classUnderTest0.addLocationWidgetDashboardContainerPage(widgetLocation0, widgetUnit0);
      classUnderTest0.deleteUserOrFeedWidgetDashboardContainerPage(id0);
      classUnderTest0.confirmOperationDeleteItemPage();
      classUnderTest0.goToSiteDashboardContainerPage();
      SitePages sitePages0 = SitePages.HOME;
      classUnderTest0.unpublishLinkOrPagePagesContainerPage(sitePages0);
      classUnderTest0.goToPagesPagesContainerPage();
      classUnderTest0.deleteLinkOrPagePagesContainerPage(sitePages0);
      classUnderTest0.goToUsersPagesContainerPage();
      classUnderTest0.activateUserUserListContainerPage(id0);
      classUnderTest0.goToPermissionsUserListContainerPage();
      classUnderTest0.goToSettingsPermissionsContainerPage();
      RegistrationUserSettings registrationUserSettings0 = RegistrationUserSettings.DISABLED;
      classUnderTest0.changeSettingsUserSettingsContainerPage(registrationUserSettings0);
  }

  //Test case number: 11
  /*
   * 8 covered goals:
   * Goal 1. main.ClassUnderTest.activateUserUserListContainerPage(Lcustom_classes/Id;)V: Line 793
   * Goal 2. main.ClassUnderTest.confirmOperationDeleteItemPage()V: Line 304
   * Goal 3. main.ClassUnderTest.deleteAdminUserUserListContainerPage(Lcustom_classes/Id;)V: Line 864
   * Goal 4. main.ClassUnderTest.editUserWidgetDashboardContainerPage(Lcustom_classes/Id;Lcustom_classes/WidgetUserType;Lcustom_classes/WidgetUserDisplay;Lcustom_classes/WidgetTotalUser;Lcustom_classes/WidgetNumberOfUsers;)V: Line 696
   * Goal 5. main.ClassUnderTest.goToEditCurrentUserUserListContainerPage()V: Line 919
   * Goal 6. main.ClassUnderTest.goToSiteAddEditUserContainerPage()V: Line 1385
   * Goal 7. main.ClassUnderTest.goToUsersDashboardContainerPage()V: Line 775
   * Goal 8. main.ClassUnderTest.goToUsersUserListContainerPage()V: Line 995
   */

  @Test(timeout = 1001000)
  public void test11()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      int int0 = (-3285);
      Id id0 = new Id(int0);
      WidgetUserType widgetUserType0 = WidgetUserType.LOGGEDIN;
      WidgetUserDisplay widgetUserDisplay0 = WidgetUserDisplay.THUMBNAIL;
      WidgetTotalUser widgetTotalUser0 = WidgetTotalUser.HIDE;
      WidgetNumberOfUsers widgetNumberOfUsers0 = WidgetNumberOfUsers.EIGHTEEN;
      classUnderTest0.editUserWidgetDashboardContainerPage(id0, widgetUserType0, widgetUserDisplay0, widgetTotalUser0, widgetNumberOfUsers0);
      classUnderTest0.goToUsersDashboardContainerPage();
      classUnderTest0.goToUsersUserListContainerPage();
      classUnderTest0.deleteAdminUserUserListContainerPage(id0);
      classUnderTest0.confirmOperationDeleteItemPage();
      classUnderTest0.activateUserUserListContainerPage(id0);
      classUnderTest0.goToEditCurrentUserUserListContainerPage();
      classUnderTest0.goToSiteAddEditUserContainerPage();
  }

  //Test case number: 12
  /*
   * 14 covered goals:
   * Goal 1. main.ClassUnderTest.addLinkPagesContainerPage()V: Line 1706
   * Goal 2. main.ClassUnderTest.addLocationWidgetDashboardContainerPage(Lcustom_classes/WidgetLocation;Lcustom_classes/WidgetUnit;)V: Line 533
   * Goal 3. main.ClassUnderTest.closeOperationAddEditUserContainerPage()V: Line 1285
   * Goal 4. main.ClassUnderTest.editPagePagesContainerPage(Lcustom_classes/SitePages;)V: Line 1884
   * Goal 5. main.ClassUnderTest.goToDashboardDashboardContainerPage()V: Line 713
   * Goal 6. main.ClassUnderTest.goToDashboardUserListContainerPage()V: Line 906
   * Goal 7. main.ClassUnderTest.goToEditCurrentUserAddEditLinkContainerPage()V: Line 2655
   * Goal 8. main.ClassUnderTest.goToEditCurrentUserAddEditPageContainerPage()V: Line 2255
   * Goal 9. main.ClassUnderTest.goToEditCurrentUserDashboardContainerPage()V: Line 726
   * Goal 10. main.ClassUnderTest.goToPermissionsUserListContainerPage()V: Line 932
   * Goal 11. main.ClassUnderTest.goToSettingsUserListContainerPage()V: Line 958
   * Goal 12. main.ClassUnderTest.goToSitePermissionsContainerPage()V: Line 1511
   * Goal 13. main.ClassUnderTest.goToSiteUserSettingsContainerPage()V: Line 1628
   * Goal 14. main.ClassUnderTest.goToUserListAddEditUserContainerPage()V: Line 1397
   */

  @Test(timeout = 1001000)
  public void test12()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      classUnderTest0.goToDashboardDashboardContainerPage();
      WidgetLocation widgetLocation0 = WidgetLocation.TRENTO;
      WidgetUnit widgetUnit0 = WidgetUnit.IMPERIAL;
      classUnderTest0.addLocationWidgetDashboardContainerPage(widgetLocation0, widgetUnit0);
      classUnderTest0.goToEditCurrentUserDashboardContainerPage();
      classUnderTest0.closeOperationAddEditUserContainerPage();
      classUnderTest0.goToPermissionsUserListContainerPage();
      classUnderTest0.goToSitePermissionsContainerPage();
      classUnderTest0.addLinkPagesContainerPage();
      classUnderTest0.goToEditCurrentUserAddEditLinkContainerPage();
      classUnderTest0.goToUserListAddEditUserContainerPage();
      classUnderTest0.goToSettingsUserListContainerPage();
      classUnderTest0.goToSiteUserSettingsContainerPage();
      SitePages sitePages0 = SitePages.HOME;
      classUnderTest0.editPagePagesContainerPage(sitePages0);
      classUnderTest0.goToEditCurrentUserAddEditPageContainerPage();
      classUnderTest0.closeOperationAddEditUserContainerPage();
      classUnderTest0.goToDashboardUserListContainerPage();
  }

  //Test case number: 13
  /*
   * 9 covered goals:
   * Goal 1. main.ClassUnderTest.addLoginWidgetsContainerPage()V: Line 2758
   * Goal 2. main.ClassUnderTest.confirmOperationDeleteItemPage()V: Line 289
   * Goal 3. main.ClassUnderTest.deleteUserOrFeedWidgetDashboardContainerPage(Lcustom_classes/Id;)V: Line 603
   * Goal 4. main.ClassUnderTest.goToDashboardAddEditLoginWidgetContainerPage()V: Line 3214
   * Goal 5. main.ClassUnderTest.goToMenuWidgetsContainerPage(Lcustom_classes/WidgetMenus;)V: Line 2971
   * Goal 6. main.ClassUnderTest.goToPagesPagesContainerPage()V: Line 1946
   * Goal 7. main.ClassUnderTest.goToSiteDashboardContainerPage()V: Line 763
   * Goal 8. main.ClassUnderTest.goToWidgetsPagesContainerPage()V: Line 1982
   * Goal 9. main.ClassUnderTest.moveAllPagesAndLinksToMenuPagesContainerPage(Lcustom_classes/SiteMenus;)V: Line 2000
   */

  @Test(timeout = 1001000)
  public void test13()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      int int0 = 800;
      Id id0 = new Id(int0);
      classUnderTest0.deleteUserOrFeedWidgetDashboardContainerPage(id0);
      classUnderTest0.confirmOperationDeleteItemPage();
      classUnderTest0.goToSiteDashboardContainerPage();
      classUnderTest0.goToPagesPagesContainerPage();
      SiteMenus siteMenus0 = SiteMenus.NOT_LINKED;
      classUnderTest0.moveAllPagesAndLinksToMenuPagesContainerPage(siteMenus0);
      classUnderTest0.goToWidgetsPagesContainerPage();
      WidgetMenus widgetMenus0 = WidgetMenus.UNASSIGNED;
      classUnderTest0.goToMenuWidgetsContainerPage(widgetMenus0);
      classUnderTest0.addLoginWidgetsContainerPage();
      classUnderTest0.goToDashboardAddEditLoginWidgetContainerPage();
  }

  //Test case number: 14
  /*
   * 21 covered goals:
   * Goal 1. main.ClassUnderTest.addLinkPagesContainerPage()V: Line 1706
   * Goal 2. main.ClassUnderTest.addPagePagesContainerPage()V: Line 1747
   * Goal 3. main.ClassUnderTest.addTextWidgetsContainerPage()V: Line 2786
   * Goal 4. main.ClassUnderTest.addUserUserListContainerPage()V: Line 812
   * Goal 5. main.ClassUnderTest.closeOperationAddEditUserContainerPage()V: Line 1285
   * Goal 6. main.ClassUnderTest.goToDashboardAddEditTextWidgetContainerPage()V: Line 2423
   * Goal 7. main.ClassUnderTest.goToEditCurrentUserAddEditLinkContainerPage()V: Line 2655
   * Goal 8. main.ClassUnderTest.goToEditCurrentUserAddEditUserContainerPage()V: Line 1333
   * Goal 9. main.ClassUnderTest.goToEditCurrentUserPagesContainerPage()V: Line 1914
   * Goal 10. main.ClassUnderTest.goToEditCurrentUserUserListContainerPage()V: Line 919
   * Goal 11. main.ClassUnderTest.goToPermissionsAddEditUserContainerPage()V: Line 1346
   * Goal 12. main.ClassUnderTest.goToRolesUserListContainerPage()V: Line 945
   * Goal 13. main.ClassUnderTest.goToSettingsAddEditUserContainerPage()V: Line 1372
   * Goal 14. main.ClassUnderTest.goToSiteAddEditUserContainerPage()V: Line 1385
   * Goal 15. main.ClassUnderTest.goToSiteUserListContainerPage()V: Line 971
   * Goal 16. main.ClassUnderTest.goToUserListPermissionsContainerPage()V: Line 1523
   * Goal 17. main.ClassUnderTest.goToUserListUserSettingsContainerPage()V: Line 1640
   * Goal 18. main.ClassUnderTest.goToUsersAddEditPageContainerPage()V: Line 2305
   * Goal 19. main.ClassUnderTest.goToUsersDashboardContainerPage()V: Line 775
   * Goal 20. main.ClassUnderTest.goToUsersPermissionsContainerPage()V: Line 1535
   * Goal 21. main.ClassUnderTest.goToWidgetsPagesContainerPage()V: Line 1982
   */

  @Test(timeout = 1001000)
  public void test14()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      classUnderTest0.goToUsersDashboardContainerPage();
      classUnderTest0.goToSiteUserListContainerPage();
      classUnderTest0.addPagePagesContainerPage();
      classUnderTest0.goToUsersAddEditPageContainerPage();
      classUnderTest0.goToRolesUserListContainerPage();
      classUnderTest0.goToUsersPermissionsContainerPage();
      classUnderTest0.addUserUserListContainerPage();
      classUnderTest0.closeOperationAddEditUserContainerPage();
      classUnderTest0.goToSiteUserListContainerPage();
      classUnderTest0.goToEditCurrentUserPagesContainerPage();
      classUnderTest0.goToEditCurrentUserAddEditUserContainerPage();
      classUnderTest0.goToSiteAddEditUserContainerPage();
      classUnderTest0.addLinkPagesContainerPage();
      classUnderTest0.goToEditCurrentUserAddEditLinkContainerPage();
      classUnderTest0.goToSettingsAddEditUserContainerPage();
      classUnderTest0.goToUserListUserSettingsContainerPage();
      classUnderTest0.goToEditCurrentUserUserListContainerPage();
      classUnderTest0.goToPermissionsAddEditUserContainerPage();
      classUnderTest0.goToUserListPermissionsContainerPage();
      classUnderTest0.goToSiteUserListContainerPage();
      classUnderTest0.goToWidgetsPagesContainerPage();
      classUnderTest0.addTextWidgetsContainerPage();
      classUnderTest0.goToDashboardAddEditTextWidgetContainerPage();
  }

  //Test case number: 15
  /*
   * 18 covered goals:
   * Goal 1. main.ClassUnderTest.addEditPageRestrictAccessAddEditPageContainerPage(Lcustom_classes/SitePages;Lcustom_classes/HTMLSnippets;Lcustom_classes/PageLinkStatus;Lcustom_classes/UserRoles;Lcustom_classes/HideInMenu;)V: Line 2198
   * Goal 2. main.ClassUnderTest.addLocationWidgetDashboardContainerPage(Lcustom_classes/WidgetLocation;Lcustom_classes/WidgetUnit;)V: Line 533
   * Goal 3. main.ClassUnderTest.addPagePagesContainerPage()V: Line 1747
   * Goal 4. main.ClassUnderTest.addUserWidgetDashboardContainerPage(Lcustom_classes/WidgetUserType;Lcustom_classes/WidgetUserDisplay;Lcustom_classes/WidgetTotalUser;Lcustom_classes/WidgetNumberOfUsers;)V: Line 553
   * Goal 5. main.ClassUnderTest.confirmOperationDeleteItemPage()V: Line 289
   * Goal 6. main.ClassUnderTest.deleteLocationWidgetDashboardContainerPage(Lcustom_classes/Id;)V: Line 575
   * Goal 7. main.ClassUnderTest.deleteUserOrFeedWidgetDashboardContainerPage(Lcustom_classes/Id;)V: Line 603
   * Goal 8. main.ClassUnderTest.goToDashboardDashboardContainerPage()V: Line 713
   * Goal 9. main.ClassUnderTest.goToDashboardUserListContainerPage()V: Line 906
   * Goal 10. main.ClassUnderTest.goToDashboardUserSettingsContainerPage()V: Line 1563
   * Goal 11. main.ClassUnderTest.goToEditCurrentUserDashboardContainerPage()V: Line 726
   * Goal 12. main.ClassUnderTest.goToPagesPagesContainerPage()V: Line 1946
   * Goal 13. main.ClassUnderTest.goToSettingsUserListContainerPage()V: Line 958
   * Goal 14. main.ClassUnderTest.goToSiteAddEditUserContainerPage()V: Line 1385
   * Goal 15. main.ClassUnderTest.goToSitePagesContainerPage()V: Line 1958
   * Goal 16. main.ClassUnderTest.goToUsersAddEditPageContainerPage()V: Line 2305
   * Goal 17. main.ClassUnderTest.goToUsersDashboardContainerPage()V: Line 775
   * Goal 18. main.ClassUnderTest.saveSettingsUserSettingsContainerPage()V: Line 1667
   */

  @Test(timeout = 1001000)
  public void test15()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      WidgetLocation widgetLocation0 = WidgetLocation.TRENTO;
      WidgetUnit widgetUnit0 = WidgetUnit.IMPERIAL;
      classUnderTest0.addLocationWidgetDashboardContainerPage(widgetLocation0, widgetUnit0);
      WidgetUserType widgetUserType0 = WidgetUserType.LASTREGISTERED;
      WidgetUserDisplay widgetUserDisplay0 = WidgetUserDisplay.THUMBNAIL;
      WidgetTotalUser widgetTotalUser0 = WidgetTotalUser.HIDE;
      WidgetNumberOfUsers widgetNumberOfUsers0 = WidgetNumberOfUsers.TWELVE;
      classUnderTest0.addUserWidgetDashboardContainerPage(widgetUserType0, widgetUserDisplay0, widgetTotalUser0, widgetNumberOfUsers0);
      int int0 = (-1246);
      Id id0 = new Id(int0);
      classUnderTest0.goToUsersDashboardContainerPage();
      classUnderTest0.goToSettingsUserListContainerPage();
      classUnderTest0.saveSettingsUserSettingsContainerPage();
      classUnderTest0.goToDashboardUserSettingsContainerPage();
      classUnderTest0.goToDashboardDashboardContainerPage();
      classUnderTest0.deleteLocationWidgetDashboardContainerPage(id0);
      classUnderTest0.goToEditCurrentUserDashboardContainerPage();
      classUnderTest0.goToSiteAddEditUserContainerPage();
      classUnderTest0.goToSitePagesContainerPage();
      classUnderTest0.goToPagesPagesContainerPage();
      classUnderTest0.addPagePagesContainerPage();
      SitePages sitePages0 = SitePages.DAILY_SECTION;
      HTMLSnippets hTMLSnippets0 = HTMLSnippets.HOME;
      PageLinkStatus pageLinkStatus0 = PageLinkStatus.DISABLED;
      UserRoles userRoles0 = UserRoles.ANONYMOUS;
      HideInMenu hideInMenu0 = HideInMenu.NO;
      classUnderTest0.addEditPageRestrictAccessAddEditPageContainerPage(sitePages0, hTMLSnippets0, pageLinkStatus0, userRoles0, hideInMenu0);
      SitePages sitePages1 = SitePages.HOME;
      PageLinkStatus pageLinkStatus1 = PageLinkStatus.DISABLED;
      HideInMenu hideInMenu1 = HideInMenu.YES;
      classUnderTest0.addEditPageRestrictAccessAddEditPageContainerPage(sitePages1, hTMLSnippets0, pageLinkStatus1, userRoles0, hideInMenu1);
      classUnderTest0.goToUsersAddEditPageContainerPage();
      classUnderTest0.goToDashboardUserListContainerPage();
      classUnderTest0.deleteUserOrFeedWidgetDashboardContainerPage(id0);
      classUnderTest0.confirmOperationDeleteItemPage();
  }

  //Test case number: 16
  /*
   * 23 covered goals:
   * Goal 1. main.ClassUnderTest.addItemAddEditItemPage()V: Line 396
   * Goal 2. main.ClassUnderTest.addLocationWidgetDashboardContainerPage(Lcustom_classes/WidgetLocation;Lcustom_classes/WidgetUnit;)V: Line 533
   * Goal 3. main.ClassUnderTest.addMenuPagesContainerPage(Lcustom_classes/SiteMenus;)V: Line 1727
   * Goal 4. main.ClassUnderTest.addPagePagesContainerPage()V: Line 1747
   * Goal 5. main.ClassUnderTest.deleteAllPagesAndLinksPagesContainerPage()V: Line 1767
   * Goal 6. main.ClassUnderTest.editUserWidgetDashboardContainerPage(Lcustom_classes/Id;Lcustom_classes/WidgetUserType;Lcustom_classes/WidgetUserDisplay;Lcustom_classes/WidgetTotalUser;Lcustom_classes/WidgetNumberOfUsers;)V: Line 696
   * Goal 7. main.ClassUnderTest.goToDashboardPagesContainerPage()V: Line 1901
   * Goal 8. main.ClassUnderTest.goToDashboardWidgetsContainerPage()V: Line 2942
   * Goal 9. main.ClassUnderTest.goToEditCurrentUserDashboardContainerPage()V: Line 726
   * Goal 10. main.ClassUnderTest.goToEditCurrentUserPagesContainerPage()V: Line 1914
   * Goal 11. main.ClassUnderTest.goToEditUserDashboardContainerPage(Lcustom_classes/Id;)V: Line 746
   * Goal 12. main.ClassUnderTest.goToPermissionsAddEditUserContainerPage()V: Line 1346
   * Goal 13. main.ClassUnderTest.goToPermissionsPermissionsContainerPage()V: Line 1472
   * Goal 14. main.ClassUnderTest.goToRolesPermissionsContainerPage()V: Line 1485
   * Goal 15. main.ClassUnderTest.goToSettingsUserListContainerPage()V: Line 958
   * Goal 16. main.ClassUnderTest.goToSettingsUserSettingsContainerPage()V: Line 1615
   * Goal 17. main.ClassUnderTest.goToSiteAddEditPageContainerPage()V: Line 2293
   * Goal 18. main.ClassUnderTest.goToSiteAddEditUserContainerPage()V: Line 1385
   * Goal 19. main.ClassUnderTest.goToSiteDashboardContainerPage()V: Line 763
   * Goal 20. main.ClassUnderTest.goToSitePermissionsContainerPage()V: Line 1511
   * Goal 21. main.ClassUnderTest.goToSiteUserSettingsContainerPage()V: Line 1628
   * Goal 22. main.ClassUnderTest.goToUsersAddEditUserContainerPage()V: Line 1409
   * Goal 23. main.ClassUnderTest.goToWidgetsPagesContainerPage()V: Line 1982
   */

  @Test(timeout = 1001000)
  public void test16()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      int int0 = 3510;
      Id id0 = new Id(int0);
      WidgetUserType widgetUserType0 = WidgetUserType.LOGGEDIN;
      WidgetUserDisplay widgetUserDisplay0 = WidgetUserDisplay.LIST;
      WidgetTotalUser widgetTotalUser0 = WidgetTotalUser.HIDE;
      WidgetNumberOfUsers widgetNumberOfUsers0 = WidgetNumberOfUsers.SIX;
      classUnderTest0.editUserWidgetDashboardContainerPage(id0, widgetUserType0, widgetUserDisplay0, widgetTotalUser0, widgetNumberOfUsers0);
      WidgetLocation widgetLocation0 = WidgetLocation.TRENTO;
      WidgetUnit widgetUnit0 = WidgetUnit.IMPERIAL;
      classUnderTest0.addLocationWidgetDashboardContainerPage(widgetLocation0, widgetUnit0);
      classUnderTest0.goToEditCurrentUserDashboardContainerPage();
      classUnderTest0.goToPermissionsAddEditUserContainerPage();
      classUnderTest0.goToPermissionsPermissionsContainerPage();
      classUnderTest0.goToRolesPermissionsContainerPage();
      SiteMenus siteMenus0 = SiteMenus.OTHER_MENU;
      classUnderTest0.goToSitePermissionsContainerPage();
      classUnderTest0.goToEditCurrentUserPagesContainerPage();
      classUnderTest0.goToUsersAddEditUserContainerPage();
      classUnderTest0.goToSettingsUserListContainerPage();
      classUnderTest0.goToSettingsUserSettingsContainerPage();
      classUnderTest0.goToSiteUserSettingsContainerPage();
      classUnderTest0.deleteAllPagesAndLinksPagesContainerPage();
      classUnderTest0.goToDashboardPagesContainerPage();
      classUnderTest0.goToSiteDashboardContainerPage();
      classUnderTest0.addMenuPagesContainerPage(siteMenus0);
      classUnderTest0.addItemAddEditItemPage();
      classUnderTest0.addPagePagesContainerPage();
      classUnderTest0.goToSiteAddEditPageContainerPage();
      classUnderTest0.goToWidgetsPagesContainerPage();
      classUnderTest0.goToDashboardWidgetsContainerPage();
      classUnderTest0.goToEditUserDashboardContainerPage(id0);
      classUnderTest0.goToSiteAddEditUserContainerPage();
  }

  //Test case number: 17
  /*
   * 9 covered goals:
   * Goal 1. main.ClassUnderTest.addMenuWidgetsContainerPage()V: Line 2772
   * Goal 2. main.ClassUnderTest.addUserUserListContainerPage()V: Line 812
   * Goal 3. main.ClassUnderTest.editUserAddEditUserContainerPage(Lcustom_classes/Username;Lcustom_classes/Name;Lcustom_classes/Email;Lcustom_classes/UserPassword;)V: Line 1303
   * Goal 4. main.ClassUnderTest.goToEditCurrentUserAddEditMenuWidgetContainerPage()V: Line 3504
   * Goal 5. main.ClassUnderTest.goToEditCurrentUserAddEditUserContainerPage()V: Line 1333
   * Goal 6. main.ClassUnderTest.goToSettingsAddEditUserContainerPage()V: Line 1372
   * Goal 7. main.ClassUnderTest.goToSiteUserSettingsContainerPage()V: Line 1628
   * Goal 8. main.ClassUnderTest.goToUsersDashboardContainerPage()V: Line 775
   * Goal 9. main.ClassUnderTest.goToWidgetsPagesContainerPage()V: Line 1982
   */

  @Test(timeout = 1001000)
  public void test17()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      classUnderTest0.goToUsersDashboardContainerPage();
      classUnderTest0.addUserUserListContainerPage();
      Name name0 = Name.JOHN;
      Email email0 = Email.ASD;
      UserPassword userPassword0 = UserPassword.FOO;
      classUnderTest0.goToEditCurrentUserAddEditUserContainerPage();
      classUnderTest0.goToEditCurrentUserAddEditUserContainerPage();
      Username username0 = Username.FOO;
      classUnderTest0.editUserAddEditUserContainerPage(username0, name0, email0, userPassword0);
      classUnderTest0.goToSettingsAddEditUserContainerPage();
      classUnderTest0.goToSiteUserSettingsContainerPage();
      classUnderTest0.goToWidgetsPagesContainerPage();
      classUnderTest0.addMenuWidgetsContainerPage();
      classUnderTest0.goToEditCurrentUserAddEditMenuWidgetContainerPage();
  }

  //Test case number: 18
  /*
   * 11 covered goals:
   * Goal 1. main.ClassUnderTest.addFeedWidgetDashboardContainerPage(Lcustom_classes/WidgetFeedTitle;Lcustom_classes/WidgetFeedUrl;Lcustom_classes/WidgetFeedNumberOfPosts;Lcustom_classes/WidgetFeedPostContent;)V: Line 515
   * Goal 2. main.ClassUnderTest.addUserWidgetDashboardContainerPage(Lcustom_classes/WidgetUserType;Lcustom_classes/WidgetUserDisplay;Lcustom_classes/WidgetTotalUser;Lcustom_classes/WidgetNumberOfUsers;)V: Line 553
   * Goal 3. main.ClassUnderTest.cancelOperationDeleteItemPage()V: Line 252
   * Goal 4. main.ClassUnderTest.closeOperationAddEditUserContainerPage()V: Line 1285
   * Goal 5. main.ClassUnderTest.deleteUserOrFeedWidgetDashboardContainerPage(Lcustom_classes/Id;)V: Line 603
   * Goal 6. main.ClassUnderTest.goToEditCurrentUserPagesContainerPage()V: Line 1914
   * Goal 7. main.ClassUnderTest.goToEditCurrentUserUserListContainerPage()V: Line 919
   * Goal 8. main.ClassUnderTest.goToMenuPagesContainerPage(Lcustom_classes/SiteMenus;)V: Line 1929
   * Goal 9. main.ClassUnderTest.goToRolesAddEditUserContainerPage()V: Line 1359
   * Goal 10. main.ClassUnderTest.goToSiteDashboardContainerPage()V: Line 763
   * Goal 11. main.ClassUnderTest.goToSitePagesContainerPage()V: Line 1958
   */

  @Test(timeout = 1001000)
  public void test18()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      int int0 = (-2687);
      Id id0 = new Id(int0);
      WidgetFeedTitle widgetFeedTitle0 = WidgetFeedTitle.PAGEKITNEWS;
      WidgetFeedUrl widgetFeedUrl0 = WidgetFeedUrl.SPORT;
      WidgetFeedNumberOfPosts widgetFeedNumberOfPosts0 = new WidgetFeedNumberOfPosts(id0.value);
      WidgetFeedPostContent widgetFeedPostContent0 = WidgetFeedPostContent.SHOWFIRSTPOST;
      classUnderTest0.addFeedWidgetDashboardContainerPage(widgetFeedTitle0, widgetFeedUrl0, widgetFeedNumberOfPosts0, widgetFeedPostContent0);
      WidgetUserType widgetUserType0 = WidgetUserType.LOGGEDIN;
      WidgetUserDisplay widgetUserDisplay0 = WidgetUserDisplay.THUMBNAIL;
      WidgetTotalUser widgetTotalUser0 = WidgetTotalUser.SHOW;
      WidgetNumberOfUsers widgetNumberOfUsers0 = WidgetNumberOfUsers.TWELVE;
      classUnderTest0.addUserWidgetDashboardContainerPage(widgetUserType0, widgetUserDisplay0, widgetTotalUser0, widgetNumberOfUsers0);
      classUnderTest0.deleteUserOrFeedWidgetDashboardContainerPage(id0);
      classUnderTest0.cancelOperationDeleteItemPage();
      classUnderTest0.goToSiteDashboardContainerPage();
      classUnderTest0.goToSitePagesContainerPage();
      SiteMenus siteMenus0 = SiteMenus.NOT_LINKED;
      classUnderTest0.goToMenuPagesContainerPage(siteMenus0);
      classUnderTest0.goToEditCurrentUserPagesContainerPage();
      classUnderTest0.closeOperationAddEditUserContainerPage();
      classUnderTest0.goToEditCurrentUserUserListContainerPage();
      classUnderTest0.goToRolesAddEditUserContainerPage();
  }

  //Test case number: 19
  /*
   * 19 covered goals:
   * Goal 1. main.ClassUnderTest.addLoginWidgetsContainerPage()V: Line 2758
   * Goal 2. main.ClassUnderTest.addTextWidgetsContainerPage()V: Line 2786
   * Goal 3. main.ClassUnderTest.addUserUserListContainerPage()V: Line 812
   * Goal 4. main.ClassUnderTest.closeOperationAddEditUserContainerPage()V: Line 1285
   * Goal 5. main.ClassUnderTest.goToDashboardAddEditUserContainerPage()V: Line 1320
   * Goal 6. main.ClassUnderTest.goToDashboardPermissionsContainerPage()V: Line 1446
   * Goal 7. main.ClassUnderTest.goToEditCurrentUserDashboardContainerPage()V: Line 726
   * Goal 8. main.ClassUnderTest.goToEditCurrentUserPagesContainerPage()V: Line 1914
   * Goal 9. main.ClassUnderTest.goToEditUserDashboardContainerPage(Lcustom_classes/Id;)V: Line 746
   * Goal 10. main.ClassUnderTest.goToPagesAddEditTextWidgetContainerPage()V: Line 2449
   * Goal 11. main.ClassUnderTest.goToPermissionsPermissionsContainerPage()V: Line 1472
   * Goal 12. main.ClassUnderTest.goToRolesUserSettingsContainerPage()V: Line 1602
   * Goal 13. main.ClassUnderTest.goToSettingsUserListContainerPage()V: Line 958
   * Goal 14. main.ClassUnderTest.goToSiteAddEditUserContainerPage()V: Line 1385
   * Goal 15. main.ClassUnderTest.goToSitePagesContainerPage()V: Line 1958
   * Goal 16. main.ClassUnderTest.goToUsersAddEditUserContainerPage()V: Line 1409
   * Goal 17. main.ClassUnderTest.goToUsersUserListContainerPage()V: Line 995
   * Goal 18. main.ClassUnderTest.goToWidgetsAddEditLoginWidgetContainerPage()V: Line 3302
   * Goal 19. main.ClassUnderTest.goToWidgetsPagesContainerPage()V: Line 1982
   */

  @Test(timeout = 1001000)
  public void test19()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      classUnderTest0.goToEditCurrentUserDashboardContainerPage();
      classUnderTest0.goToUsersAddEditUserContainerPage();
      classUnderTest0.goToUsersUserListContainerPage();
      classUnderTest0.goToSettingsUserListContainerPage();
      classUnderTest0.goToRolesUserSettingsContainerPage();
      int int0 = 4439;
      Id id0 = new Id(int0);
      Id id1 = new Id(id0.value);
      classUnderTest0.goToPermissionsPermissionsContainerPage();
      classUnderTest0.goToDashboardPermissionsContainerPage();
      classUnderTest0.goToEditUserDashboardContainerPage(id1);
      classUnderTest0.goToSiteAddEditUserContainerPage();
      classUnderTest0.goToWidgetsPagesContainerPage();
      classUnderTest0.addTextWidgetsContainerPage();
      classUnderTest0.goToPagesAddEditTextWidgetContainerPage();
      classUnderTest0.goToEditCurrentUserPagesContainerPage();
      classUnderTest0.closeOperationAddEditUserContainerPage();
      classUnderTest0.addUserUserListContainerPage();
      classUnderTest0.goToDashboardAddEditUserContainerPage();
      classUnderTest0.goToEditCurrentUserDashboardContainerPage();
      classUnderTest0.goToSiteAddEditUserContainerPage();
      classUnderTest0.goToSitePagesContainerPage();
      classUnderTest0.goToWidgetsPagesContainerPage();
      classUnderTest0.addLoginWidgetsContainerPage();
      classUnderTest0.goToWidgetsAddEditLoginWidgetContainerPage();
  }

  //Test case number: 20
  /*
   * 15 covered goals:
   * Goal 1. main.ClassUnderTest.addLoginWidgetsContainerPage()V: Line 2758
   * Goal 2. main.ClassUnderTest.addUserWidgetDashboardContainerPage(Lcustom_classes/WidgetUserType;Lcustom_classes/WidgetUserDisplay;Lcustom_classes/WidgetTotalUser;Lcustom_classes/WidgetNumberOfUsers;)V: Line 553
   * Goal 3. main.ClassUnderTest.closeOperationAddEditUserContainerPage()V: Line 1285
   * Goal 4. main.ClassUnderTest.goToDashboardPagesContainerPage()V: Line 1901
   * Goal 5. main.ClassUnderTest.goToDashboardUserListContainerPage()V: Line 906
   * Goal 6. main.ClassUnderTest.goToEditCurrentUserPermissionsContainerPage()V: Line 1459
   * Goal 7. main.ClassUnderTest.goToPagesPagesContainerPage()V: Line 1946
   * Goal 8. main.ClassUnderTest.goToPagesWidgetsContainerPage()V: Line 2988
   * Goal 9. main.ClassUnderTest.goToPermissionsUserListContainerPage()V: Line 932
   * Goal 10. main.ClassUnderTest.goToSiteDashboardContainerPage()V: Line 763
   * Goal 11. main.ClassUnderTest.goToSitePagesContainerPage()V: Line 1958
   * Goal 12. main.ClassUnderTest.goToSiteUserListContainerPage()V: Line 971
   * Goal 13. main.ClassUnderTest.goToUsersDashboardContainerPage()V: Line 775
   * Goal 14. main.ClassUnderTest.goToWidgetsPagesContainerPage()V: Line 1982
   * Goal 15. main.ClassUnderTest.unpublishAllPagesAndLinksPagesContainerPage()V: Line 2091
   */

  @Test(timeout = 1001000)
  public void test20()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      classUnderTest0.goToSiteDashboardContainerPage();
      classUnderTest0.goToDashboardPagesContainerPage();
      classUnderTest0.goToUsersDashboardContainerPage();
      classUnderTest0.goToDashboardUserListContainerPage();
      WidgetUserType widgetUserType0 = WidgetUserType.LOGGEDIN;
      WidgetUserDisplay widgetUserDisplay0 = WidgetUserDisplay.LIST;
      WidgetTotalUser widgetTotalUser0 = WidgetTotalUser.HIDE;
      WidgetNumberOfUsers widgetNumberOfUsers0 = WidgetNumberOfUsers.TWENTYFOUR;
      classUnderTest0.addUserWidgetDashboardContainerPage(widgetUserType0, widgetUserDisplay0, widgetTotalUser0, widgetNumberOfUsers0);
      classUnderTest0.goToUsersDashboardContainerPage();
      classUnderTest0.goToPermissionsUserListContainerPage();
      classUnderTest0.goToEditCurrentUserPermissionsContainerPage();
      classUnderTest0.closeOperationAddEditUserContainerPage();
      classUnderTest0.goToSiteUserListContainerPage();
      classUnderTest0.goToSitePagesContainerPage();
      classUnderTest0.goToPagesPagesContainerPage();
      classUnderTest0.goToWidgetsPagesContainerPage();
      classUnderTest0.goToPagesWidgetsContainerPage();
      classUnderTest0.unpublishAllPagesAndLinksPagesContainerPage();
      classUnderTest0.goToWidgetsPagesContainerPage();
      classUnderTest0.addLoginWidgetsContainerPage();
  }

  //Test case number: 21
  /*
   * 8 covered goals:
   * Goal 1. main.ClassUnderTest.closeOperationAddEditUserContainerPage()V: Line 1285
   * Goal 2. main.ClassUnderTest.goToDashboardUserListContainerPage()V: Line 906
   * Goal 3. main.ClassUnderTest.goToEditCurrentUserDashboardContainerPage()V: Line 726
   * Goal 4. main.ClassUnderTest.goToPermissionsUserSettingsContainerPage()V: Line 1589
   * Goal 5. main.ClassUnderTest.goToRolesPermissionsContainerPage()V: Line 1485
   * Goal 6. main.ClassUnderTest.goToSettingsUserListContainerPage()V: Line 958
   * Goal 7. main.ClassUnderTest.goToSiteDashboardContainerPage()V: Line 763
   * Goal 8. main.ClassUnderTest.goToUsersPagesContainerPage()V: Line 1970
   */

  @Test(timeout = 1001000)
  public void test21()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      classUnderTest0.goToEditCurrentUserDashboardContainerPage();
      classUnderTest0.closeOperationAddEditUserContainerPage();
      classUnderTest0.goToDashboardUserListContainerPage();
      classUnderTest0.goToSiteDashboardContainerPage();
      classUnderTest0.goToUsersPagesContainerPage();
      classUnderTest0.goToSettingsUserListContainerPage();
      classUnderTest0.goToPermissionsUserSettingsContainerPage();
      classUnderTest0.goToRolesPermissionsContainerPage();
  }

  //Test case number: 22
  /*
   * 12 covered goals:
   * Goal 1. main.ClassUnderTest.addMenuWidgetsContainerPage()V: Line 2772
   * Goal 2. main.ClassUnderTest.addUserUserListContainerPage()V: Line 812
   * Goal 3. main.ClassUnderTest.addUserWidgetDashboardContainerPage(Lcustom_classes/WidgetUserType;Lcustom_classes/WidgetUserDisplay;Lcustom_classes/WidgetTotalUser;Lcustom_classes/WidgetNumberOfUsers;)V: Line 553
   * Goal 4. main.ClassUnderTest.editLocationWidgetDashboardContainerPage(Lcustom_classes/Id;Lcustom_classes/WidgetLocation;Lcustom_classes/WidgetUnit;)V: Line 664
   * Goal 5. main.ClassUnderTest.goToDashboardDashboardContainerPage()V: Line 713
   * Goal 6. main.ClassUnderTest.goToEditCurrentUserPermissionsContainerPage()V: Line 1459
   * Goal 7. main.ClassUnderTest.goToPagesPagesContainerPage()V: Line 1946
   * Goal 8. main.ClassUnderTest.goToRolesAddEditUserContainerPage()V: Line 1359
   * Goal 9. main.ClassUnderTest.goToSettingsAddEditMenuWidgetContainerPage()V: Line 3529
   * Goal 10. main.ClassUnderTest.goToSiteAddEditUserContainerPage()V: Line 1385
   * Goal 11. main.ClassUnderTest.goToUsersDashboardContainerPage()V: Line 775
   * Goal 12. main.ClassUnderTest.goToWidgetsPagesContainerPage()V: Line 1982
   */

  @Test(timeout = 1001000)
  public void test22()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      WidgetUserType widgetUserType0 = WidgetUserType.LASTREGISTERED;
      WidgetUserDisplay widgetUserDisplay0 = WidgetUserDisplay.LIST;
      WidgetTotalUser widgetTotalUser0 = WidgetTotalUser.SHOW;
      WidgetNumberOfUsers widgetNumberOfUsers0 = WidgetNumberOfUsers.EIGHTEEN;
      classUnderTest0.addUserWidgetDashboardContainerPage(widgetUserType0, widgetUserDisplay0, widgetTotalUser0, widgetNumberOfUsers0);
      int int0 = (-4);
      Id id0 = new Id(int0);
      WidgetLocation widgetLocation0 = WidgetLocation.TRENTO;
      WidgetUnit widgetUnit0 = WidgetUnit.METRIC;
      classUnderTest0.editLocationWidgetDashboardContainerPage(id0, widgetLocation0, widgetUnit0);
      classUnderTest0.goToDashboardDashboardContainerPage();
      classUnderTest0.goToUsersDashboardContainerPage();
      classUnderTest0.addUserUserListContainerPage();
      classUnderTest0.goToRolesAddEditUserContainerPage();
      classUnderTest0.goToEditCurrentUserPermissionsContainerPage();
      classUnderTest0.goToSiteAddEditUserContainerPage();
      classUnderTest0.goToPagesPagesContainerPage();
      classUnderTest0.goToWidgetsPagesContainerPage();
      classUnderTest0.addMenuWidgetsContainerPage();
      classUnderTest0.goToSettingsAddEditMenuWidgetContainerPage();
  }

  //Test case number: 23
  /*
   * 8 covered goals:
   * Goal 1. main.ClassUnderTest.addLinkPagesContainerPage()V: Line 1706
   * Goal 2. main.ClassUnderTest.addPagePagesContainerPage()V: Line 1747
   * Goal 3. main.ClassUnderTest.deleteAllPagesAndLinksPagesContainerPage()V: Line 1767
   * Goal 4. main.ClassUnderTest.goToDashboardPagesContainerPage()V: Line 1901
   * Goal 5. main.ClassUnderTest.goToSiteAddEditLinkContainerPage()V: Line 2706
   * Goal 6. main.ClassUnderTest.goToSiteAddEditPageContainerPage()V: Line 2293
   * Goal 7. main.ClassUnderTest.goToSiteDashboardContainerPage()V: Line 763
   * Goal 8. main.ClassUnderTest.goToSitePagesContainerPage()V: Line 1958
   */

  @Test(timeout = 1001000)
  public void test23()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      classUnderTest0.goToSiteDashboardContainerPage();
      classUnderTest0.deleteAllPagesAndLinksPagesContainerPage();
      classUnderTest0.addLinkPagesContainerPage();
      classUnderTest0.goToSiteAddEditLinkContainerPage();
      classUnderTest0.goToDashboardPagesContainerPage();
      classUnderTest0.goToSiteDashboardContainerPage();
      classUnderTest0.goToSitePagesContainerPage();
      classUnderTest0.goToSitePagesContainerPage();
      classUnderTest0.addPagePagesContainerPage();
      classUnderTest0.goToSiteAddEditPageContainerPage();
  }

  //Test case number: 24
  /*
   * 17 covered goals:
   * Goal 1. main.ClassUnderTest.changeSettingsUserSettingsContainerPage(Lcustom_classes/RegistrationUserSettings;)V: Line 1550
   * Goal 2. main.ClassUnderTest.editUserAddEditUserContainerPage(Lcustom_classes/Username;Lcustom_classes/Name;Lcustom_classes/Email;Lcustom_classes/UserPassword;)V: Line 1303
   * Goal 3. main.ClassUnderTest.goToDashboardAddEditUserContainerPage()V: Line 1320
   * Goal 4. main.ClassUnderTest.goToDashboardPagesContainerPage()V: Line 1901
   * Goal 5. main.ClassUnderTest.goToDashboardUserListContainerPage()V: Line 906
   * Goal 6. main.ClassUnderTest.goToEditCurrentUserDashboardContainerPage()V: Line 726
   * Goal 7. main.ClassUnderTest.goToEditCurrentUserPermissionsContainerPage()V: Line 1459
   * Goal 8. main.ClassUnderTest.goToPermissionsUserListContainerPage()V: Line 932
   * Goal 9. main.ClassUnderTest.goToRolesUserListContainerPage()V: Line 945
   * Goal 10. main.ClassUnderTest.goToSettingsAddEditUserContainerPage()V: Line 1372
   * Goal 11. main.ClassUnderTest.goToSettingsUserSettingsContainerPage()V: Line 1615
   * Goal 12. main.ClassUnderTest.goToSiteDashboardContainerPage()V: Line 763
   * Goal 13. main.ClassUnderTest.goToUserListUserListContainerPage()V: Line 983
   * Goal 14. main.ClassUnderTest.goToUsersAddEditUserContainerPage()V: Line 1409
   * Goal 15. main.ClassUnderTest.goToUsersDashboardContainerPage()V: Line 775
   * Goal 16. main.ClassUnderTest.goToUsersWidgetsContainerPage()V: Line 3012
   * Goal 17. main.ClassUnderTest.goToWidgetsPagesContainerPage()V: Line 1982
   */

  @Test(timeout = 1001000)
  public void test24()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      classUnderTest0.goToSiteDashboardContainerPage();
      classUnderTest0.goToDashboardPagesContainerPage();
      classUnderTest0.goToUsersDashboardContainerPage();
      classUnderTest0.goToDashboardUserListContainerPage();
      classUnderTest0.goToSiteDashboardContainerPage();
      classUnderTest0.goToWidgetsPagesContainerPage();
      classUnderTest0.goToUsersWidgetsContainerPage();
      classUnderTest0.goToPermissionsUserListContainerPage();
      classUnderTest0.goToEditCurrentUserPermissionsContainerPage();
      classUnderTest0.goToUsersAddEditUserContainerPage();
      classUnderTest0.goToUserListUserListContainerPage();
      classUnderTest0.goToRolesUserListContainerPage();
      classUnderTest0.goToEditCurrentUserPermissionsContainerPage();
      classUnderTest0.goToDashboardAddEditUserContainerPage();
      classUnderTest0.goToEditCurrentUserDashboardContainerPage();
      Email email0 = Email.ASD;
      UserPassword userPassword0 = UserPassword.ADMIN;
      Username username0 = Username.ADMIN;
      Name name0 = Name.MARK;
      classUnderTest0.editUserAddEditUserContainerPage(username0, name0, email0, userPassword0);
      Username username1 = Username.ADMIN;
      Name name1 = Name.JOHN;
      Email email1 = Email.FOO;
      UserPassword userPassword1 = UserPassword.FOO;
      classUnderTest0.editUserAddEditUserContainerPage(username1, name1, email1, userPassword1);
      classUnderTest0.goToSettingsAddEditUserContainerPage();
      classUnderTest0.goToSettingsUserSettingsContainerPage();
      RegistrationUserSettings registrationUserSettings0 = RegistrationUserSettings.DISABLED;
      classUnderTest0.changeSettingsUserSettingsContainerPage(registrationUserSettings0);
  }

  //Test case number: 25
  /*
   * 5 covered goals:
   * Goal 1. main.ClassUnderTest.addTextWidgetsContainerPage()V: Line 2786
   * Goal 2. main.ClassUnderTest.deleteLocationWidgetDashboardContainerPage(Lcustom_classes/Id;)V: Line 575
   * Goal 3. main.ClassUnderTest.goToSiteDashboardContainerPage()V: Line 763
   * Goal 4. main.ClassUnderTest.goToWidgetsAddEditTextWidgetContainerPage()V: Line 2511
   * Goal 5. main.ClassUnderTest.goToWidgetsPagesContainerPage()V: Line 1982
   */

  @Test(timeout = 1001000)
  public void test25()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      int int0 = 1363;
      Id id0 = new Id(int0);
      classUnderTest0.deleteLocationWidgetDashboardContainerPage(id0);
      classUnderTest0.goToSiteDashboardContainerPage();
      classUnderTest0.goToWidgetsPagesContainerPage();
      classUnderTest0.addTextWidgetsContainerPage();
      classUnderTest0.goToWidgetsAddEditTextWidgetContainerPage();
  }

  //Test case number: 26
  /*
   * 16 covered goals:
   * Goal 1. main.ClassUnderTest.cancelOperationDeleteItemPage()V: Line 252
   * Goal 2. main.ClassUnderTest.deleteAllPagesAndLinksPagesContainerPage()V: Line 1767
   * Goal 3. main.ClassUnderTest.deleteUserOrFeedWidgetDashboardContainerPage(Lcustom_classes/Id;)V: Line 603
   * Goal 4. main.ClassUnderTest.editUserAddEditUserContainerPage(Lcustom_classes/Username;Lcustom_classes/Name;Lcustom_classes/Email;Lcustom_classes/UserPassword;)V: Line 1303
   * Goal 5. main.ClassUnderTest.giveOrRemoveAllPermissionsToUserRolePermissionsContainerPage(Lcustom_classes/UserRoles;)V: Line 1428
   * Goal 6. main.ClassUnderTest.goToDashboardPagesContainerPage()V: Line 1901
   * Goal 7. main.ClassUnderTest.goToEditCurrentUserAddEditUserContainerPage()V: Line 1333
   * Goal 8. main.ClassUnderTest.goToEditCurrentUserPermissionsContainerPage()V: Line 1459
   * Goal 9. main.ClassUnderTest.goToEditCurrentUserUserSettingsContainerPage()V: Line 1576
   * Goal 10. main.ClassUnderTest.goToEditUserDashboardContainerPage(Lcustom_classes/Id;)V: Line 746
   * Goal 11. main.ClassUnderTest.goToPermissionsUserListContainerPage()V: Line 932
   * Goal 12. main.ClassUnderTest.goToRolesPermissionsContainerPage()V: Line 1485
   * Goal 13. main.ClassUnderTest.goToSettingsAddEditUserContainerPage()V: Line 1372
   * Goal 14. main.ClassUnderTest.goToSiteAddEditUserContainerPage()V: Line 1385
   * Goal 15. main.ClassUnderTest.goToUsersAddEditUserContainerPage()V: Line 1409
   * Goal 16. main.ClassUnderTest.publishAllPagesAndLinksPagesContainerPage()V: Line 2047
   */

  @Test(timeout = 1001000)
  public void test26()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      int int0 = (-2604);
      Id id0 = new Id(int0);
      classUnderTest0.goToEditUserDashboardContainerPage(id0);
      classUnderTest0.goToSettingsAddEditUserContainerPage();
      classUnderTest0.goToEditCurrentUserUserSettingsContainerPage();
      Username username0 = Username.ADMIN;
      Name name0 = Name.JOHN;
      Email email0 = Email.ASD;
      UserPassword userPassword0 = UserPassword.ADMIN;
      classUnderTest0.editUserAddEditUserContainerPage(username0, name0, email0, userPassword0);
      Username username1 = Username.FOO;
      UserPassword userPassword1 = UserPassword.ADMIN;
      classUnderTest0.editUserAddEditUserContainerPage(username1, name0, email0, userPassword1);
      classUnderTest0.goToUsersAddEditUserContainerPage();
      classUnderTest0.goToPermissionsUserListContainerPage();
      UserRoles userRoles0 = UserRoles.AUTHENTICATED;
      classUnderTest0.giveOrRemoveAllPermissionsToUserRolePermissionsContainerPage(userRoles0);
      classUnderTest0.goToRolesPermissionsContainerPage();
      classUnderTest0.goToEditCurrentUserPermissionsContainerPage();
      classUnderTest0.goToEditCurrentUserAddEditUserContainerPage();
      classUnderTest0.goToSiteAddEditUserContainerPage();
      classUnderTest0.publishAllPagesAndLinksPagesContainerPage();
      classUnderTest0.deleteAllPagesAndLinksPagesContainerPage();
      classUnderTest0.goToDashboardPagesContainerPage();
      classUnderTest0.deleteUserOrFeedWidgetDashboardContainerPage(id0);
      classUnderTest0.cancelOperationDeleteItemPage();
  }

  //Test case number: 27
  /*
   * 9 covered goals:
   * Goal 1. main.ClassUnderTest.addLinkPagesContainerPage()V: Line 1706
   * Goal 2. main.ClassUnderTest.deleteAllPagesAndLinksPagesContainerPage()V: Line 1767
   * Goal 3. main.ClassUnderTest.goToDashboardDashboardContainerPage()V: Line 713
   * Goal 4. main.ClassUnderTest.goToEditCurrentUserDashboardContainerPage()V: Line 726
   * Goal 5. main.ClassUnderTest.goToPermissionsAddEditUserContainerPage()V: Line 1346
   * Goal 6. main.ClassUnderTest.goToSiteUserListContainerPage()V: Line 971
   * Goal 7. main.ClassUnderTest.goToUserListPermissionsContainerPage()V: Line 1523
   * Goal 8. main.ClassUnderTest.selectLinkStorageSelectLinkPage(Lcustom_classes/Extension;)V: Line 126
   * Goal 9. main.ClassUnderTest.selectUrlAddEditLinkContainerPage()V: Line 2744
   */

  @Test(timeout = 1001000)
  public void test27()  throws Throwable  {
      ClassUnderTest classUnderTest0 = new ClassUnderTest();
      classUnderTest0.goToDashboardDashboardContainerPage();
      classUnderTest0.goToEditCurrentUserDashboardContainerPage();
      classUnderTest0.goToPermissionsAddEditUserContainerPage();
      classUnderTest0.goToUserListPermissionsContainerPage();
      classUnderTest0.goToSiteUserListContainerPage();
      classUnderTest0.deleteAllPagesAndLinksPagesContainerPage();
      classUnderTest0.addLinkPagesContainerPage();
      classUnderTest0.selectUrlAddEditLinkContainerPage();
      Extension extension0 = Extension.STORAGE;
      classUnderTest0.selectLinkStorageSelectLinkPage(extension0);
  }
}
